/**
 * Node-safe single source of truth for per-lesson training-image generation.
 *
 * This module deliberately contains NO React Native imports and NO `require()`
 * of image assets, so it can be imported both by the React Native runtime
 * manifest (`lessonImageManifest.ts`) and by the plain Node generation script
 * (`scripts/generateLessonImages.ts`) without pulling in the bundler.
 *
 * Every entry corresponds to exactly one active production lesson id. The list
 * is kept in the same order as `productionLessonDefinitions`.
 */

export type BehaviourSkillId =
  | 'recall'
  | 'loose-lead-walking'
  | 'focus'
  | 'jumping'
  | 'barking'
  | 'chewing'
  | 'reactivity'
  | 'house-training'
  | 'confidence'
  | 'impulse-control';

export interface LessonImageSpec {
  /** Unique, active production lesson id (matches the lesson catalogue). */
  readonly lessonId: string;
  readonly title: string;
  readonly skill: BehaviourSkillId;
  /** The exact behaviour the lesson teaches. */
  readonly behaviour: string;
  /** The exact visible dog-training action the image must depict. */
  readonly visibleAction: string;
  readonly breed: string;
  readonly size: string;
  readonly age: string;
  readonly environment: string;
  readonly handlerPosition: string;
  readonly rewardPlacement: string;
  /** Camera angle and framing. */
  readonly cameraFraming: string;
  readonly lighting: string;
  /** Destination filename under assets/lesson-images/by-lesson/. */
  readonly destinationFilename: string;
  /** Full positive photorealistic generation prompt. */
  readonly prompt: string;
  /** Negative prompt requirements. */
  readonly negativePrompt: string;
}

/**
 * Shared negative-prompt baseline. Enforces photorealism and humane,
 * positive-reinforcement handling. Individual lessons may append extra
 * lesson-specific exclusions.
 */
export const SHARED_NEGATIVE_PROMPT =
  'cartoon, illustration, drawing, painting, digital painting, storybook art, ' +
  'anime, 3d render, cgi, render, vector art, sketch, watercolour, flat shading, ' +
  'text, caption, watermark, logo, signature, border, ' +
  'deformed anatomy, extra limbs, missing limbs, fused paws, distorted face, ' +
  'prong collar, choke chain, choke collar, shock collar, e-collar, ' +
  'tight leash, tense leash, choking, yanking, fear, cowering, punishment, ' +
  'intimidation, harsh handling';

const withExtra = (extra?: string): string =>
  extra ? `${SHARED_NEGATIVE_PROMPT}, ${extra}` : SHARED_NEGATIVE_PROMPT;

const photoPrefix = 'Photorealistic candid documentary-style colour photograph of ';
const photoSuffix =
  '. Shot on a full-frame DSLR with a 35mm lens, natural light, shallow depth of field, ' +
  'true-to-life canine anatomy, gentle positive-reinforcement dog training, ' +
  '3:2 landscape composition suitable for mobile cropping, high resolution, sharp focus.';

const spec = (
  base: Omit<LessonImageSpec, 'prompt' | 'negativePrompt'>,
  scene: string,
  extraNegative?: string,
): LessonImageSpec => ({
  ...base,
  prompt: `${photoPrefix}${scene}${photoSuffix}`,
  negativePrompt: withExtra(extraNegative),
});

export const lessonImageGenerationSpecs: readonly LessonImageSpec[] = Object.freeze([
  // ---- Recall ----
  spec(
    {
      lessonId: 'recall-name-response',
      title: 'Name Response',
      skill: 'recall',
      behaviour: 'A quick, happy head-turn towards the handler when the dog hears its name.',
      visibleAction: 'The dog turns its head and makes eye contact with the handler on hearing its name.',
      breed: 'Golden Retriever',
      size: 'Small (young puppy)',
      age: 'Puppy, about 4 months',
      environment: 'Bright, tidy modern living room with soft natural daylight',
      handlerPosition: 'Crouched low nearby, one hand visible near the knees',
      rewardPlacement: 'Treat held low near the handler’s knees, ready to deliver at chest height',
      cameraFraming: 'Eye-level medium close-up on the puppy’s joyful expression, 3:2 landscape',
      lighting: 'Soft indoor window daylight',
      destinationFilename: 'recall-name-response.jpg',
    },
    'a friendly Golden Retriever puppy turning its head and making happy eye contact with its crouching owner in a bright modern living room, the owner’s hand visible holding a small reward low near the knees',
  ),
  spec(
    {
      lessonId: 'recall-short-distance',
      title: 'Short-Distance Recall',
      skill: 'recall',
      behaviour: 'An enthusiastic return to the handler over a short distance in a familiar place.',
      visibleAction: 'The dog runs across a lawn straight towards a crouching handler with open arms.',
      breed: 'Australian Shepherd',
      size: 'Medium',
      age: 'Young adult, about 1 year',
      environment: 'Sunny enclosed green backyard lawn',
      handlerPosition: 'Crouched low about five metres away with open, welcoming posture',
      rewardPlacement: 'Treat visible in an open hand ready at the handler’s chest',
      cameraFraming: 'Low action shot at dog eye level, 3:2 landscape',
      lighting: 'Bright outdoor sunlight',
      destinationFilename: 'recall-short-distance.jpg',
    },
    'an Australian Shepherd running enthusiastically across a sunny green backyard lawn towards its owner who is crouching with open arms and a visible treat',
  ),
  spec(
    {
      lessonId: 'recall-around-distractions',
      title: 'Recall Around Distractions',
      skill: 'recall',
      behaviour: 'A reliable recall response around carefully controlled everyday distractions.',
      visibleAction: 'The dog sprints past a park bench on a trailing long line straight to the cheering handler.',
      breed: 'Labrador mixed-breed',
      size: 'Medium',
      age: 'Adult',
      environment: 'Open grassy park field near a wooden park bench',
      handlerPosition: 'Standing with open arms, cheering the dog in',
      rewardPlacement: 'Treat ready in an open hand at waist height for arrival',
      cameraFraming: 'Dynamic wide outdoor action shot, 3:2 landscape',
      lighting: 'Natural outdoor daylight',
      destinationFilename: 'recall-around-distractions.jpg',
    },
    'a happy mixed-breed dog sprinting past a park bench on a loose trailing long line straight towards its owner who stands with open arms encouraging it, a quiet park in the background',
    'no stepped-on line',
  ),

  spec(
    {
      lessonId: 'recall-reward-reset',
      title: 'Reset the Recall Reward',
      skill: 'recall',
      behaviour: 'Your dog begins turning and moving towards you promptly because the recall cue reliably predicts a worthwhile outcome.',
      visibleAction: 'The dog turns away from sniffing and runs towards the handler, who keeps rewards hidden until arrival.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Secure quiet backyard',
      handlerPosition: 'Moving backwards with an open welcoming posture',
      rewardPlacement: 'Several small rewards delivered close to the handler after arrival',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'recall-reward-reset.jpg',
    },
    'a happy medium mixed-breed dog turning away from sniffing and running towards its owner in a secure quiet backyard, the owner moving backwards with open welcoming posture and rewards hidden until the dog arrives',
  ),
  spec(
    {
      lessonId: 'recall-collar-touch-and-release',
      title: 'Collar Touch and Release',
      skill: 'recall',
      behaviour: 'Your dog returns all the way to you and stays relaxed while you briefly touch or hold the collar before rewarding and releasing.',
      visibleAction: 'The dog stands close and relaxed while the handler gently touches the side of the harness before rewarding.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Quiet enclosed garden',
      handlerPosition: 'Crouched sideways beside the dog with one hand lightly touching the harness',
      rewardPlacement: 'Treat delivered from the other hand immediately after the gentle touch',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'recall-collar-touch-and-release.jpg',
    },
    'a relaxed dog standing close beside a crouching owner in a quiet enclosed garden while the owner gently touches the side of the harness and prepares a reward with the other hand',
  ),
  spec(
    {
      lessonId: 'recall-real-world-maintenance',
      title: 'Maintain Real-World Recall',
      skill: 'recall',
      behaviour: 'Your dog maintains a strong recall response across familiar locations without being repeatedly tested beyond their current ability.',
      visibleAction: 'The dog returns on a loose long line across an open field while the handler waits at a safe distance.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Open familiar grassy field',
      handlerPosition: 'Standing with relaxed open posture at the end of a slack long line',
      rewardPlacement: 'High-value reward ready at waist height for arrival',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'recall-real-world-maintenance.jpg',
    },
    'a dog returning enthusiastically across an open familiar grassy field on a loose long line towards an owner waiting with relaxed open posture and a reward ready',
  ),

  // ---- Loose-lead walking ----
  spec(
    {
      lessonId: 'loose-lead-reward-zone',
      title: 'Find the Reward Zone',
      skill: 'loose-lead-walking',
      behaviour: 'The dog learns that staying beside the handler on a loose lead is rewarding.',
      visibleAction: 'The handler delivers a treat beside their hip to a dog walking level with their leg on a J-shaped slack lead.',
      breed: 'Yellow Labrador',
      size: 'Large',
      age: 'Young adult',
      environment: 'Green park walking path',
      handlerPosition: 'Walking forward, delivering a treat down beside the hip',
      rewardPlacement: 'Treat delivered at the handler’s hip, beside the leg the dog should follow',
      cameraFraming: 'Side profile walking shot, 3:2 landscape',
      lighting: 'Outdoor sunlight',
      destinationFilename: 'loose-lead-reward-zone.jpg',
    },
    'a handler walking forward along a green park path handing a treat down beside their hip to a happy Yellow Labrador walking level with their leg, the lead hanging in a loose J-shaped curve',
  ),
  spec(
    {
      lessonId: 'loose-lead-direction-changes',
      title: 'Calm Direction Changes',
      skill: 'loose-lead-walking',
      behaviour: 'The dog notices and follows smooth changes of direction.',
      visibleAction: 'The handler turns smoothly on a paved path and the dog curves naturally with them on a loose leash.',
      breed: 'Brown Labrador/Shepherd mixed-breed',
      size: 'Medium',
      age: 'Adult',
      environment: 'Paved park pathway',
      handlerPosition: 'Mid-turn, walking smoothly',
      rewardPlacement: 'Treat hand relaxed at the hip, ready to mark the turn',
      cameraFraming: 'Wide action shot showing the curved path, 3:2 landscape',
      lighting: 'Natural outdoor daylight',
      destinationFilename: 'loose-lead-direction-changes.jpg',
    },
    'an owner smoothly turning on a paved park path while a medium brown dog curves naturally alongside them on a loose relaxed leash',
    'no harsh jerking',
  ),
  spec(
    {
      lessonId: 'loose-lead-real-world-distractions',
      title: 'Loose Lead in the Real World',
      skill: 'loose-lead-walking',
      behaviour: 'Relaxed loose-lead walking near manageable everyday distractions.',
      visibleAction: 'The dog walks loosely beside the owner along a suburban pavement past parked cars and lawns.',
      breed: 'Staffordshire/Labrador mixed-breed',
      size: 'Medium',
      age: 'Adult',
      environment: 'Suburban pavement with parked cars and green lawns',
      handlerPosition: 'Walking alongside the dog, lead relaxed',
      rewardPlacement: 'Treat hand relaxed at hip level',
      cameraFraming: 'Medium side shot, outdoor daylight, 3:2 landscape',
      lighting: 'Outdoor daylight',
      destinationFilename: 'loose-lead-real-world-distractions.jpg',
    },
    'an adult dog walking calmly and loosely beside its owner along a suburban pavement past parked cars and green front lawns, the lead completely slack',
    'no leash strain',
  ),

  spec(
    {
      lessonId: 'loose-lead-stop-and-reset',
      title: 'Stop and Reset Pulling',
      skill: 'loose-lead-walking',
      behaviour: 'Your dog learns that a loose lead restarts movement while a tight lead leads to a brief calm pause and easier setup.',
      visibleAction: 'The handler pauses calmly as the dog turns back and creates a visible J-shaped slack lead.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Quiet suburban footpath',
      handlerPosition: 'Standing still with relaxed lead hand near the body',
      rewardPlacement: 'Treat ready beside the handler’s leg after slack appears',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'loose-lead-stop-and-reset.jpg',
    },
    'an owner standing calmly on a quiet suburban footpath while a dog turns back and creates a clearly slack J-shaped lead, a reward ready beside the owner’s leg',
  ),
  spec(
    {
      lessonId: 'loose-lead-sniffing-rewards',
      title: 'Use Sniffing as a Reward',
      skill: 'loose-lead-walking',
      behaviour: 'Your dog can walk a short loose-lead section and then access a chosen sniffing spot as the reward.',
      visibleAction: 'The dog walks loosely beside the handler towards a safe grass verge before being released to sniff.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Quiet park path beside a safe grass verge',
      handlerPosition: 'Walking beside the dog with the lead relaxed',
      rewardPlacement: 'Environmental reward is access to the grass after the release cue',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'loose-lead-sniffing-rewards.jpg',
    },
    'a dog walking on a loose leash beside its owner along a quiet park path approaching a safe green grass verge for a planned sniffing reward',
  ),
  spec(
    {
      lessonId: 'loose-lead-longer-routes',
      title: 'Build Longer Relaxed Walks',
      skill: 'loose-lead-walking',
      behaviour: 'Your dog can complete a longer familiar route with repeated relaxed sections, planned sniff breaks, and calm resets.',
      visibleAction: 'The dog and handler walk calmly on a long familiar route with the lead loose and a planned rest point ahead.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Familiar leafy neighbourhood walking route',
      handlerPosition: 'Walking naturally beside the dog',
      rewardPlacement: 'Small reward ready at hip level with a water break nearby',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'loose-lead-longer-routes.jpg',
    },
    'an owner and dog walking calmly together on a familiar leafy neighbourhood route with a fully loose leash and a planned water and sniff break visible ahead',
  ),

  // ---- Focus ----
  spec(
    {
      lessonId: 'focus-check-in',
      title: 'Voluntary Check-Ins',
      skill: 'focus',
      behaviour: 'The dog chooses to look towards the handler without being prompted.',
      visibleAction: 'A dog walking outdoors turns its head up to make happy eye contact with the handler on a loose lead.',
      breed: 'Black Labrador Retriever',
      size: 'Large',
      age: 'Young adult',
      environment: 'Grassy park edge',
      handlerPosition: 'Walking beside the dog',
      rewardPlacement: 'Treat hand relaxed at the hip, ready to reward the look',
      cameraFraming: 'Three-quarter angle showing the dog’s eyes on the handler, 3:2 landscape',
      lighting: 'Soft outdoor light',
      destinationFilename: 'focus-check-in.jpg',
    },
    'a Black Labrador walking outdoors on a loose lead turning its head up to make happy eye contact with its handler at a grassy park edge',
    'no tight collar',
  ),
  spec(
    {
      lessonId: 'focus-hold-attention',
      title: 'Hold Attention Briefly',
      skill: 'focus',
      behaviour: 'Comfortable attention held for a few seconds without frustration.',
      visibleAction: 'A sitting dog holds steady eye contact with the handler who holds a reward near chest level.',
      breed: 'Standard Poodle',
      size: 'Medium to large',
      age: 'Adult',
      environment: 'Warm indoor living room',
      handlerPosition: 'Standing in front of the dog holding a treat near the chest',
      rewardPlacement: 'Treat held at the handler’s chest, drawing the eyes upward',
      cameraFraming: 'Eye-level medium shot, 3:2 landscape',
      lighting: 'Warm indoor daylight',
      destinationFilename: 'focus-hold-attention.jpg',
    },
    'a Standard Poodle sitting indoors and holding steady, relaxed eye contact with its handler who holds a reward near chest level in a warm living room',
    'no forced chin hold',
  ),
  spec(
    {
      lessonId: 'focus-around-distractions',
      title: 'Focus Around Distractions',
      skill: 'focus',
      behaviour: 'The dog reconnects with the handler around manageable everyday activity.',
      visibleAction: 'A sitting dog checks in with its owner while a distant cyclist passes far away on a trail.',
      breed: 'German Shepherd',
      size: 'Large',
      age: 'Adult',
      environment: 'Open park field with a distant trail',
      handlerPosition: 'Standing facing the dog',
      rewardPlacement: 'Treat ready in the hand at waist height',
      cameraFraming: 'Wide medium shot showing the distant distraction, 3:2 landscape',
      lighting: 'Outdoor daylight',
      destinationFilename: 'focus-around-distractions.jpg',
    },
    'a calm German Shepherd sitting and checking in with its owner in an open park while a cyclist rides by far away on a distant trail',
    'no reactive lunging',
  ),

  spec(
    {
      lessonId: 'focus-disengage-and-reset',
      title: 'Disengage and Reset',
      skill: 'focus',
      behaviour: 'Your dog can follow you away from a mild distraction and offer a relaxed check-in after a short reset.',
      visibleAction: 'The dog follows the handler in a wide turn away from a distant distraction and towards a food scatter.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Open quiet park with a distant mild distraction',
      handlerPosition: 'Turning smoothly away with the dog on a loose lead',
      rewardPlacement: 'Small food scatter placed on the ground after moving away',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'focus-disengage-and-reset.jpg',
    },
    'a dog following its owner in a smooth wide turn away from a distant mild distraction in an open park, moving towards a small food scatter on the grass with a loose lead',
  ),
  spec(
    {
      lessonId: 'focus-predictable-patterns',
      title: 'Predictable Focus Patterns',
      skill: 'focus',
      behaviour: 'Your dog can follow a short predictable pattern and remain engaged without continuous verbal prompting.',
      visibleAction: 'The dog walks three calm steps beside the handler and looks up as a reward is delivered at the hip.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Quiet paved training area',
      handlerPosition: 'Walking at a steady rhythm beside the dog',
      rewardPlacement: 'Treat delivered beside the hip after the short step pattern',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'focus-predictable-patterns.jpg',
    },
    'a focused dog completing a short predictable walking pattern beside its owner in a quiet paved area and looking up as a reward is delivered at hip level',
  ),
  spec(
    {
      lessonId: 'focus-real-world-duration',
      title: 'Extend Real-World Focus',
      skill: 'focus',
      behaviour: 'Your dog can alternate between brief handler engagement and appropriate environmental exploration during a real-world session.',
      visibleAction: 'The dog alternates between checking in with the handler and calmly sniffing during a structured outdoor break.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Familiar low-traffic park',
      handlerPosition: 'Standing relaxed while allowing a sniff break',
      rewardPlacement: 'Treat ready for the next voluntary check-in',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'focus-real-world-duration.jpg',
    },
    'a relaxed dog in a familiar low-traffic park alternating between a voluntary check-in with its owner and a calm sniffing break on a loose lead',
  ),

  // ---- Jumping ----
  spec(
    {
      lessonId: 'jumping-four-paws-down',
      title: 'Four Paws Down',
      skill: 'jumping',
      behaviour: 'Calm standing is reinforced before jumping becomes a way to get attention.',
      visibleAction: 'A dog stands with all four paws on the floor while being greeted with low hands and a gentle chest scratch.',
      breed: 'Boxer',
      size: 'Medium to large',
      age: 'Young adult',
      environment: 'Living room entryway',
      handlerPosition: 'Crouched low, greeting the dog at its own height',
      rewardPlacement: 'Calm chest scratch delivered low, at the dog’s chest',
      cameraFraming: 'Low-angle medium shot, 3:2 landscape',
      lighting: 'Indoor daylight',
      destinationFilename: 'jumping-four-paws-down.jpg',
    },
    'a Boxer standing calmly with all four paws firmly on the floor of a living room entryway being greeted with low, gentle hands and a calm chest scratch',
    'no jumping, no paws on chest',
  ),
  spec(
    {
      lessonId: 'jumping-calm-greetings',
      title: 'Calm Greetings',
      skill: 'jumping',
      behaviour: 'A repeatable calm greeting routine with one familiar helper.',
      visibleAction: 'A dog stands calmly beside its owner while a visiting friend extends a gentle hand to pet it.',
      breed: 'Labradoodle',
      size: 'Medium',
      age: 'Adult',
      environment: 'Home hallway entryway',
      handlerPosition: 'Standing beside the dog holding the lead loosely, next to the visitor',
      rewardPlacement: 'Calm gentle petting from the visitor at the dog’s shoulder',
      cameraFraming: 'Medium shot showing dog and visitor, 3:2 landscape',
      lighting: 'Natural indoor light',
      destinationFilename: 'jumping-calm-greetings.jpg',
    },
    'a friendly Labradoodle standing calmly beside its owner in a home hallway while a visiting friend gently extends a calm hand to pet it, the lead loose',
    'no jumping on the visitor',
  ),
  spec(
    {
      lessonId: 'jumping-visitors-and-excitement',
      title: 'Visitors and Excitement',
      skill: 'jumping',
      behaviour: 'Calm greeting skills applied to realistic arrivals.',
      visibleAction: 'A dog sits politely on an entry mat as a guest enters through the front door.',
      breed: 'Mixed-breed',
      size: 'Medium',
      age: 'Adult',
      environment: 'Spacious entryway with a mat by the front door',
      handlerPosition: 'Standing near the door welcoming the visitor',
      rewardPlacement: 'Treat ready to reward the sit on the mat',
      cameraFraming: 'Wide medium shot, 3:2 landscape',
      lighting: 'Bright indoor light',
      destinationFilename: 'jumping-visitors-and-excitement.jpg',
    },
    'a medium mixed-breed dog sitting politely on an entry mat inside a hallway as a guest steps in through the open front door, the owner nearby',
    'no lunging, no jumping',
  ),

  spec(
    {
      lessonId: 'jumping-station-on-a-mat',
      title: 'Station on a Mat',
      skill: 'jumping',
      behaviour: 'Your dog chooses the mat and keeps four paws down while one person moves nearby.',
      visibleAction: 'The dog stands with all four paws on a mat while a person moves gently near the doorway.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Bright home entryway',
      handlerPosition: 'Standing beside the mat and calmly rewarding low',
      rewardPlacement: 'Treat delivered low between the dog’s front paws on the mat',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'jumping-station-on-a-mat.jpg',
    },
    'a dog standing with all four paws on a non-slip mat in a bright home entryway while its owner rewards low and another person moves gently near the doorway',
  ),
  spec(
    {
      lessonId: 'jumping-greetings-with-movement',
      title: 'Greetings with Movement',
      skill: 'jumping',
      behaviour: 'Your dog keeps four paws down while a familiar helper adds small realistic greeting movements.',
      visibleAction: 'The dog keeps four paws down while a familiar helper takes a slow step forward.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Spacious living room near an entry',
      handlerPosition: 'Holding a loose lead several metres from the helper',
      rewardPlacement: 'Treat delivered low beside the dog after the helper moves',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'jumping-greetings-with-movement.jpg',
    },
    'a dog keeping all four paws on the floor in a spacious living room while a familiar helper takes one slow step forward and the owner rewards calmly on a loose lead',
  ),
  spec(
    {
      lessonId: 'jumping-maintenance-in-public',
      title: 'Maintain Calm Greetings in Public',
      skill: 'jumping',
      behaviour: 'Your dog can complete brief chosen greetings in two familiar public settings without repeated jumping.',
      visibleAction: 'The dog completes a brief calm greeting with a helper in a quiet public space and turns back to the handler.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Quiet outdoor café edge or open plaza',
      handlerPosition: 'Standing beside the dog with space to move away',
      rewardPlacement: 'Treat delivered after the dog turns back from the short greeting',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'jumping-maintenance-in-public.jpg',
    },
    'a dog completing a brief calm greeting with a familiar helper in a quiet open public space and turning back towards its owner for a reward, all four paws on the ground',
  ),

  // ---- Barking ----
  spec(
    {
      lessonId: 'barking-identify-triggers',
      title: 'Identify Barking Triggers',
      skill: 'barking',
      behaviour: 'Observing when barking happens so the handler can respond to its cause.',
      visibleAction: 'A dog sits calmly on a rug looking out of a large window while the owner observes quietly.',
      breed: 'Friendly mixed-breed',
      size: 'Medium',
      age: 'Adult',
      environment: 'Modern living room with a floor-to-ceiling window and daylight',
      handlerPosition: 'Seated in an armchair in the background, watching quietly',
      rewardPlacement: 'No active reward; calm observation only',
      cameraFraming: '35mm medium shot, shallow depth of field, 3:2 landscape',
      lighting: 'Window daylight',
      destinationFilename: 'barking-identify-triggers.jpg',
    },
    'a friendly mixed-breed dog sitting calmly on a rug and looking out of a modern floor-to-ceiling window in a cosy living room while the owner observes quietly from an armchair in the background',
  ),
  spec(
    {
      lessonId: 'barking-quiet-reinforcement',
      title: 'Reinforce Quiet Moments',
      skill: 'barking',
      behaviour: 'Rewarding brief quiet pauses around a manageable trigger.',
      visibleAction: 'A dog lies quietly on its bed looking up as the owner offers a treat at nose level.',
      breed: 'Border Collie',
      size: 'Medium',
      age: 'Adult',
      environment: 'Bright indoor living room',
      handlerPosition: 'Kneeling beside the dog, extending a treat',
      rewardPlacement: 'Treat delivered calmly at the dog’s nose level on its bed',
      cameraFraming: 'Eye-level close medium shot, 3:2 landscape',
      lighting: 'Bright indoor natural light',
      destinationFilename: 'barking-quiet-reinforcement.jpg',
    },
    'a Border Collie lying quietly on a dog bed and looking up towards its owner who kneels beside it calmly offering a treat at nose level in a bright living room',
  ),
  spec(
    {
      lessonId: 'barking-real-world-management',
      title: 'Real-World Barking Management',
      skill: 'barking',
      behaviour: 'Combining prevention, calm alternatives and reinforcement in a daily routine.',
      visibleAction: 'A dog on a slack lead turns calmly towards the owner while walking past a garden fence.',
      breed: 'Medium mixed-breed',
      size: 'Medium',
      age: 'Adult',
      environment: 'Suburban pavement beside a green garden fence',
      handlerPosition: 'Walking beside the dog holding a loose lead',
      rewardPlacement: 'Treat ready at the hip to reward the calm turn',
      cameraFraming: 'Outdoor side-angle medium shot, 3:2 landscape',
      lighting: 'Outdoor daylight',
      destinationFilename: 'barking-real-world-management.jpg',
    },
    'an owner walking a medium mixed-breed dog on a slack lead past a suburban garden fence, the dog turning calmly towards the owner with relaxed ears',
  ),

  spec(
    {
      lessonId: 'barking-meet-needs-first',
      title: 'Meet Needs Before Training',
      skill: 'barking',
      behaviour: 'You can identify and address one likely unmet need before attempting a barking training exercise.',
      visibleAction: 'The owner calmly prepares water, a toilet break, and a resting space while the dog waits quietly.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Calm home living area near a back door',
      handlerPosition: 'Standing near the dog while checking the daily routine',
      rewardPlacement: 'No active cue reward; needs and calm enrichment are prepared',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'barking-meet-needs-first.jpg',
    },
    'an owner calmly checking a dog’s water, preparing access to a backyard toilet break, and arranging a quiet resting space in a peaceful home while the dog waits relaxed',
  ),
  spec(
    {
      lessonId: 'barking-doorbell-routine',
      title: 'Build a Doorbell Routine',
      skill: 'barking',
      behaviour: 'Your dog can hear a low-intensity door sound and move with you to a prepared station before barking escalates.',
      visibleAction: 'The dog moves to a mat behind a gate after a low-volume door sound while the handler rewards calmly.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Home hallway with a secure baby gate and mat',
      handlerPosition: 'Standing beside the mat away from the front door',
      rewardPlacement: 'Several small rewards delivered on the mat',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'barking-doorbell-routine.jpg',
    },
    'a dog moving calmly to a mat behind a secure baby gate in a home hallway after a door sound while the owner rewards on the mat away from the front door',
  ),
  spec(
    {
      lessonId: 'barking-recovery-and-maintenance',
      title: 'Barking Recovery and Maintenance',
      skill: 'barking',
      behaviour: 'Your dog recovers more quickly from predictable barking triggers through a consistent prevention and calm-response plan.',
      visibleAction: 'The dog settles on a mat after noticing a window trigger while a curtain is partly closed.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Living room with a window and visual barrier',
      handlerPosition: 'Kneeling near the mat with relaxed posture',
      rewardPlacement: 'Calm food scatter or chew activity on the mat',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'barking-recovery-and-maintenance.jpg',
    },
    'a dog settling calmly on a mat after noticing an outdoor window trigger, with the curtain partly closed and the owner providing a quiet food activity nearby',
  ),

  // ---- Chewing ----
  spec(
    {
      lessonId: 'chewing-appropriate-items',
      title: 'Choose Appropriate Chews',
      skill: 'chewing',
      behaviour: 'Making safe, suitable chewing options easy and rewarding to choose.',
      visibleAction: 'A puppy rests on the floor happily chewing a durable rubber dog toy.',
      breed: 'Golden Retriever',
      size: 'Small (puppy)',
      age: 'Puppy, about 3–4 months',
      environment: 'Clean modern hardwood living-room floor',
      handlerPosition: 'Out of frame, supervising nearby',
      rewardPlacement: 'The appropriate chew toy itself is the reward',
      cameraFraming: 'Low-angle close-up on the puppy and chew toy, 3:2 landscape',
      lighting: 'Bright indoor daylight',
      destinationFilename: 'chewing-appropriate-items.jpg',
    },
    'a young Golden Retriever puppy resting on a clean wooden floor happily chewing a durable rubber dog chew toy in a bright living room',
    'no shoes or forbidden household items near the dog',
  ),
  spec(
    {
      lessonId: 'chewing-redirection-routine',
      title: 'A Calm Redirection Routine',
      skill: 'chewing',
      behaviour: 'Guiding the dog from an unsuitable object to a safe alternative without conflict.',
      visibleAction: 'A young dog leaves a shoe on the rug to accept a safe chew toy offered by the owner.',
      breed: 'Yellow Labrador',
      size: 'Medium',
      age: 'Young, about 6–9 months',
      environment: 'Cosy living-room rug',
      handlerPosition: 'Kneeling low, calmly offering the chew toy',
      rewardPlacement: 'Safe chew toy offered at the dog’s mouth level',
      cameraFraming: 'Medium close-up showing the hand, chew toy and dog, 3:2 landscape',
      lighting: 'Warm indoor daylight',
      destinationFilename: 'chewing-redirection-routine.jpg',
    },
    'an owner kneeling and calmly offering a safe chew toy to a young Yellow Labrador that is leaving a shoe on the carpet to take the chew toy, a cosy living room',
    'no conflict, no scolding',
  ),
  spec(
    {
      lessonId: 'chewing-independence-and-prevention',
      title: 'Independence and Prevention',
      skill: 'chewing',
      behaviour: 'A practical routine that meets chewing needs while preventing unsafe choices.',
      visibleAction: 'A dog rests contentedly on a mat surrounded by an assortment of safe chews.',
      breed: 'Beagle (tricolour)',
      size: 'Small to medium',
      age: 'Adult',
      environment: 'Clean modern home living room',
      handlerPosition: 'Out of frame',
      rewardPlacement: 'Safe chews arranged within easy reach on the mat',
      cameraFraming: 'Wide medium shot, 3:2 landscape',
      lighting: 'Bright natural lighting',
      destinationFilename: 'chewing-independence-and-prevention.jpg',
    },
    'an adult tricolour Beagle relaxing comfortably on a plush dog mat with an assortment of safe chew toys and bones arranged around it in a clean modern living room',
  ),

  spec(
    {
      lessonId: 'chewing-puppy-teething-plan',
      title: 'Puppy Teething Plan',
      skill: 'chewing',
      behaviour: 'Your puppy or young dog has appropriate chewing choices available during the times chewing is most likely.',
      visibleAction: 'A puppy chooses a safe rubber chew in a puppy-proofed pen with several hazards removed.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Bright puppy-safe home pen',
      handlerPosition: 'Seated nearby supervising calmly',
      rewardPlacement: 'The safe chew itself is available on the mat',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'chewing-puppy-teething-plan.jpg',
    },
    'a young puppy in a bright puppy-proofed indoor pen choosing a safe rubber chew on a mat while its owner sits nearby supervising calmly',
  ),
  spec(
    {
      lessonId: 'chewing-leave-and-trade',
      title: 'Leave and Trade Safely',
      skill: 'chewing',
      behaviour: 'Your dog releases a low-value practice object and moves to a safe alternative when offered a calm trade.',
      visibleAction: 'The dog releases a low-value practice object and moves to a safe chew offered by the handler.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Quiet living room with clear floor space',
      handlerPosition: 'Kneeling sideways and placing a reward away from the object',
      rewardPlacement: 'High-value reward placed away, followed by a safe chew',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'chewing-leave-and-trade.jpg',
    },
    'a relaxed dog in a quiet living room releasing a low-value practice object and moving towards a safe chew offered by a kneeling owner, with no chasing or conflict',
  ),
  spec(
    {
      lessonId: 'chewing-rotation-and-settle',
      title: 'Chew Rotation and Settle',
      skill: 'chewing',
      behaviour: 'Your dog can choose an appropriate chew and settle in a prepared area during a normal household activity.',
      visibleAction: 'The dog lies on a mat using a safe chew while normal household activity continues nearby.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Kitchen-living area during a calm household routine',
      handlerPosition: 'Moving nearby while supervising',
      rewardPlacement: 'Approved chew provided on the dog’s mat',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'chewing-rotation-and-settle.jpg',
    },
    'a dog lying calmly on a comfortable mat using an approved chew while its owner prepares food nearby in a tidy kitchen-living area',
  ),

  // ---- Reactivity ----
  spec(
    {
      lessonId: 'reactivity-safe-distance',
      title: 'Find a Safe Working Distance',
      skill: 'reactivity',
      behaviour: 'Observing triggers from far enough away that the dog can stay safe, eat and recover.',
      visibleAction: 'A dog sits calmly beside the handler on a hill while another dog walks far away below.',
      breed: 'German Shepherd',
      size: 'Large',
      age: 'Adult',
      environment: 'Open grassy hill overlooking a distant park trail',
      handlerPosition: 'Standing beside the dog, giving a treat',
      rewardPlacement: 'Treat delivered calmly beside the handler at the dog’s head',
      cameraFraming: 'Wide landscape shot showing the distance, 3:2 landscape',
      lighting: 'Soft outdoor light',
      destinationFilename: 'reactivity-safe-distance.jpg',
    },
    'a handler and a calm German Shepherd standing on a grassy hill giving the dog a treat, while another dog walks far away on a distant park trail below',
    'no barking, no reaction',
  ),
  spec(
    {
      lessonId: 'reactivity-look-and-disengage',
      title: 'Look and Disengage',
      skill: 'reactivity',
      behaviour: 'Reinforcing the choice to look away from a trigger while below reaction threshold.',
      visibleAction: 'A dog turns its head back from a distant trigger towards the handler for a treat on a slack long line.',
      breed: 'Collie',
      size: 'Medium',
      age: 'Adult',
      environment: 'Park edge near trees',
      handlerPosition: 'Standing about a metre from the dog, rewarding the look-away',
      rewardPlacement: 'Treat delivered at the dog’s head as it turns back',
      cameraFraming: 'Medium shot showing the head turn, 3:2 landscape',
      lighting: 'Outdoor daylight',
      destinationFilename: 'reactivity-look-and-disengage.jpg',
    },
    'a calm Collie on a slack long line turning its head back from a distant trigger towards its handler to take a treat, at a quiet park edge near trees',
    'no lunging',
  ),
  spec(
    {
      lessonId: 'reactivity-controlled-exposure',
      title: 'Carefully Controlled Exposure',
      skill: 'reactivity',
      behaviour: 'Practising predictable, below-threshold trigger sightings with a safety-first plan.',
      visibleAction: 'A dog walks calmly with the handler behind a natural park hedge, focused on the handler.',
      breed: 'Shepherd mixed-breed',
      size: 'Medium',
      age: 'Adult',
      environment: 'Park walkway alongside a green hedge line',
      handlerPosition: 'Walking beside the dog',
      rewardPlacement: 'Treat hand relaxed at hip, ready to reward focus',
      cameraFraming: 'Medium wide landscape shot, 3:2 landscape',
      lighting: 'Natural light',
      destinationFilename: 'reactivity-controlled-exposure.jpg',
    },
    'a handler walking a calm dog behind a natural green park hedge that acts as a visual barrier, the dog relaxed and focused on the handler',
    'no barrier frustration',
  ),

  spec(
    {
      lessonId: 'reactivity-emergency-u-turn',
      title: 'Practise an Emergency U-Turn',
      skill: 'reactivity',
      behaviour: 'Your dog can follow a familiar turn cue away from a mild distraction before a reaction develops.',
      visibleAction: 'The dog follows the handler in a wide U-turn away from a distant dog with the lead fully loose.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Wide park path with a distant dog far behind',
      handlerPosition: 'Moving smoothly away beside the dog',
      rewardPlacement: 'High-value treat delivered after several steps away',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'reactivity-emergency-u-turn.jpg',
    },
    'a handler and dog making a smooth wide emergency U-turn on a spacious park path away from a very distant dog, the lead fully loose and a reward ready after moving away',
  ),
  spec(
    {
      lessonId: 'reactivity-recovery-after-trigger',
      title: 'Recover After a Trigger',
      skill: 'reactivity',
      behaviour: 'Your dog can move to safety and return to eating, sniffing, or responding before the session ends.',
      visibleAction: 'The dog sniffs calmly behind a visual barrier after moving away from a distant trigger.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Quiet area behind a hedge or parked vehicle barrier',
      handlerPosition: 'Standing quietly with slack lead and giving space',
      rewardPlacement: 'Small food scatter on the ground once the dog can engage',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'reactivity-recovery-after-trigger.jpg',
    },
    'a dog recovering calmly behind a natural visual barrier after moving away from a distant trigger, sniffing a small food scatter while the owner stands quietly with a slack lead',
  ),
  spec(
    {
      lessonId: 'reactivity-generalisation-and-maintenance',
      title: 'Generalise Reactivity Skills Safely',
      skill: 'reactivity',
      behaviour: 'Your dog can use established coping skills around one known trigger type in two carefully controlled locations.',
      visibleAction: 'The dog observes a distant known trigger from a spacious second location and then turns back to the handler.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Large open field with extensive distance and an exit path',
      handlerPosition: 'Standing sideways beside the dog with a loose lead',
      rewardPlacement: 'Reward delivered after voluntary disengagement',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'reactivity-generalisation-and-maintenance.jpg',
    },
    'a dog in a large open field calmly observing a very distant known trigger and then voluntarily turning back to its owner for a reward, with extensive space and a loose lead',
  ),

  // ---- House-training ----
  spec(
    {
      lessonId: 'house-training-routine',
      title: 'Build a Toileting Routine',
      skill: 'house-training',
      behaviour: 'Using timing, supervision and immediate rewards to make the right location easy to choose.',
      visibleAction: 'A puppy sniffs the grass in a backyard near an open patio door in the morning.',
      breed: 'Mixed-breed puppy',
      size: 'Small',
      age: 'Puppy, about 3 months',
      environment: 'Suburban backyard grass near an open patio door',
      handlerPosition: 'Standing nearby encouragingly',
      rewardPlacement: 'Treat ready to reward immediately after the puppy finishes',
      cameraFraming: 'Landscape outdoor shot, 3:2 landscape',
      lighting: 'Bright morning sun',
      destinationFilename: 'house-training-routine.jpg',
    },
    'a young puppy sniffing the lush green grass in a suburban backyard near an open patio door under bright morning sunlight, the owner standing nearby',
  ),
  spec(
    {
      lessonId: 'house-training-signal-and-reward',
      title: 'Signal and Reward',
      skill: 'house-training',
      behaviour: 'Pairing the routine with a clear way for the dog to request access.',
      visibleAction: 'The owner bends down to give a treat and praise to a small dog in the garden.',
      breed: 'Terrier mixed-breed',
      size: 'Small',
      age: 'Young adult',
      environment: 'Sunny residential garden',
      handlerPosition: 'Bending low, delivering a treat',
      rewardPlacement: 'Treat delivered low at the dog’s mouth with praise',
      cameraFraming: 'Close medium shot, 3:2 landscape',
      lighting: 'Natural sunlight',
      destinationFilename: 'house-training-signal-and-reward.jpg',
    },
    'an owner bending down to give a treat and warm praise to a small happy terrier mix in a sunny residential garden',
  ),
  spec(
    {
      lessonId: 'house-training-reliability',
      title: 'Build House-Training Reliability',
      skill: 'house-training',
      behaviour: 'Gradually extending freedom while protecting successful habits.',
      visibleAction: 'An adult dog sits patiently by a glass back door, looking out into the garden.',
      breed: 'Golden Retriever',
      size: 'Large',
      age: 'Adult',
      environment: 'Modern sunroom by a glass back door',
      handlerPosition: 'Approaching to open the door',
      rewardPlacement: 'Praise and access to the garden as the reward',
      cameraFraming: 'Medium shot showing dog and door, 3:2 landscape',
      lighting: 'Bright natural light',
      destinationFilename: 'house-training-reliability.jpg',
    },
    'an adult Golden Retriever sitting patiently by a glass back door and looking out into the garden with a gently wagging tail in a bright modern sunroom',
  ),

  spec(
    {
      lessonId: 'house-training-accident-reset',
      title: 'Reset After an Accident',
      skill: 'house-training',
      behaviour: 'You can respond calmly to an accident and change the routine to make the next correct toileting opportunity easier.',
      visibleAction: 'The owner calmly cleans an indoor accident area while the dog rests separately without punishment.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Clean home hallway beside an open back-door route',
      handlerPosition: 'Cleaning the floor calmly while the dog is safely elsewhere',
      rewardPlacement: 'Rewards prepared for the next correct outdoor toilet trip',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'house-training-accident-reset.jpg',
    },
    'an owner calmly using pet-safe cleaner on a small indoor accident area while the dog waits relaxed in a separate safe space near an open route to the backyard, no scolding',
  ),
  spec(
    {
      lessonId: 'house-training-clear-outdoor-signal',
      title: 'Build a Clear Toilet Signal',
      skill: 'house-training',
      behaviour: 'Your dog uses one chosen behaviour near the exit before being taken promptly to the toileting area.',
      visibleAction: 'The dog stands on a small mat by the exit door while the owner reaches to open it promptly.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Home back-door area leading to a secure yard',
      handlerPosition: 'Standing beside the door responding to the dog’s signal',
      rewardPlacement: 'Reward reserved for correct toileting outside',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'house-training-clear-outdoor-signal.jpg',
    },
    'a dog standing calmly on a small signal mat beside the back door while its owner responds promptly and opens the route to a secure backyard toilet area',
  ),
  spec(
    {
      lessonId: 'house-training-new-places-and-weather',
      title: 'Toileting in New Places and Weather',
      skill: 'house-training',
      behaviour: 'Your dog can toilet promptly in a second safe location or on a different suitable surface with a familiar routine.',
      visibleAction: 'The dog toilets on a safe unfamiliar grass area during light rain while the owner waits quietly under shelter.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Quiet sheltered outdoor grass area in mild rain',
      handlerPosition: 'Standing nearby with a loose lead and weather protection',
      rewardPlacement: 'Reward delivered immediately after toileting',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'house-training-new-places-and-weather.jpg',
    },
    'a dog using a quiet unfamiliar grass toilet area during gentle light rain while the owner waits calmly under nearby shelter with a loose lead and a reward ready',
  ),

  // ---- Confidence ----
  spec(
    {
      lessonId: 'confidence-choice-and-exploration',
      title: 'Choice and Exploration',
      skill: 'confidence',
      behaviour: 'Building confidence by rewarding voluntary investigation and respecting retreat.',
      visibleAction: 'A curious dog sniffs an open cardboard box while the owner stands back giving space.',
      breed: 'Scruffy terrier mixed-breed (rescue)',
      size: 'Small to medium',
      age: 'Adult',
      environment: 'Bright sunlit living room',
      handlerPosition: 'Standing about two metres back, observing encouragingly',
      rewardPlacement: 'Treat ready to reward the voluntary investigation',
      cameraFraming: 'Wide shot showing full-body dog and open box, 3:2 landscape',
      lighting: 'Natural morning light',
      destinationFilename: 'confidence-choice-and-exploration.jpg',
    },
    'a curious scruffy rescue terrier-mix voluntarily sniffing an open cardboard box in a sunlit living room while the owner stands back calmly giving the dog space and time',
    'no forcing, no pulling',
  ),
  spec(
    {
      lessonId: 'confidence-new-surfaces-and-sounds',
      title: 'New Surfaces and Sounds',
      skill: 'confidence',
      behaviour: 'Introducing gentle sensory changes through choice and gradual exposure.',
      visibleAction: 'A dog steps one paw onto a textured rubber balance pad while the owner smiles beside it.',
      breed: 'Australian Shepherd (blue merle)',
      size: 'Medium',
      age: 'Young adult',
      environment: 'Indoor dog-training facility with soft matting',
      handlerPosition: 'Crouching beside the dog holding a treat',
      rewardPlacement: 'Treat delivered as the dog investigates the pad',
      cameraFraming: 'Medium shot focusing on the paws and balance pad, 3:2 landscape',
      lighting: 'Bright indoor daylight',
      destinationFilename: 'confidence-new-surfaces-and-sounds.jpg',
    },
    'a blue-merle Australian Shepherd stepping one paw onto a textured rubber balance pad in an indoor training room while its owner crouches beside it smiling with a treat',
    'no force, no pushing',
  ),
  spec(
    {
      lessonId: 'confidence-new-environments',
      title: 'Explore New Environments',
      skill: 'confidence',
      behaviour: 'Transferring choice-based confidence skills to a quiet unfamiliar location.',
      visibleAction: 'A dog explores a quiet park path on a long line, sniffing the grass happily.',
      breed: 'Cocker Spaniel',
      size: 'Small to medium',
      age: 'Adult',
      environment: 'Quiet green suburban park pathway',
      handlerPosition: 'Following about four metres behind, holding a long line loosely',
      rewardPlacement: 'Praise and freedom to explore as the reward',
      cameraFraming: 'Outdoor landscape shot, 3:2 landscape',
      lighting: 'Natural daylight',
      destinationFilename: 'confidence-new-environments.jpg',
    },
    'a Cocker Spaniel exploring a quiet green park pathway on a loose long line, sniffing the grass happily while its owner follows a few metres behind',
    'no tight leash, no crowd',
  ),

  spec(
    {
      lessonId: 'confidence-consent-based-handling',
      title: 'Consent-Based Handling',
      skill: 'confidence',
      behaviour: 'Your dog remains relaxed and chooses to continue during one brief low-intensity handling exercise.',
      visibleAction: 'The dog voluntarily remains on a mat while the handler gives a brief gentle shoulder touch and pauses.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Quiet familiar room with a non-slip mat',
      handlerPosition: 'Kneeling sideways with open relaxed posture',
      rewardPlacement: 'Treat delivered after the one-second touch',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'confidence-consent-based-handling.jpg',
    },
    'a relaxed dog voluntarily standing on a non-slip mat in a quiet familiar room while a kneeling owner gives a brief gentle shoulder touch and then pauses with a reward ready',
  ),
  spec(
    {
      lessonId: 'confidence-recovery-after-surprise',
      title: 'Recover After a Surprise',
      skill: 'confidence',
      behaviour: 'Your dog can create distance, observe, and return to a chosen calm activity after a mild surprise.',
      visibleAction: 'The dog observes a mild unfamiliar object from a chosen distance and then returns to sniffing.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Spacious quiet room with a harmless novelty far away',
      handlerPosition: 'Seated neutrally near the dog’s retreat area',
      rewardPlacement: 'Reward offered only after voluntary relaxed engagement',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'confidence-recovery-after-surprise.jpg',
    },
    'a dog calmly observing a harmless unfamiliar household object from a chosen distance in a spacious quiet room and then returning to relaxed sniffing near its seated owner',
  ),
  spec(
    {
      lessonId: 'confidence-generalise-brave-choices',
      title: 'Generalise Brave Choices',
      skill: 'confidence',
      behaviour: 'Your dog can explore or calmly observe one new feature in two different low-pressure environments by choice.',
      visibleAction: 'The dog calmly explores one new feature in a quiet outdoor setting with a clear retreat route.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Quiet garden centre outdoor aisle or calm park feature',
      handlerPosition: 'Standing sideways and allowing the dog to choose distance',
      rewardPlacement: 'Treat delivered after voluntary observation or approach',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'confidence-generalise-brave-choices.jpg',
    },
    'a dog voluntarily and calmly exploring one new low-pressure feature in a quiet outdoor setting while its owner stands sideways with a clear retreat path and rewards choice',
  ),

  // ---- Impulse control ----
  spec(
    {
      lessonId: 'impulse-control-wait-for-reward',
      title: 'Wait for a Reward',
      skill: 'impulse-control',
      behaviour: 'A very brief pause before access to something the dog wants.',
      visibleAction: 'A dog sits calmly facing an open palm holding a treat, pausing before taking it.',
      breed: 'Hungarian Vizsla',
      size: 'Medium',
      age: 'Young adult',
      environment: 'Bright indoor kitchen or dining room',
      handlerPosition: 'Open hand held about 30cm in front of the sitting dog',
      rewardPlacement: 'Treat resting on a flat open palm, delivered after the pause',
      cameraFraming: 'Close-up on the dog’s face and the open hand, 3:2 landscape',
      lighting: 'Indoor daylight',
      destinationFilename: 'impulse-control-wait-for-reward.jpg',
    },
    'a smooth-coated Hungarian Vizsla sitting calmly and patiently facing an open human palm holding a treat, pausing before taking it, in a bright kitchen',
    'no snatching',
  ),
  spec(
    {
      lessonId: 'impulse-control-doorways',
      title: 'Pause at Doorways',
      skill: 'impulse-control',
      behaviour: 'A calm, released pause at a low-risk doorway.',
      visibleAction: 'A dog sits quietly in front of an open front door, looking at the handler for the release cue.',
      breed: 'Border Collie',
      size: 'Medium',
      age: 'Adult',
      environment: 'Home entryway with an open front door',
      handlerPosition: 'Standing at the doorway looking at the dog',
      rewardPlacement: 'Release and access through the door as the reward',
      cameraFraming: 'Eye-level wide medium shot, 3:2 landscape',
      lighting: 'Natural daylight',
      destinationFilename: 'impulse-control-doorways.jpg',
    },
    'a Border Collie sitting quietly in front of an open front door in a home entryway, looking up at its handler and waiting calmly for the release cue',
    'no physical blocking',
  ),
  spec(
    {
      lessonId: 'impulse-control-real-world-distractions',
      title: 'Impulse Control in Daily Life',
      skill: 'impulse-control',
      behaviour: 'Short pauses before safe access to selected everyday rewards.',
      visibleAction: 'A dog holds a relaxed down-stay on a patio while the owner sets down a food bowl nearby.',
      breed: 'Golden Retriever',
      size: 'Large',
      age: 'Adult',
      environment: 'Outdoor home patio',
      handlerPosition: 'Placing a food bowl on the ground about 1.5 metres away',
      rewardPlacement: 'Release to the food bowl as the reward after the calm wait',
      cameraFraming: 'Medium wide shot, 3:2 landscape',
      lighting: 'Natural outdoor daylight',
      destinationFilename: 'impulse-control-real-world-distractions.jpg',
    },
    'a Golden Retriever holding a calm, relaxed down-stay on a home patio while its owner sets a food bowl on the ground a short distance away',
    'no pushing, no holding down',
  ),
  spec(
    {
      lessonId: 'impulse-control-leave-it',
      title: 'Leave It by Choice',
      skill: 'impulse-control',
      behaviour: 'Your dog voluntarily moves attention away from a covered low-value item and turns towards you for reinforcement.',
      visibleAction: 'The dog looks away from a covered low-value item and turns towards the handler for a reward.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Quiet home training room',
      handlerPosition: 'Kneeling beside a covered container',
      rewardPlacement: 'Higher-value reward delivered from the opposite hand away from the item',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'impulse-control-leave-it.jpg',
    },
    'a dog in a quiet room looking away from a covered low-value food item and turning towards its kneeling owner for a higher-value reward delivered away from the container',
  ),
  spec(
    {
      lessonId: 'impulse-control-settle-on-mat',
      title: 'Settle on a Mat',
      skill: 'impulse-control',
      behaviour: 'Your dog can remain relaxed on a mat for a short period while the handler performs a simple nearby activity.',
      visibleAction: 'The dog lies relaxed on a mat while the handler sits in a nearby chair doing a simple activity.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Calm home living room',
      handlerPosition: 'Seated nearby with relaxed posture',
      rewardPlacement: 'Small reward delivered slowly between the dog’s front paws',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'impulse-control-settle-on-mat.jpg',
    },
    'a dog lying relaxed on a comfortable mat in a calm living room while its owner sits nearby and slowly delivers a small reward between the front paws',
  ),
  spec(
    {
      lessonId: 'impulse-control-maintenance-and-release',
      title: 'Maintain Waiting with Release Cues',
      skill: 'impulse-control',
      behaviour: 'Your dog can pause briefly in several everyday situations and move only after a consistent release cue.',
      visibleAction: 'The dog waits briefly at an open doorway and moves only after the handler gives a clear release cue.',
      breed: 'Friendly mixed-breed dog',
      size: 'Medium',
      age: 'Adult',
      environment: 'Secure home doorway opening to a fenced yard',
      handlerPosition: 'Standing beside the dog with one hand giving a release signal',
      rewardPlacement: 'Reward available after the dog responds to the release cue',
      cameraFraming: 'Eye-level documentary-style medium landscape shot, 3:2 composition',
      lighting: 'Soft natural daylight',
      destinationFilename: 'impulse-control-maintenance-and-release.jpg',
    },
    'a dog waiting calmly for a few seconds at an open home doorway leading to a fenced yard and then beginning to move after its owner gives a clear release signal',
  ),

]);

export const lessonImageGenerationSpecById: Readonly<Record<string, LessonImageSpec>> =
  Object.freeze(
    Object.fromEntries(lessonImageGenerationSpecs.map((entry) => [entry.lessonId, entry])),
  );
