import { StatusBar as RNStatusBar, StyleSheet } from 'react-native';

import { colors } from './colors';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background, paddingTop: RNStatusBar.currentHeight ?? 0 },
  app: { flex: 1 },
  content: { padding: 18, paddingBottom: 110, gap: 16 },
  hero: { borderRadius: 28, backgroundColor: colors.forest, padding: 22, gap: 13 },
  eyebrow: { color: colors.gold, fontSize: 10, letterSpacing: 1.7, fontWeight: '900' },
  eyebrowDark: { color: colors.gold, fontSize: 10, letterSpacing: 1.7, fontWeight: '900' },
  heroTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  heroDogName: { color: colors.white, fontSize: 18, fontWeight: '800', marginTop: 4 },
  ownerBadge: { borderRadius: 999, borderWidth: 1, borderColor: 'rgba(216,180,106,0.45)', backgroundColor: 'rgba(216,180,106,0.14)', paddingHorizontal: 11, paddingVertical: 7 },
  ownerBadgeText: { color: colors.gold, fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  heroTitle: { color: colors.white, fontSize: 29, lineHeight: 35, letterSpacing: -0.6, fontWeight: '900' },
  heroBody: { color: 'rgba(255,255,255,0.73)', fontSize: 15, lineHeight: 22 },
  metricRow: { flexDirection: 'row', gap: 9 },
  metric: { flex: 1, borderRadius: 17, padding: 12, backgroundColor: 'rgba(255,255,255,0.09)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)' },
  metricValue: { color: colors.white, fontSize: 23, fontWeight: '900' },
  metricLabel: { color: 'rgba(255,255,255,0.65)', fontSize: 11, fontWeight: '700', marginTop: 3 },
  pageTitle: { color: colors.text, fontSize: 32, lineHeight: 38, letterSpacing: -0.7, fontWeight: '900' },
  card: { backgroundColor: colors.card, borderRadius: 22, padding: 18, gap: 11, borderWidth: 1, borderColor: colors.line },
  sectionTitle: { color: colors.text, fontSize: 21, fontWeight: '900' },
  body: { color: colors.text, fontSize: 16, lineHeight: 23 },
  label: { color: colors.text, fontSize: 14, fontWeight: '800' },
  input: { borderWidth: 1, borderColor: colors.line, borderRadius: 15, backgroundColor: '#FAF8F3', paddingHorizontal: 14, paddingVertical: 14, fontSize: 16, color: colors.text },
  lessonTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  coursePill: { borderRadius: 999, backgroundColor: colors.mint, paddingHorizontal: 10, paddingVertical: 6 },
  coursePillText: { color: colors.green, fontSize: 10, fontWeight: '900', letterSpacing: 0.8 },
  duration: { color: colors.muted, fontSize: 11, fontWeight: '900', letterSpacing: 0.7 },
  lessonTitle: { color: colors.text, fontSize: 22, fontWeight: '900' },
  primaryButton: { minHeight: 52, borderRadius: 15, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
  primaryButtonText: { color: colors.white, fontSize: 16, fontWeight: '900' },
  pressed: { opacity: 0.82 },
  completedBadge: { minHeight: 48, borderRadius: 15, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center' },
  completedBadgeText: { color: colors.green, fontSize: 15, fontWeight: '900' },
  progressHero: { borderRadius: 28, backgroundColor: colors.forest, padding: 22, gap: 11 },
  progressValue: { color: colors.white, fontSize: 58, fontWeight: '900', letterSpacing: -1.5 },
  progressLabel: { color: 'rgba(255,255,255,0.73)', fontSize: 15, fontWeight: '700' },
  progressTrack: { height: 10, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.12)', overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 999, backgroundColor: colors.gold },
  progressRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: colors.line },
  completeText: { color: colors.green, fontWeight: '900' },
  notStartedText: { color: colors.muted, fontWeight: '700' },
  membershipCard: { borderRadius: 27, backgroundColor: colors.forest, padding: 21, gap: 8 },
  membershipEyebrow: { color: colors.gold, fontSize: 10, letterSpacing: 1.5, fontWeight: '900' },
  membershipTitle: { color: colors.white, fontSize: 25, fontWeight: '900' },
  membershipBody: { color: 'rgba(255,255,255,0.7)', fontSize: 14, lineHeight: 21 },
  profileValue: { color: colors.text, fontSize: 18, fontWeight: '900' },
  tabBar: { height: 82, backgroundColor: colors.card, flexDirection: 'row', borderTopWidth: 1, borderTopColor: colors.line, paddingBottom: 8 },
  tabButton: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 6 },
  tabDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#C6CCC8' },
  tabDotActive: { backgroundColor: colors.gold },
  tabText: { color: colors.muted, fontSize: 11, fontWeight: '800' },
  tabTextActive: { color: colors.green },
});
