import { StatusBar as RNStatusBar, StyleSheet } from 'react-native';

import { colors } from './colors';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background, paddingTop: RNStatusBar.currentHeight ?? 0 },
  app: { flex: 1 },
  content: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 116, gap: 18 },
  hero: { borderRadius: 12, backgroundColor: colors.card, padding: 14, gap: 8, borderWidth: 1, borderColor: colors.line },
  eyebrow: { color: '#1D6337', fontSize: 9, letterSpacing: 1.1, fontWeight: '900' },
  eyebrowDark: { color: '#1D6337', fontSize: 9, letterSpacing: 1.1, fontWeight: '900' },
  heroTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  heroDogName: { color: colors.text, fontSize: 14, fontWeight: '800', marginTop: 4 },
  ownerBadge: { borderRadius: 999, borderWidth: 1, borderColor: colors.line, backgroundColor: '#F4F0E8', paddingHorizontal: 11, paddingVertical: 7 },
  ownerBadgeText: { color: colors.green, fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  heroTitle: { color: colors.text, fontSize: 26, lineHeight: 32, letterSpacing: -0.5, fontWeight: '900' },
  heroBody: { color: colors.muted, fontSize: 12.5, lineHeight: 18 },
  metricRow: { flexDirection: 'row', gap: 10 },
  metric: { flex: 1, minWidth: 0, borderRadius: 12, paddingHorizontal: 8, paddingVertical: 14, alignItems: 'center', backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line },
  metricValue: { color: colors.green, fontSize: 25, lineHeight: 30, fontWeight: '900', fontVariant: ['tabular-nums'] },
  metricLabel: { color: colors.muted, fontSize: 10, lineHeight: 14, fontWeight: '800', marginTop: 3, textAlign: 'center' },
  todayPlanSectionHeader: { gap: 5 },
  todayPlanSectionIntro: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  todayPlanLessonCard: { minHeight: 48, borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 7 },
  todayPlanLessonTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  todayPlanLessonVisualRow: { flexDirection: 'row', gap: 14, alignItems: 'center' },
  todayPlanLessonCopy: { flex: 1, gap: 4 },
  todayPlanSkillLabel: { flex: 1, color: colors.green, fontSize: 10, lineHeight: 15, letterSpacing: 0.8, textTransform: 'uppercase', fontWeight: '900' },
  todayPlanStatusBadge: { flexShrink: 0, borderRadius: 999, backgroundColor: '#FFF4DF', borderWidth: 1, borderColor: '#ECD4A8', paddingHorizontal: 10, paddingVertical: 6 },
  todayPlanStatusBadgeCompleted: { backgroundColor: colors.mint, borderColor: colors.green },
  todayPlanStatusBadgeUnavailable: { backgroundColor: '#F8E7E2', borderColor: '#E2C3BB' },
  todayPlanStatusText: { color: colors.text, fontSize: 10, lineHeight: 14, fontWeight: '900' },
  todayPlanLessonTitle: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: '900' },
  todayPlanLessonDescription: { color: colors.text, fontSize: 12, lineHeight: 17 },
  todayPlanLessonMetadata: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  todayPlanUnavailableNotice: { minHeight: 48, justifyContent: 'center', borderRadius: 10, backgroundColor: '#F8E7E2', borderWidth: 1, borderColor: '#E2C3BB', paddingHorizontal: 14, paddingVertical: 10 },
  todayPlanUnavailableText: { color: '#984B3E', fontSize: 13, lineHeight: 19, fontWeight: '800' },
  todayPlanClosedNotice: { minHeight: 48, justifyContent: 'center', borderRadius: 10, backgroundColor: colors.mint, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 14, paddingVertical: 10 },
  todayPlanClosedText: { color: colors.green, fontSize: 13, lineHeight: 19, fontWeight: '800' },
  todayPlanStaleCard: { borderRadius: 12, backgroundColor: '#FFF4DF', borderWidth: 1, borderColor: '#ECD4A8', padding: 13, gap: 5 },
  todayPlanStaleTitle: { color: '#704C11', fontSize: 17, lineHeight: 23, fontWeight: '900' },
  todayPlanStaleText: { color: colors.text, fontSize: 14, lineHeight: 21 },
  todayPlanEmptyCard: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 8 },
  pageTitle: { color: '#0B2545', fontSize: 26, lineHeight: 32, letterSpacing: -0.5, fontWeight: '900' },
  card: { backgroundColor: colors.card, borderRadius: 12, padding: 14, gap: 8, borderWidth: 1, borderColor: colors.line },
  sectionTitle: { color: '#0B2545', fontSize: 15, fontWeight: '900' },
  body: { color: colors.text, fontSize: 12.5, lineHeight: 18 },
  label: { color: colors.text, fontSize: 12, fontWeight: '800' },
  input: { borderWidth: 1, borderColor: colors.line, borderRadius: 9, backgroundColor: colors.card, paddingHorizontal: 16, paddingVertical: 15, fontSize: 15, color: colors.text },
  lessonTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  coursePill: { borderRadius: 999, backgroundColor: colors.mint, paddingHorizontal: 10, paddingVertical: 6 },
  coursePillText: { color: colors.green, fontSize: 10, fontWeight: '900', letterSpacing: 0.8 },
  duration: { color: colors.muted, fontSize: 11, fontWeight: '900', letterSpacing: 0.7 },
  lessonTitle: { color: colors.text, fontSize: 16, fontWeight: '900' },
  libraryListContent: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 116 },
  libraryHeader: { gap: 16 },
  libraryDogContext: { color: colors.muted, fontSize: 12.5, lineHeight: 18 },
  libraryDogName: { color: colors.text, fontWeight: '900' },
  librarySearchField: { minHeight: 56, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.line, borderRadius: 12, backgroundColor: colors.card, overflow: 'hidden' },
  librarySearchInput: { flex: 1, minWidth: 0, minHeight: 52, paddingHorizontal: 15, paddingVertical: 12, color: colors.text, fontSize: 16 },
  librarySearchClear: { minWidth: 58, minHeight: 52, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  librarySearchClearText: { color: colors.green, fontSize: 13, fontWeight: '900' },
  libraryFilterToolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  libraryFilterToggle: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 14, borderWidth: 1, borderColor: colors.line, borderRadius: 9, backgroundColor: colors.card, paddingHorizontal: 17, paddingVertical: 10 },
  libraryFilterToggleText: { color: colors.green, fontSize: 15, fontWeight: '900' },
  libraryFilterArrow: { color: colors.green, fontSize: 20, lineHeight: 22, fontWeight: '900' },
  libraryClearFiltersButton: { minHeight: 48, justifyContent: 'center', paddingHorizontal: 8 },
  libraryClearFiltersText: { color: colors.green, fontSize: 13, fontWeight: '900' },
  libraryActiveFilters: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  libraryActiveFilterText: { color: colors.green, backgroundColor: colors.mint, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, fontSize: 11, fontWeight: '900' },
  libraryFilterPanel: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 13, gap: 18 },
  libraryFilterGroup: { gap: 8 },
  libraryFilterChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  libraryFilterChip: { minHeight: 44, justifyContent: 'center', borderRadius: 999, borderWidth: 1, borderColor: colors.line, backgroundColor: '#FAF7F0', paddingHorizontal: 13, paddingVertical: 8 },
  libraryFilterChipSelected: { borderColor: colors.green, backgroundColor: colors.mint },
  libraryFilterChipText: { color: colors.text, fontSize: 13, fontWeight: '800' },
  libraryFilterChipTextSelected: { color: colors.green },
  libraryResultCount: { color: colors.muted, fontSize: 13, lineHeight: 18, fontWeight: '800' },
  librarySectionHeader: { marginTop: 28, marginBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  librarySectionTitle: { flex: 1, color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: '900' },
  librarySectionCount: { minWidth: 34, borderRadius: 999, backgroundColor: '#EDF5E9', color: colors.green, textAlign: 'center', paddingHorizontal: 10, paddingVertical: 6, fontSize: 12, fontWeight: '900' },
  libraryCardSpacing: { marginBottom: 14 },
  libraryLessonCard: { minHeight: 48, borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 8 },
  libraryLessonVisualRow: { flexDirection: 'row', gap: 14, alignItems: 'center' },
  libraryLessonCopy: { flex: 1, gap: 4 },
  libraryLessonTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  librarySkillLabel: { flex: 1, color: colors.green, fontSize: 10, lineHeight: 15, letterSpacing: 0.8, textTransform: 'uppercase', fontWeight: '900' },
  libraryStateBadge: { flexShrink: 0, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: colors.line },
  libraryStateAvailable: { backgroundColor: '#EEEAE2', borderColor: colors.line },
  libraryStateLocked: { backgroundColor: '#EEEAE2', borderColor: colors.line },
  libraryStateInProgress: { backgroundColor: '#FFF4DF', borderColor: '#ECD4A8' },
  libraryStateCompleted: { backgroundColor: colors.mint, borderColor: colors.green },
  libraryStateText: { color: colors.text, fontSize: 10, lineHeight: 14, fontWeight: '900' },
  libraryLessonTitle: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: '900' },
  libraryLessonDescription: { color: colors.text, fontSize: 12, lineHeight: 17 },
  libraryMetadataRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 7 },
  libraryMetadataText: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  libraryMetadataDot: { color: colors.green, fontSize: 13, lineHeight: 17, fontWeight: '900' },
  libraryLockNotice: { borderRadius: 10, backgroundColor: '#FFF4DF', padding: 11, gap: 3 },
  libraryLockLabel: { color: '#704C11', fontSize: 9, lineHeight: 13, letterSpacing: 0.8, fontWeight: '900' },
  libraryLockText: { color: colors.text, fontSize: 13, lineHeight: 19 },
  librarySelfDirectedNotice: { borderRadius: 10, backgroundColor: colors.mint, padding: 11, gap: 3, borderWidth: 1, borderColor: colors.line },
  librarySelfDirectedLabel: { color: colors.green, fontSize: 9, lineHeight: 13, letterSpacing: 0.8, fontWeight: '900' },
  librarySelfDirectedText: { color: colors.text, fontSize: 13, lineHeight: 19 },
  libraryCardAction: { color: colors.green, fontSize: 13, lineHeight: 18, fontWeight: '900' },
  libraryNoResultsCard: { marginTop: 22, borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 6 },
  libraryEmptyCard: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 8 },
  librarySummaryHero: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 8 },
  librarySummaryLockCard: { borderRadius: 12, backgroundColor: '#FFF4DF', borderWidth: 1, borderColor: '#ECD4A8', padding: 13, gap: 6 },
  librarySummaryLockReason: { color: colors.text, fontSize: 17, lineHeight: 24, fontWeight: '900' },
  librarySummarySupportText: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  librarySummaryNotice: { borderRadius: 12, backgroundColor: colors.mint, borderWidth: 1, borderColor: colors.line, padding: 13, gap: 5 },
  librarySummaryNoticeTitle: { color: colors.green, fontSize: 16, lineHeight: 21, fontWeight: '900' },
  lessonDetails: { gap: 14, paddingTop: 4 },
  coachingGoalCard: { borderRadius: 12, backgroundColor: colors.mint, borderWidth: 1, borderColor: colors.line, padding: 12, gap: 6 },
  coachingKicker: { color: colors.green, fontSize: 10, lineHeight: 14, letterSpacing: 1.1, fontWeight: '900' },
  lessonGoal: { color: colors.text, fontSize: 13.5, lineHeight: 19, fontWeight: '800' },
  coachingMeta: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  coachingSectionTitle: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: '900' },
  coachingSectionIntro: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 3 },
  lessonIllustrationSection: { gap: 8 },
  lessonIllustrationCard: { borderRadius: 12, overflow: 'hidden', backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line },
  lessonIllustrationFrame: { width: '100%', aspectRatio: 3 / 2, backgroundColor: '#EEF5EA', overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  lessonIllustration: { width: '100%', height: '100%' },
  lessonIllustrationTone: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(42,30,8,0.08)' },
  illustrationCopy: { padding: 14, gap: 5 },
  illustrationLabel: { color: colors.green, fontSize: 9, lineHeight: 13, letterSpacing: 1, fontWeight: '900' },
  illustrationText: { color: colors.text, fontSize: 14, lineHeight: 21 },
  illustrationProblem: { marginTop: 7, borderRadius: 10, backgroundColor: '#FFF4DF', padding: 11, gap: 3 },
  illustrationProblemLabel: { color: '#704C11', fontSize: 9, lineHeight: 13, letterSpacing: 0.8, fontWeight: '900' },
  illustrationProblemText: { color: colors.text, fontSize: 13, lineHeight: 19 },
  lessonDiagram: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 12, gap: 4 },
  diagramStageGroup: { alignItems: 'stretch' },
  diagramStage: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 8 },
  diagramNumber: { width: 26, height: 26, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.green },
  diagramNumberText: { color: colors.white, fontSize: 12, lineHeight: 16, fontWeight: '900' },
  diagramCopy: { flex: 1, gap: 3 },
  diagramTitle: { color: colors.green, fontSize: 14, lineHeight: 19, fontWeight: '900' },
  diagramText: { color: colors.text, fontSize: 12, lineHeight: 18 },
  diagramArrow: { color: colors.green, fontSize: 20, lineHeight: 20, textAlign: 'center', fontWeight: '900' },
  coachingListCard: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 7 },
  coachingListRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  coachingBullet: { width: 20, color: colors.green, fontSize: 16, lineHeight: 21, fontWeight: '900', textAlign: 'center' },
  coachingTipIcon: { width: 20, color: '#704C11', fontSize: 15, lineHeight: 21, fontWeight: '900', textAlign: 'center' },
  coachingWarningIcon: { width: 20, height: 20, borderRadius: 10, color: '#704C11', backgroundColor: '#FFF4DF', fontSize: 12, lineHeight: 20, fontWeight: '900', textAlign: 'center' },
  coachingListText: { flex: 1, color: colors.text, fontSize: 12.5, lineHeight: 18 },
  lessonSteps: { gap: 10 },
  lessonStep: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14 },
  lessonStepNumber: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.green },
  lessonStepNumberText: { color: colors.white, fontSize: 13, lineHeight: 17, fontWeight: '900' },
  lessonStepText: { flex: 1, color: colors.text, fontSize: 12.5, lineHeight: 18 },
  coachingCheckIn: { borderRadius: 12, backgroundColor: '#E0EBEF', borderWidth: 1, borderColor: '#B9CDD4', padding: 14, gap: 5 },
  coachingCheckInTitle: { color: '#3F6878', fontSize: 10, lineHeight: 14, letterSpacing: 0.9, fontWeight: '900' },
  coachingCheckInText: { color: colors.text, fontSize: 14, lineHeight: 21 },
  coachingPreventionCard: { borderRadius: 12, backgroundColor: '#FFF4DF', borderWidth: 1, borderColor: '#ECD4A8', padding: 14, gap: 7 },
  troubleshootingList: { gap: 9, marginTop: 8 },
  troubleshootingCard: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 13, gap: 5 },
  troubleshootingProblem: { color: colors.text, fontSize: 13, lineHeight: 20, fontWeight: '900' },
  troubleshootingSolution: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  safetyTitle: { color: '#984B3E', fontSize: 14, lineHeight: 22, fontWeight: '900' },
  safetyText: { color: colors.text, fontSize: 13, lineHeight: 20 },
  completionCard: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: '#ECD4A8', padding: 12, gap: 5 },
  completionTitle: { color: colors.text, fontSize: 16, lineHeight: 22, fontWeight: '900' },
  completionText: { color: colors.text, fontSize: 14, lineHeight: 21 },
  completionMeta: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  encouragementCard: { borderRadius: 12, backgroundColor: colors.card, padding: 13, gap: 6 },
  encouragementTitle: { color: colors.green, fontSize: 10, lineHeight: 14, letterSpacing: 1, fontWeight: '900' },
  encouragementText: { color: colors.text, fontSize: 14, lineHeight: 21, fontWeight: '700' },
  guidedCompleteCard: { borderRadius: 12, backgroundColor: colors.card, padding: 14, gap: 8, alignItems: 'center' },
  guidedCompleteMark: { width: 54, height: 54, borderRadius: 27, backgroundColor: colors.green, color: colors.white, fontSize: 28, lineHeight: 54, fontWeight: '900', textAlign: 'center' },
  guidedCompleteKicker: { color: colors.green, fontSize: 10, lineHeight: 14, letterSpacing: 1.2, fontWeight: '900' },
  guidedCompleteTitle: { color: colors.text, fontSize: 22, lineHeight: 28, fontWeight: '900', textAlign: 'center' },
  guidedCompleteBody: { color: colors.muted, fontSize: 15, lineHeight: 22, textAlign: 'center' },
  sessionSnapshotCard: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 13, gap: 8 },
  sessionSnapshotTitle: { color: colors.text, fontSize: 17, lineHeight: 23, fontWeight: '900' },
  sessionSnapshotRow: { flexDirection: 'row', gap: 8 },
  sessionSnapshotMetric: { flex: 1, minWidth: 0, borderRadius: 13, backgroundColor: colors.mint, padding: 10, alignItems: 'center', gap: 3 },
  sessionSnapshotValue: { color: colors.green, fontSize: 21, lineHeight: 27, fontWeight: '900' },
  sessionSnapshotLabel: { color: colors.muted, fontSize: 10, lineHeight: 14, fontWeight: '800', textAlign: 'center' },
  sessionRatingStack: { gap: 9 },
  sessionRatingButton: { minHeight: 64, borderRadius: 9, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 13, justifyContent: 'center' },
  sessionRatingButtonSelected: { borderColor: colors.green, borderWidth: 2, backgroundColor: colors.mint },
  sessionRatingTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  sessionRatingValue: { width: 30, height: 30, borderRadius: 15, backgroundColor: colors.green, color: colors.white, fontSize: 14, lineHeight: 30, fontWeight: '900', textAlign: 'center' },
  sessionRatingCopy: { flex: 1, minWidth: 0, gap: 2 },
  sessionRatingTitle: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: '900' },
  sessionRatingDescription: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  sessionRatingSuggested: { flexShrink: 0, color: '#704C11', backgroundColor: '#FFF4DF', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 5, fontSize: 8, lineHeight: 11, letterSpacing: 0.6, fontWeight: '900' },
  sessionTimerCard: { borderRadius: 12, backgroundColor: '#0B2545', padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 14 },
  sessionTimerLabel: { color: '#F0D6A6', fontSize: 9, lineHeight: 13, letterSpacing: 1, fontWeight: '900' },
  sessionTimer: { color: colors.white, fontSize: 31, lineHeight: 37, fontWeight: '900', fontVariant: ['tabular-nums'] },
  timerButton: { minWidth: 86, minHeight: 48, borderRadius: 9, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 },
  timerButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '900' },
  sessionStepCard: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 7 },
  sessionStepKicker: { color: colors.green, fontSize: 10, lineHeight: 14, letterSpacing: 1, fontWeight: '900' },
  sessionStepText: { color: colors.text, fontSize: 16, lineHeight: 22, fontWeight: '900' },
  sessionCoachCard: { borderRadius: 12, backgroundColor: colors.mint, borderWidth: 1, borderColor: colors.line, padding: 12, gap: 5 },
  sessionCoachLabel: { color: colors.green, fontSize: 9, lineHeight: 13, letterSpacing: 0.9, fontWeight: '900' },
  sessionCoachBody: { color: colors.text, fontSize: 12.5, lineHeight: 18 },
  sessionCheckInCard: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 13, gap: 7 },
  sessionCheckInLabel: { color: '#3F6878', fontSize: 9, lineHeight: 13, letterSpacing: 0.9, fontWeight: '900' },
  sessionCheckInHeading: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: '900' },
  sessionCountRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  sessionCountText: { color: colors.green, backgroundColor: colors.mint, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, fontSize: 11, lineHeight: 15, fontWeight: '900' },
  sessionResetCard: { borderRadius: 12, backgroundColor: '#FFF4DF', borderWidth: 1, borderColor: '#ECD4A8', padding: 13, gap: 8 },
  sessionResetTitle: { color: '#704C11', fontSize: 16, lineHeight: 21, fontWeight: '900' },
  sessionResetText: { color: colors.text, fontSize: 13, lineHeight: 19 },
  sessionActionRow: { flexDirection: 'row', gap: 9 },
  sessionWinButton: { flex: 1, minHeight: 50, borderRadius: 9, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  sessionWinButtonText: { color: colors.white, fontSize: 13, fontWeight: '900', textAlign: 'center' },
  sessionHelpButton: { flex: 1, minHeight: 50, borderRadius: 9, backgroundColor: '#FFF4DF', borderWidth: 1, borderColor: '#ECD4A8', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  sessionHelpButtonText: { color: '#704C11', fontSize: 13, fontWeight: '900', textAlign: 'center' },
  sessionTroubleCard: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 12, gap: 5 },
  sessionTroubleLabel: { color: '#704C11', fontSize: 9, lineHeight: 13, letterSpacing: 0.8, fontWeight: '900' },
  sessionOutlineButton: { flex: 1, minHeight: 48, borderRadius: 9, borderWidth: 1, borderColor: colors.green, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  sessionOutlineButtonText: { color: colors.green, fontSize: 14, fontWeight: '900' },
  sessionExitNote: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  sessionPromiseCard: { borderRadius: 12, backgroundColor: '#E0EBEF', borderWidth: 1, borderColor: '#B9CDD4', padding: 12, gap: 5 },
  sessionPromiseTitle: { color: '#3F6878', fontSize: 16, lineHeight: 21, fontWeight: '900' },
  sessionPromiseText: { color: colors.text, fontSize: 13, lineHeight: 20 },
  primaryButton: { minHeight: 52, borderRadius: 9, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
  primaryButtonText: { color: colors.white, fontSize: 14, fontWeight: '900' },
  pressed: { opacity: 0.82 },
  disabled: { opacity: 0.45 },
  fieldGroup: { gap: 7 },
  inputError: { borderColor: '#984B3E', borderWidth: 2 },
  validationText: { color: '#984B3E', fontSize: 13, lineHeight: 18, fontWeight: '700' },
  chipGroup: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  selectionChip: { minHeight: 48, justifyContent: 'center', borderRadius: 999, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.card, paddingHorizontal: 15, paddingVertical: 10 },
  selectionChipActive: { borderColor: colors.green, backgroundColor: colors.mint },
  selectionChipText: { color: colors.text, fontSize: 13, fontWeight: '700' },
  selectionChipTextActive: { color: colors.green, fontWeight: '900' },
  onboardingProgress: { gap: 8 },
  progressStep: { color: colors.muted, fontSize: 11, letterSpacing: 1.2, fontWeight: '900' },
  onboardingProgressTrack: { height: 7, borderRadius: 999, backgroundColor: colors.line, overflow: 'hidden' },
  onboardingProgressFill: { height: '100%', borderRadius: 999, backgroundColor: colors.green },
  secondaryTextButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  secondaryText: { color: colors.green, fontSize: 13, fontWeight: '900' },
  centerState: { flex: 1, minHeight: 320, alignItems: 'center', justifyContent: 'center', gap: 16, padding: 24 },
  errorCard: { backgroundColor: '#F8E7E2', borderColor: '#E2C3BB', borderWidth: 1, borderRadius: 12, padding: 14, gap: 8 },
  welcomeMark: { width: 96, height: 96, alignSelf: 'center', borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center', shadowColor: '#4B4136', shadowOpacity: 0.12, shadowRadius: 18, shadowOffset: { width: 0, height: 6 }, elevation: 5 },
  welcomeMarkImage: { width: 78, height: 78 },
  onboardingTitle: { color: colors.text, fontSize: 27, lineHeight: 33, letterSpacing: -0.5, fontWeight: '900' },
  onboardingBody: { color: colors.muted, fontSize: 13.5, lineHeight: 20 },
  photoPreview: { width: 96, height: 96, borderRadius: 48, backgroundColor: colors.mint, borderWidth: 2, borderColor: '#ECD4A8' },
  photoActionRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  dateSelection: { minHeight: 52, justifyContent: 'center', borderWidth: 1, borderColor: colors.line, borderRadius: 9, backgroundColor: colors.card, paddingHorizontal: 14, paddingVertical: 12 },
  dateSelectionText: { color: colors.text, fontSize: 16, fontWeight: '700' },
  dateSelectionPlaceholder: { color: '#7C827D', fontSize: 16 },
  developerToolsCard: { backgroundColor: '#FFF4DF', borderRadius: 12, padding: 14, gap: 8, borderWidth: 1, borderColor: '#ECD4A8' },
  assessmentQuestion: { backgroundColor: colors.card, borderRadius: 12, padding: 14, gap: 8, borderWidth: 1, borderColor: colors.line },
  assessmentOptions: { gap: 8 },
  assessmentOption: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderColor: colors.line, borderRadius: 10, backgroundColor: colors.card, paddingHorizontal: 14, paddingVertical: 10 },
  assessmentOptionSelected: { borderColor: colors.green, backgroundColor: colors.mint, borderWidth: 2 },
  radioOuter: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: colors.muted, alignItems: 'center', justifyContent: 'center' },
  radioSelected: { borderColor: colors.green },
  radioInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.green },
  optionText: { flex: 1, color: colors.text, fontSize: 13.5, fontWeight: '700' },
  safetyCard: { backgroundColor: '#F8E7E2', borderColor: '#E2C3BB', borderWidth: 1, borderRadius: 12, padding: 14, gap: 8 },
  scoreRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', minHeight: 48, borderBottomWidth: 1, borderBottomColor: colors.line },
  scoreValue: { color: colors.green, fontSize: 15, fontWeight: '900' },
  completedBadge: { minHeight: 48, borderRadius: 9, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center' },
  completedBadgeText: { color: colors.green, fontSize: 15, fontWeight: '900' },
  progressHero: { borderRadius: 12, backgroundColor: colors.card, padding: 14, gap: 8 },
  progressValue: { color: colors.text, fontSize: 40, fontWeight: '900', letterSpacing: -1 },
  progressLabel: { color: colors.muted, fontSize: 15, fontWeight: '700' },
  progressTrack: { height: 6, borderRadius: 999, backgroundColor: '#EDE8DE', overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 999, backgroundColor: colors.green },
  progressHistoryCard: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 8 },
  progressRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: colors.line },
  completeText: { color: colors.green, fontWeight: '900' },
  notStartedText: { color: colors.muted, fontWeight: '700' },
  historyListContent: { flexGrow: 1, paddingHorizontal: 18, paddingTop: 18, paddingBottom: 110 },
  historyHeader: { gap: 10, marginBottom: 20 },
  historyDogContext: { color: colors.muted, fontSize: 12.5, lineHeight: 18 },
  historyStateScreen: { flex: 1, padding: 18, gap: 14 },
  historyCardSpacing: { marginBottom: 12 },
  historySessionCard: { minHeight: 48, borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 13, gap: 6 },
  historyCardTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  historySkillLabel: { flex: 1, color: colors.green, fontSize: 10, lineHeight: 15, letterSpacing: 0.8, textTransform: 'uppercase', fontWeight: '900' },
  historyOutcomeBadge: { flexShrink: 0, borderRadius: 999, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 6 },
  historyOutcomeSuccess: { backgroundColor: colors.mint, borderColor: colors.green },
  historyOutcomePartial: { backgroundColor: '#FFF4DF', borderColor: '#ECD4A8' },
  historyOutcomeUnsuccessful: { backgroundColor: '#F8E7E2', borderColor: '#E2C3BB' },
  historyOutcomeText: { color: colors.text, fontSize: 10, lineHeight: 14, fontWeight: '900' },
  historySessionTitle: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: '900' },
  historyMetadataRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 7 },
  historyMetadataText: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  historyMetadataDot: { color: colors.green, fontSize: 13, lineHeight: 17, fontWeight: '900' },
  historyNotesPreview: { color: colors.text, fontSize: 13, lineHeight: 19 },
  historyCardAction: { color: colors.green, fontSize: 13, lineHeight: 18, fontWeight: '900' },
  historyEmptyCard: { marginTop: 12, borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 8 },
  historyListFooter: { paddingTop: 8, paddingBottom: 8 },
  historyMissingLessonNotice: { borderRadius: 12, backgroundColor: '#FFF4DF', borderWidth: 1, borderColor: '#ECD4A8', padding: 13, gap: 5 },
  historyMissingLessonTitle: { color: '#704C11', fontSize: 16, lineHeight: 22, fontWeight: '900' },
  historyDetailCard: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 8 },
  historyDetailRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16, borderBottomWidth: 1, borderBottomColor: colors.line, paddingVertical: 9 },
  historyDetailLabel: { flex: 1, color: colors.muted, fontSize: 13, lineHeight: 19, fontWeight: '800' },
  historyDetailValue: { flex: 1, color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: '900', textAlign: 'right' },
  historyDetailSupportingText: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  progressSnapshotCard: { gap: 18 },
  membershipCard: { borderRadius: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 6, shadowColor: '#4B4136', shadowOpacity: 0.18, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 6 },
  membershipTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  membershipBadge: { borderRadius: 999, borderWidth: 1, borderColor: colors.line, backgroundColor: '#F4F0E8', paddingHorizontal: 10, paddingVertical: 6 },
  membershipBadgeText: { color: colors.green, fontSize: 9, lineHeight: 12, letterSpacing: 1, fontWeight: '900' },
  membershipEyebrow: { color: colors.green, fontSize: 10, letterSpacing: 1.5, fontWeight: '900' },
  membershipTitle: { color: colors.text, fontSize: 19, fontWeight: '900' },
  membershipBody: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  profileDetailRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 18, borderBottomWidth: 1, borderBottomColor: colors.line, paddingVertical: 11 },
  profileDetailRowLast: { borderBottomWidth: 0, paddingBottom: 0 },
  profileDetailLabel: { flex: 1, color: colors.muted, fontSize: 13, lineHeight: 19, fontWeight: '700' },
  profileDetailValue: { flex: 1.4, color: colors.text, fontSize: 15, lineHeight: 21, fontWeight: '900', textAlign: 'right' },
  tabBar: { height: 82, backgroundColor: '#FFFDF8', flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#E5E0D5', paddingHorizontal: 6, paddingTop: 7, paddingBottom: 7, gap: 2 },
  tabButton: { flex: 1, minHeight: 62, borderRadius: 10, alignItems: 'center', justifyContent: 'center', gap: 3, backgroundColor: 'transparent', borderWidth: 1, borderColor: 'transparent' },
  tabButtonActive: { backgroundColor: '#EEF5EA', borderColor: '#D9E8D3' },
  tabIconShell: { width: 32, height: 27, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  tabIconShellActive: { backgroundColor: 'rgba(23,106,58,0.09)' },
  tabText: { color: '#818A83', fontSize: 9, lineHeight: 12, fontWeight: '800', letterSpacing: 0.1 },
  tabTextActive: { color: '#176A3A' },

  // ---- Home (Today) warm editorial screen ----
  homeRoot: { flex: 1, backgroundColor: '#FBF8F0' },
  homeSafe: { flex: 1 },
  homeBody: { flexGrow: 1, width: '100%', alignItems: 'center', paddingHorizontal: 18, paddingTop: 8, paddingBottom: 26, gap: 20 },
  homeTopBar: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 14 },
  homeTopBarCopy: { flex: 1, gap: 2 },
  homeBrand: { color: '#1D6337', fontSize: 10, lineHeight: 14, letterSpacing: 1.7, fontWeight: '900' },
  homeTodayLabel: { color: '#657168', fontSize: 16, lineHeight: 21, fontWeight: '700' },
  homeDogName: { color: '#10271A', fontSize: 31, lineHeight: 36, letterSpacing: -0.8, fontWeight: '900' },
  homeHeaderAside: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  homeSmallAvatar: { padding: 2, borderRadius: 999, borderWidth: 1, borderColor: '#D3CCBE', backgroundColor: '#FFFFFF' },
  homePlanProgress: { minWidth: 54, minHeight: 48, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EEF5EA', borderWidth: 1, borderColor: '#C9D5C3' },
  homePlanProgressValue: { color: '#176A3A', fontSize: 15, lineHeight: 18, fontWeight: '900', fontVariant: ['tabular-nums'] },
  homePlanProgressLabel: { color: '#657168', fontSize: 8, lineHeight: 11, letterSpacing: 1, fontWeight: '900' },
  homeButtons: { width: '100%', alignItems: 'center', gap: 12 },
  homeButton: { width: '100%', minHeight: 50, borderRadius: 9, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20, borderWidth: 1, borderColor: '#D3CCBE', backgroundColor: 'rgba(255,252,246,0.72)' },
  homeButtonText: { color: '#176A3A', fontSize: 15, fontWeight: '900', letterSpacing: 0.1 },
  homeButtonPressed: { opacity: 0.85, transform: [{ scale: 0.99 }] },
  homeWelcome: { width: '100%', alignItems: 'flex-start', gap: 5, padding: 13, borderRadius: 12, backgroundColor: '#FFFDF8', borderWidth: 1, borderColor: '#E5E0D5' },
  homeWelcomeKicker: { color: '#1D6337', fontSize: 9, lineHeight: 13, letterSpacing: 1.3, fontWeight: '900' },
  homeWelcomeTitle: { color: '#10271A', fontSize: 18, lineHeight: 23, fontWeight: '900' },
  homeWelcomeLine: { color: '#657168', fontSize: 13, lineHeight: 19 },
  homeWelcomeReport: { color: '#176A3A', fontSize: 12, lineHeight: 18, fontWeight: '800' },
  homePlanCard: { width: '100%', borderRadius: 12, padding: 0, gap: 0, overflow: 'hidden', backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5E0D5', shadowColor: '#173524', shadowOpacity: 0.08, shadowRadius: 14, shadowOffset: { width: 0, height: 7 }, elevation: 3 },
  homePlanCardTopRow: { minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingHorizontal: 16, paddingTop: 4 },
  homePlanKicker: { color: '#1D6337', fontSize: 10, lineHeight: 14, letterSpacing: 1.2, fontWeight: '900' },
  homePlanMinutes: { color: '#657168', fontSize: 10, lineHeight: 14, letterSpacing: 0.8, fontWeight: '900', paddingRight: 18, paddingTop: 17 },
  homePlanImageFrame: { width: '100%', aspectRatio: 3 / 2, marginTop: 14, overflow: 'hidden', backgroundColor: '#EEF5EA' },
  homePlanImage: { width: '100%', height: '100%' },
  homePlanImageTone: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(24,55,43,0.04)' },
  homePlanImageBadge: { position: 'absolute', left: 14, bottom: 13, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, backgroundColor: 'rgba(24,55,43,0.88)' },
  homePlanImageBadgeText: { color: '#FFFFFF', fontSize: 9, lineHeight: 12, textTransform: 'uppercase', letterSpacing: 0.9, fontWeight: '900' },
  homePlanLessonCopy: { minWidth: 0, gap: 5, paddingHorizontal: 18, paddingTop: 16 },
  homePlanCompleteCopy: { gap: 5, paddingHorizontal: 18, paddingTop: 16 },
  homePlanLessonTitle: { color: '#10271A', fontSize: 19, lineHeight: 24, fontWeight: '900' },
  homePlanLessonDescription: { color: '#657168', fontSize: 13, lineHeight: 18 },
  homePrimaryButton: { minHeight: 50, margin: 16, borderRadius: 9, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20, backgroundColor: '#176A3A', shadowColor: '#0D3F27', shadowOpacity: 0.12, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  homePrimaryButtonText: { color: '#FFFFFF', fontSize: 15, lineHeight: 20, fontWeight: '900' },
  homeHelpNowCard: { width: '100%', minHeight: 104, flexDirection: 'row', alignItems: 'center', gap: 14, borderRadius: 12, padding: 17, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E4DED3', shadowColor: '#0D3F27', shadowOpacity: 0.12, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 4 },
  homeHelpNowCopy: { flex: 1, minWidth: 0, gap: 3 },
  homeHelpNowKicker: { color: '#704C11', fontSize: 9, lineHeight: 13, letterSpacing: 1.4, fontWeight: '900' },
  homeHelpNowTitle: { color: '#0B2545', fontSize: 19, lineHeight: 24, fontWeight: '900' },
  homeHelpNowBody: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  homeHelpNowAction: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22, backgroundColor: '#2F8148' },
  homeHelpNowActionText: { color: '#FFFFFF', fontSize: 9, lineHeight: 12, letterSpacing: 0.7, fontWeight: '900' },
  homeHelpNowArrow: { color: '#10271A', fontSize: 26, lineHeight: 28, fontWeight: '700' },


  // ---- Reference-inspired home and discovery navigation ----
  referenceHomeHeader: { width: '100%', gap: 4, paddingTop: 2 },
  referenceHomeHeaderTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16 },
  referenceHomeTitle: { color: '#10271A', fontSize: 30, lineHeight: 36, fontWeight: '900', letterSpacing: -0.7 },
  referenceHomeGreeting: { color: '#1D6337', fontSize: 13, lineHeight: 18, fontWeight: '900', marginTop: 2 },
  referenceHomeMessage: { color: '#10271A', fontSize: 15, lineHeight: 21, maxWidth: '78%' },
  referenceScreenHeader: { gap: 6 },
  referenceScreenTitle: { color: '#10271A', fontSize: 26, lineHeight: 32, fontWeight: '900', letterSpacing: -0.6 },
  referenceScreenIntro: { color: '#657168', fontSize: 12.5, lineHeight: 18 },
  screenLabel: { color: '#1D6337', fontSize: 10, lineHeight: 14, letterSpacing: 1.1, fontWeight: '900' },
  homeChoiceStack: { width: '100%', gap: 10 },
  homeChoiceCard: { width: '100%', minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: 13, borderRadius: 12, backgroundColor: '#FFFDF8', borderWidth: 1, borderColor: '#E5E0D5', paddingHorizontal: 14, paddingVertical: 12, shadowColor: '#173524', shadowOpacity: 0.045, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 1 },
  homeChoiceIcon: { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  homeChoiceCopy: { flex: 1, minWidth: 0, gap: 2 },
  homeChoiceTitle: { color: '#10271A', fontSize: 16, lineHeight: 21, fontWeight: '900' },
  homeChoiceBody: { color: '#657168', fontSize: 12, lineHeight: 17 },
  homeChoiceArrow: { color: '#657168', fontSize: 27, lineHeight: 29, fontWeight: '400' },
  homeSectionHeadingRow: { width: '100%', flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12 },
  homeSectionKicker: { color: '#1D6337', fontSize: 9, lineHeight: 13, letterSpacing: 1.2, fontWeight: '900' },
  homeSectionTitle: { color: '#10271A', fontSize: 20, lineHeight: 26, fontWeight: '900', marginTop: 2 },
  homeSectionLink: { color: '#176A3A', fontSize: 13, lineHeight: 19, fontWeight: '900', paddingVertical: 3 },
  homePlanProgressInline: { minWidth: 42, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EEF5EA', borderWidth: 1, borderColor: '#D9E8D3' },
  homePlanProgressInlineText: { color: '#176A3A', fontSize: 11, lineHeight: 15, fontWeight: '900', fontVariant: ['tabular-nums'] },
  homePlanCompactBody: { flexDirection: 'row', gap: 13, paddingHorizontal: 16, paddingTop: 10 },
  homePlanCompactImage: { width: 112, height: 112, borderRadius: 10, backgroundColor: '#EEF5EA' },
  homePlanCompactCopy: { flex: 1, minWidth: 0, justifyContent: 'center', gap: 4 },
  homePlanCompactSkill: { color: '#176A3A', fontSize: 9, lineHeight: 13, letterSpacing: 0.8, textTransform: 'uppercase', fontWeight: '900' },
  homePlanCompactMeta: { color: '#1D6337', fontSize: 11, lineHeight: 16, fontWeight: '800' },
  discoveryCategoryList: { gap: 10 },
  discoveryCategoryRow: { minHeight: 90, flexDirection: 'row', alignItems: 'center', gap: 12, overflow: 'hidden', borderRadius: 12, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5E0D5', paddingRight: 13, shadowColor: '#173524', shadowOpacity: 0.045, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 1 },
  discoveryCategoryRowImage: { width: 94, alignSelf: 'stretch', backgroundColor: '#EEF5EA' },
  discoveryCategoryRowCopy: { flex: 1, minWidth: 0, gap: 1, paddingVertical: 10 },
  discoveryCategoryRowTitle: { color: '#10271A', fontSize: 16, lineHeight: 21, fontWeight: '900' },
  discoveryCategoryRowCount: { color: '#176A3A', fontSize: 11, lineHeight: 15, fontWeight: '900' },
  discoveryCategoryRowDescription: { color: '#657168', fontSize: 11, lineHeight: 15 },
  discoveryCategoryRowArrow: { color: '#657168', fontSize: 25, lineHeight: 27 },
  discoveryShortcutStack: { gap: 10 },
  discoveryStageList: { gap: 12 },
  discoveryStageRow: { minHeight: 142, flexDirection: 'row', alignItems: 'stretch', overflow: 'hidden', borderRadius: 12, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5E0D5', shadowColor: '#173524', shadowOpacity: 0.05, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  discoveryStageRowImage: { width: 118, backgroundColor: '#EEF5EA' },
  discoveryStageRowCopy: { flex: 1, minWidth: 0, justifyContent: 'center', gap: 3, paddingHorizontal: 14, paddingVertical: 13 },
  discoveryStageRowTitle: { color: '#10271A', fontSize: 20, lineHeight: 25, fontWeight: '900' },
  discoveryStageRowAge: { color: '#1D6337', fontSize: 11, lineHeight: 15, fontWeight: '900' },
  discoveryStageRowDescription: { color: '#657168', fontSize: 12, lineHeight: 17 },
  discoveryStageRowCount: { color: '#176A3A', fontSize: 11, lineHeight: 15, fontWeight: '900', marginTop: 2 },
  discoveryStageRowArrow: { alignSelf: 'center', color: '#657168', fontSize: 26, lineHeight: 28, paddingRight: 12 },

  recommendedHero: { alignItems: 'center', gap: 7, paddingTop: 2, paddingBottom: 4 },
  recommendedHeroStar: { color: '#E1A126', fontSize: 34, lineHeight: 38, fontWeight: '900' },
  recommendedLessonList: { gap: 11 },
  discoveryRecommendedRow: { minHeight: 126, flexDirection: 'row', alignItems: 'stretch', overflow: 'hidden', borderRadius: 12, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5E0D5', shadowColor: '#173524', shadowOpacity: 0.05, shadowRadius: 9, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  discoveryRecommendedRowImage: { width: 104, backgroundColor: '#EEF5EA' },
  discoveryRecommendedRowCopy: { flex: 1, minWidth: 0, justifyContent: 'center', gap: 3, paddingHorizontal: 13, paddingVertical: 12 },
  discoveryRecommendedRowDescription: { color: '#657168', fontSize: 12, lineHeight: 16 },
  discoveryRecommendedRowArrow: { alignSelf: 'center', color: '#657168', fontSize: 26, lineHeight: 28, paddingRight: 12 },
  dogStageNote: { borderRadius: 12, backgroundColor: '#EEF5EA', borderWidth: 1, borderColor: '#D9E8D3', padding: 13, gap: 5 },
  dogStageNoteTitle: { color: '#176A3A', fontSize: 16, lineHeight: 21, fontWeight: '900' },
  dogStageNoteBody: { color: '#657168', fontSize: 13, lineHeight: 19 },
  todaySummaryCard: { borderRadius: 12, backgroundColor: '#FFFFFF', padding: 18, gap: 13, shadowColor: '#0D3F27', shadowOpacity: 0.13, shadowRadius: 14, shadowOffset: { width: 0, height: 7 }, elevation: 4 },
  todaySummaryTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 14 },
  todaySummaryKicker: { color: '#1D6337', fontSize: 9, lineHeight: 13, letterSpacing: 1.1, fontWeight: '900' },
  todaySummaryTitle: { color: '#FFFFFF', fontSize: 22, lineHeight: 28, fontWeight: '900', marginTop: 2 },
  todaySummaryMinutes: { width: 54, height: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EDF5E9', borderWidth: 1, borderColor: '#CFE2C8' },
  todaySummaryMinutesValue: { color: '#FFFFFF', fontSize: 19, lineHeight: 22, fontWeight: '900' },
  todaySummaryMinutesLabel: { color: '#1D6337', fontSize: 8, lineHeight: 11, letterSpacing: 0.8, fontWeight: '900' },
  todaySummaryTrack: { height: 8, borderRadius: 999, overflow: 'hidden', backgroundColor: '#EDE8DE' },
  todaySummaryFill: { height: '100%', borderRadius: 999, backgroundColor: '#2F8148' },
  todaySummaryBody: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  todayLessonList: { gap: 14 },


  // ---- Lesson discovery: recommendations, categories and dog stages ----
  academyDiscoveryHero: { gap: 24 },
  academyDogCard: { gap: 14, borderRadius: 12, backgroundColor: '#FFFDF8', borderWidth: 1, borderColor: '#E5E0D5', padding: 13, shadowColor: '#173524', shadowOpacity: 0.05, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  academyDogCardCopy: { gap: 3 },
  academyDogCardLabel: { color: '#1D6337', fontSize: 9, lineHeight: 13, letterSpacing: 1.2, fontWeight: '900' },
  academyDogCardName: { color: '#10271A', fontSize: 22, lineHeight: 28, fontWeight: '900' },
  academyDogCardBody: { color: '#657168', fontSize: 13, lineHeight: 19 },
  homeDiscoverySection: { width: '100%', gap: 12 },
  discoveryPathRow: { gap: 10 },
  discoverySection: { gap: 12 },
  discoverySectionHeader: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12 },
  discoverySectionHeaderCopy: { flex: 1, minWidth: 0, gap: 4 },
  discoverySectionKicker: { color: '#1D6337', fontSize: 9, lineHeight: 13, letterSpacing: 1.2, fontWeight: '900' },
  discoverySectionTitle: { color: colors.text, fontSize: 20, lineHeight: 26, fontWeight: '900' },
  discoverySectionIntro: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  discoverySectionLink: { color: colors.green, fontSize: 13, lineHeight: 19, fontWeight: '900', paddingVertical: 4 },
  discoveryHorizontalContent: { gap: 11, paddingRight: 10 },
  discoveryEmptyText: { color: colors.muted, fontSize: 14, lineHeight: 20, borderRadius: 12, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.card, padding: 14 },
  discoveryCategoryGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 12 },
  discoveryCategoryCard: { width: '48%', minHeight: 160, borderRadius: 16, overflow: 'hidden', backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, shadowColor: '#173524', shadowOpacity: 0.07, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 2 },
  discoveryCategoryCardCompact: { width: 132, height: 120, borderRadius: 15, overflow: 'hidden', backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line },
  discoveryCategoryImage: { width: '100%', height: '100%' },
  discoveryCategoryTone: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(7,35,20,0.30)' },
  discoveryCategoryCopy: { position: 'absolute', left: 12, right: 12, bottom: 11, gap: 2 },
  discoveryCategoryTitle: { color: colors.white, fontSize: 17, lineHeight: 21, fontWeight: '900', textShadowColor: 'rgba(0,0,0,0.45)', textShadowRadius: 4, textShadowOffset: { width: 0, height: 1 } },
  discoveryCategoryCount: { color: 'rgba(255,255,255,0.84)', fontSize: 11, lineHeight: 15, fontWeight: '800' },
  discoveryRecommendedCard: { width: 254, minHeight: 112, flexDirection: 'row', overflow: 'hidden', borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5E0D5', shadowColor: '#173524', shadowOpacity: 0.06, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  discoveryRecommendedImage: { width: 94, alignSelf: 'stretch' },
  discoveryRecommendedCopy: { flex: 1, minWidth: 0, justifyContent: 'center', gap: 4, padding: 13 },
  discoveryRecommendedKicker: { color: '#176A3A', fontSize: 9, lineHeight: 13, letterSpacing: 0.7, textTransform: 'uppercase', fontWeight: '900' },
  discoveryRecommendedTitle: { color: colors.text, fontSize: 16, lineHeight: 21, fontWeight: '900' },
  discoveryRecommendedMeta: { color: colors.muted, fontSize: 11, lineHeight: 16, fontWeight: '800' },
  discoveryStageCard: { width: 276, height: 184, borderRadius: 18, overflow: 'hidden', backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line },
  discoveryStageCardCompact: { width: 210, height: 148, borderRadius: 17, overflow: 'hidden', backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line },
  discoveryStageImage: { width: '100%', height: '100%' },
  discoveryStageTone: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(7,35,20,0.42)' },
  discoveryStageCopy: { position: 'absolute', left: 15, right: 15, top: 14, bottom: 13, justifyContent: 'flex-end', gap: 3 },
  discoveryStageTitle: { color: colors.white, fontSize: 21, lineHeight: 26, fontWeight: '900', textShadowColor: 'rgba(0,0,0,0.45)', textShadowRadius: 4, textShadowOffset: { width: 0, height: 1 } },
  discoveryStageAge: { color: '#F7D88D', fontSize: 11, lineHeight: 15, fontWeight: '900' },
  discoveryStageDescription: { color: 'rgba(255,255,255,0.86)', fontSize: 12, lineHeight: 17 },
  discoveryStageCount: { color: colors.white, fontSize: 11, lineHeight: 15, fontWeight: '900', marginTop: 2 },
  discoveryLibraryIntro: { gap: 5, paddingTop: 6 },
  lessonBrowseHero: { gap: 7 },
  lessonBrowseBack: { alignSelf: 'flex-start', minHeight: 44, justifyContent: 'center', paddingHorizontal: 4, paddingRight: 16, marginBottom: 3 },
  lessonBrowseBackText: { color: colors.green, fontSize: 16, lineHeight: 22, fontWeight: '900' },

  // ---- Get Ready (lesson summary) image ----
  getReadyImageCard: { alignSelf: 'center', width: '76%' },

  // ---- Before You Begin ----
  bybSection: { gap: 7 },
  bybEasierCard: { borderRadius: 12, backgroundColor: colors.mint, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 10 },
  bybEasierIcon: { width: 20, color: colors.green, fontSize: 15, lineHeight: 21, fontWeight: '900', textAlign: 'center' },

  // ---- Active session (single-screen) ----
  activeColumn: { flex: 1, gap: 10 },
  activeTimerHeader: { maxHeight: 104, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: 12, backgroundColor: '#0B2545', paddingHorizontal: 16, paddingVertical: 12, gap: 12 },
  activeTimerLabel: { color: '#F0D6A6', fontSize: 9, lineHeight: 13, letterSpacing: 1, fontWeight: '900' },
  activeTimerValue: { color: colors.white, fontSize: 26, lineHeight: 30, fontWeight: '900', fontVariant: ['tabular-nums'] },
  activeTimerButton: { minWidth: 84, minHeight: 44, borderRadius: 9, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  activeTimerButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '900' },
  activeSteps: { flex: 1, justifyContent: 'center' },
  activeStepRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, paddingVertical: 7, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line },
  activeStepRowLast: { borderBottomWidth: 0 },
  activeStepNumber: { width: 26, height: 26, borderRadius: 13, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', marginTop: 1 },
  activeStepNumberText: { color: '#FFFFFF', fontSize: 13, lineHeight: 17, fontWeight: '900' },
  activeStepBody: { flex: 1, gap: 1 },
  activeStepHeading: { color: colors.text, fontSize: 17, lineHeight: 21, fontWeight: '900' },
  activeStepText: { color: colors.text, fontSize: 15, lineHeight: 20 },
  activeCounterRow: { flexDirection: 'row', gap: 10 },
  activeCounterSuccess: { flex: 1, minHeight: 56, borderRadius: 9, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', paddingVertical: 6, gap: 1 },
  activeCounterTryAgain: { flex: 1, minHeight: 56, borderRadius: 9, backgroundColor: 'transparent', borderWidth: 1.5, borderColor: colors.green, alignItems: 'center', justifyContent: 'center', paddingVertical: 6, gap: 1 },
  activeCounterLabelOnDark: { color: '#D8EBDD', fontSize: 11, lineHeight: 14, letterSpacing: 0.8, fontWeight: '900' },
  activeCounterLabelLight: { color: '#1D6337', fontSize: 11, lineHeight: 14, letterSpacing: 0.8, fontWeight: '900' },
  activeCounterValueOnDark: { color: colors.white, fontSize: 24, lineHeight: 28, fontWeight: '900' },
  activeCounterValueLight: { color: colors.text, fontSize: 24, lineHeight: 28, fontWeight: '900' },
  activeUndo: { alignSelf: 'center', minHeight: 40, justifyContent: 'center', paddingHorizontal: 18 },
  activeUndoText: { color: colors.green, fontSize: 14, fontWeight: '800' },
  activeUndoTextDisabled: { color: colors.muted, opacity: 0.5 },
  activeResetHint: { flexDirection: 'row', alignItems: 'center', gap: 10, borderRadius: 10, backgroundColor: '#FFF4DF', borderWidth: 1, borderColor: '#ECD4A8', paddingHorizontal: 12, paddingVertical: 8 },
  activeResetHintText: { flex: 1, color: '#704C11', fontSize: 13, lineHeight: 18, fontWeight: '700' },
  activeResetHintButton: { minHeight: 40, borderRadius: 9, backgroundColor: colors.green, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  activeResetHintButtonText: { color: colors.forest, fontSize: 13, fontWeight: '900' },

  // ---- Lesson scaffold (stable content + pinned bottom actions) ----
  lessonScaffoldSafe: { flex: 1, backgroundColor: colors.background },
  lessonScaffoldScroll: { padding: 18, paddingBottom: 12, gap: 14 },
  lessonScaffoldFixed: { flex: 1, paddingHorizontal: 16, paddingTop: 10, paddingBottom: 6 },
  lessonScaffoldFooter: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: 6, borderTopWidth: 1, borderTopColor: colors.line, backgroundColor: colors.background },
  lessonActionRow: { flexDirection: 'row', gap: 12, alignItems: 'stretch' },
  lessonActionButton: { minHeight: 56, borderRadius: 9, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, borderWidth: 1.5, borderColor: colors.green, backgroundColor: colors.card },
  lessonActionBack: { flex: 1 },
  lessonActionForward: { flex: 2, backgroundColor: colors.green, shadowColor: colors.forest, shadowOpacity: 0.16, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 5 },
  lessonActionText: { color: colors.green, fontSize: 14, fontWeight: '900', letterSpacing: 0.2, textAlign: 'center' },
  lessonActionForwardText: { color: colors.white },
  lessonActionPressed: { opacity: 0.85, transform: [{ scale: 0.99 }] },
  lessonActionDisabled: { opacity: 0.5 },

  // ---- Journey roadmap ----
  journeyIntro: { color: colors.muted, fontSize: 15, lineHeight: 22 },
  journeyProgressText: { color: colors.text, fontSize: 15, lineHeight: 22, fontWeight: '900' },
  journeyGroup: { gap: 2, marginTop: 18 },
  journeyGroupTitle: { color: colors.green, fontSize: 12, lineHeight: 16, letterSpacing: 0.8, textTransform: 'uppercase', fontWeight: '900', marginBottom: 4 },
  journeyNode: { flexDirection: 'row', gap: 12 },
  journeyRail: { width: 30, alignItems: 'center' },
  journeyMarker: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', borderWidth: 2, backgroundColor: colors.card },
  journeyMarkerCompleted: { backgroundColor: colors.green, borderColor: colors.green },
  journeyMarkerCurrent: { backgroundColor: colors.green, borderColor: '#ECD4A8' },
  journeyMarkerUpcoming: { backgroundColor: colors.card, borderColor: colors.line },
  journeyMarkerText: { fontSize: 13, lineHeight: 17, fontWeight: '900' },
  journeyMarkerTextCompleted: { color: colors.white },
  journeyMarkerTextCurrent: { color: colors.forest },
  journeyMarkerTextUpcoming: { color: colors.muted },
  journeyConnector: { flex: 1, width: 2, minHeight: 14, backgroundColor: colors.line, marginVertical: 2 },
  journeyCard: { flex: 1, borderRadius: 10, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.card, paddingHorizontal: 14, paddingVertical: 12, marginBottom: 12, gap: 3 },
  journeyCardCurrent: { borderColor: '#ECD4A8', borderWidth: 2, backgroundColor: '#FFF8E8' },
  journeyCardUpcoming: { opacity: 0.7 },
  journeyCardTitle: { color: colors.text, fontSize: 16, lineHeight: 21, fontWeight: '900' },
  journeyCardMeta: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  journeyCardStateText: { fontSize: 11, lineHeight: 15, fontWeight: '900', letterSpacing: 0.4 },
});
