import { StatusBar as RNStatusBar, StyleSheet } from 'react-native';

import { colors } from './colors';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background, paddingTop: RNStatusBar.currentHeight ?? 0 },
  app: { flex: 1 },
  content: { padding: 18, paddingBottom: 110, gap: 16 },
  hero: { borderRadius: 28, backgroundColor: colors.forest, padding: 22, gap: 13 },
  eyebrow: { color: colors.gold, fontSize: 10, letterSpacing: 1.7, fontWeight: '900' },
  eyebrowDark: { color: colors.gold, fontSize: 10, letterSpacing: 1.7, fontWeight: '900' },
  heroTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  heroDogName: { color: colors.white, fontSize: 18, fontWeight: '800', marginTop: 4 },
  ownerBadge: { borderRadius: 999, borderWidth: 1, borderColor: 'rgba(212,175,55,0.5)', backgroundColor: 'rgba(212,175,55,0.16)', paddingHorizontal: 11, paddingVertical: 7 },
  ownerBadgeText: { color: colors.gold, fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  heroTitle: { color: colors.white, fontSize: 29, lineHeight: 35, letterSpacing: -0.6, fontWeight: '900' },
  heroBody: { color: 'rgba(255,255,255,0.73)', fontSize: 15, lineHeight: 22 },
  metricRow: { flexDirection: 'row', gap: 9 },
  metric: { flex: 1, borderRadius: 17, padding: 12, backgroundColor: 'rgba(255,255,255,0.09)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)' },
  metricValue: { color: colors.white, fontSize: 23, fontWeight: '900' },
  metricLabel: { color: 'rgba(255,255,255,0.65)', fontSize: 11, fontWeight: '700', marginTop: 3 },
  todayPlanSectionHeader: { gap: 5 },
  todayPlanSectionIntro: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  todayPlanLessonCard: { minHeight: 48, borderRadius: 22, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 18, gap: 10 },
  todayPlanLessonTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  todayPlanLessonVisualRow: { flexDirection: 'row', gap: 14, alignItems: 'center' },
  todayPlanLessonCopy: { flex: 1, gap: 4 },
  todayPlanSkillLabel: { flex: 1, color: colors.green, fontSize: 10, lineHeight: 15, letterSpacing: 0.8, textTransform: 'uppercase', fontWeight: '900' },
  todayPlanStatusBadge: { flexShrink: 0, borderRadius: 999, backgroundColor: '#241E10', borderWidth: 1, borderColor: colors.gold, paddingHorizontal: 10, paddingVertical: 6 },
  todayPlanStatusBadgeCompleted: { backgroundColor: colors.mint, borderColor: colors.green },
  todayPlanStatusBadgeUnavailable: { backgroundColor: '#241514', borderColor: '#5A3A38' },
  todayPlanStatusText: { color: colors.text, fontSize: 10, lineHeight: 14, fontWeight: '900' },
  todayPlanLessonTitle: { color: colors.text, fontSize: 22, lineHeight: 28, fontWeight: '900' },
  todayPlanLessonDescription: { color: colors.text, fontSize: 14, lineHeight: 21 },
  todayPlanLessonMetadata: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  todayPlanUnavailableNotice: { minHeight: 48, justifyContent: 'center', borderRadius: 14, backgroundColor: '#241514', borderWidth: 1, borderColor: '#5A3A38', paddingHorizontal: 14, paddingVertical: 10 },
  todayPlanUnavailableText: { color: '#E39B95', fontSize: 13, lineHeight: 19, fontWeight: '800' },
  todayPlanClosedNotice: { minHeight: 48, justifyContent: 'center', borderRadius: 14, backgroundColor: colors.mint, borderWidth: 1, borderColor: '#2A2A2A', paddingHorizontal: 14, paddingVertical: 10 },
  todayPlanClosedText: { color: colors.green, fontSize: 13, lineHeight: 19, fontWeight: '800' },
  todayPlanStaleCard: { borderRadius: 18, backgroundColor: '#241E10', borderWidth: 1, borderColor: colors.gold, padding: 16, gap: 5 },
  todayPlanStaleTitle: { color: '#E4C27A', fontSize: 17, lineHeight: 23, fontWeight: '900' },
  todayPlanStaleText: { color: colors.text, fontSize: 14, lineHeight: 21 },
  todayPlanEmptyCard: { borderRadius: 20, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 20, gap: 8 },
  pageTitle: { color: colors.text, fontSize: 32, lineHeight: 38, letterSpacing: -0.7, fontWeight: '900' },
  card: { backgroundColor: colors.card, borderRadius: 22, padding: 18, gap: 11, borderWidth: 1, borderColor: colors.line },
  sectionTitle: { color: colors.text, fontSize: 21, fontWeight: '900' },
  body: { color: colors.text, fontSize: 16, lineHeight: 23 },
  label: { color: colors.text, fontSize: 14, fontWeight: '800' },
  input: { borderWidth: 1, borderColor: colors.line, borderRadius: 15, backgroundColor: '#161616', paddingHorizontal: 14, paddingVertical: 14, fontSize: 16, color: colors.text },
  lessonTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  coursePill: { borderRadius: 999, backgroundColor: colors.mint, paddingHorizontal: 10, paddingVertical: 6 },
  coursePillText: { color: colors.green, fontSize: 10, fontWeight: '900', letterSpacing: 0.8 },
  duration: { color: colors.muted, fontSize: 11, fontWeight: '900', letterSpacing: 0.7 },
  lessonTitle: { color: colors.text, fontSize: 22, fontWeight: '900' },
  libraryListContent: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 110 },
  libraryHeader: { gap: 14 },
  libraryDogContext: { color: colors.muted, fontSize: 15, lineHeight: 22 },
  libraryDogName: { color: colors.text, fontWeight: '900' },
  librarySearchField: { minHeight: 54, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.line, borderRadius: 16, backgroundColor: colors.card, overflow: 'hidden' },
  librarySearchInput: { flex: 1, minWidth: 0, minHeight: 52, paddingHorizontal: 15, paddingVertical: 12, color: colors.text, fontSize: 16 },
  librarySearchClear: { minWidth: 58, minHeight: 52, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  librarySearchClearText: { color: colors.green, fontSize: 13, fontWeight: '900' },
  libraryFilterToolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  libraryFilterToggle: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 14, borderWidth: 1, borderColor: colors.green, borderRadius: 14, paddingHorizontal: 15, paddingVertical: 10 },
  libraryFilterToggleText: { color: colors.green, fontSize: 15, fontWeight: '900' },
  libraryFilterArrow: { color: colors.green, fontSize: 20, lineHeight: 22, fontWeight: '900' },
  libraryClearFiltersButton: { minHeight: 48, justifyContent: 'center', paddingHorizontal: 8 },
  libraryClearFiltersText: { color: colors.green, fontSize: 13, fontWeight: '900' },
  libraryActiveFilters: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  libraryActiveFilterText: { color: colors.green, backgroundColor: colors.mint, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, fontSize: 11, fontWeight: '900' },
  libraryFilterPanel: { borderRadius: 18, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 16 },
  libraryFilterGroup: { gap: 8 },
  libraryFilterChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  libraryFilterChip: { minHeight: 44, justifyContent: 'center', borderRadius: 999, borderWidth: 1, borderColor: colors.line, backgroundColor: '#161616', paddingHorizontal: 12, paddingVertical: 8 },
  libraryFilterChipSelected: { borderColor: colors.green, backgroundColor: colors.green },
  libraryFilterChipText: { color: colors.text, fontSize: 13, fontWeight: '800' },
  libraryFilterChipTextSelected: { color: colors.white },
  libraryResultCount: { color: colors.muted, fontSize: 13, lineHeight: 18, fontWeight: '800' },
  librarySectionHeader: { marginTop: 22, marginBottom: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  librarySectionTitle: { flex: 1, color: colors.text, fontSize: 22, lineHeight: 28, fontWeight: '900' },
  librarySectionCount: { minWidth: 32, borderRadius: 999, backgroundColor: colors.mint, color: colors.green, textAlign: 'center', paddingHorizontal: 9, paddingVertical: 5, fontSize: 12, fontWeight: '900' },
  libraryCardSpacing: { marginBottom: 12 },
  libraryLessonCard: { minHeight: 48, borderRadius: 20, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 17, gap: 9 },
  libraryLessonVisualRow: { flexDirection: 'row', gap: 14, alignItems: 'center' },
  libraryLessonCopy: { flex: 1, gap: 4 },
  libraryLessonTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  librarySkillLabel: { flex: 1, color: colors.green, fontSize: 10, lineHeight: 15, letterSpacing: 0.8, textTransform: 'uppercase', fontWeight: '900' },
  libraryStateBadge: { flexShrink: 0, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: colors.line },
  libraryStateAvailable: { backgroundColor: '#242424', borderColor: '#2A2A2A' },
  libraryStateLocked: { backgroundColor: '#1E1E1E', borderColor: '#2A2A2A' },
  libraryStateInProgress: { backgroundColor: '#241E10', borderColor: colors.gold },
  libraryStateCompleted: { backgroundColor: colors.mint, borderColor: colors.green },
  libraryStateText: { color: colors.text, fontSize: 10, lineHeight: 14, fontWeight: '900' },
  libraryLessonTitle: { color: colors.text, fontSize: 20, lineHeight: 26, fontWeight: '900' },
  libraryLessonDescription: { color: colors.text, fontSize: 14, lineHeight: 21 },
  libraryMetadataRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 7 },
  libraryMetadataText: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  libraryMetadataDot: { color: colors.gold, fontSize: 13, lineHeight: 17, fontWeight: '900' },
  libraryLockNotice: { borderRadius: 13, backgroundColor: '#241E10', padding: 11, gap: 3 },
  libraryLockLabel: { color: '#E4C27A', fontSize: 9, lineHeight: 13, letterSpacing: 0.8, fontWeight: '900' },
  libraryLockText: { color: colors.text, fontSize: 13, lineHeight: 19 },
  libraryCardAction: { color: colors.green, fontSize: 13, lineHeight: 18, fontWeight: '900' },
  libraryNoResultsCard: { marginTop: 22, borderRadius: 20, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 18, gap: 9 },
  libraryEmptyCard: { borderRadius: 20, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 20, gap: 8 },
  librarySummaryHero: { borderRadius: 22, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 19, gap: 11 },
  librarySummaryLockCard: { borderRadius: 18, backgroundColor: '#241E10', borderWidth: 1, borderColor: colors.gold, padding: 16, gap: 6 },
  librarySummaryLockReason: { color: colors.text, fontSize: 17, lineHeight: 24, fontWeight: '900' },
  librarySummarySupportText: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  librarySummaryNotice: { borderRadius: 18, backgroundColor: colors.mint, borderWidth: 1, borderColor: '#2A2A2A', padding: 16, gap: 5 },
  librarySummaryNoticeTitle: { color: colors.green, fontSize: 16, lineHeight: 21, fontWeight: '900' },
  lessonDetails: { gap: 14, paddingTop: 4 },
  coachingGoalCard: { borderRadius: 17, backgroundColor: colors.mint, borderWidth: 1, borderColor: '#2A2A2A', padding: 15, gap: 6 },
  coachingKicker: { color: colors.green, fontSize: 10, lineHeight: 14, letterSpacing: 1.1, fontWeight: '900' },
  lessonGoal: { color: colors.text, fontSize: 16, lineHeight: 23, fontWeight: '800' },
  coachingMeta: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  coachingSectionTitle: { color: colors.text, fontSize: 18, lineHeight: 24, fontWeight: '900' },
  coachingSectionIntro: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 3 },
  lessonIllustrationSection: { gap: 8 },
  lessonIllustrationCard: { borderRadius: 18, overflow: 'hidden', backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line },
  lessonIllustrationFrame: { width: '100%', aspectRatio: 3 / 2, backgroundColor: '#F7F4EE', overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
  lessonIllustration: { width: '100%', height: '100%' },
  illustrationCopy: { padding: 14, gap: 5 },
  illustrationLabel: { color: colors.green, fontSize: 9, lineHeight: 13, letterSpacing: 1, fontWeight: '900' },
  illustrationText: { color: colors.text, fontSize: 14, lineHeight: 21 },
  illustrationProblem: { marginTop: 7, borderRadius: 12, backgroundColor: '#241E10', padding: 11, gap: 3 },
  illustrationProblemLabel: { color: '#E4C27A', fontSize: 9, lineHeight: 13, letterSpacing: 0.8, fontWeight: '900' },
  illustrationProblemText: { color: colors.text, fontSize: 13, lineHeight: 19 },
  lessonDiagram: { borderRadius: 17, backgroundColor: '#1E1E1E', borderWidth: 1, borderColor: colors.line, padding: 12, gap: 4 },
  diagramStageGroup: { alignItems: 'stretch' },
  diagramStage: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 8 },
  diagramNumber: { width: 26, height: 26, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.green },
  diagramNumberText: { color: colors.white, fontSize: 12, lineHeight: 16, fontWeight: '900' },
  diagramCopy: { flex: 1, gap: 3 },
  diagramTitle: { color: colors.green, fontSize: 14, lineHeight: 19, fontWeight: '900' },
  diagramText: { color: colors.text, fontSize: 12, lineHeight: 18 },
  diagramArrow: { color: colors.gold, fontSize: 20, lineHeight: 20, textAlign: 'center', fontWeight: '900' },
  coachingListCard: { borderRadius: 17, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14, gap: 10 },
  coachingListRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  coachingBullet: { width: 20, color: colors.green, fontSize: 16, lineHeight: 21, fontWeight: '900', textAlign: 'center' },
  coachingTipIcon: { width: 20, color: '#E4C27A', fontSize: 15, lineHeight: 21, fontWeight: '900', textAlign: 'center' },
  coachingWarningIcon: { width: 20, height: 20, borderRadius: 10, color: '#E4C27A', backgroundColor: '#4A3D1C', fontSize: 12, lineHeight: 20, fontWeight: '900', textAlign: 'center' },
  coachingListText: { flex: 1, color: colors.text, fontSize: 14, lineHeight: 21 },
  lessonSteps: { gap: 10 },
  lessonStep: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, borderRadius: 16, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 14 },
  lessonStepNumber: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.green },
  lessonStepNumberText: { color: colors.white, fontSize: 13, lineHeight: 17, fontWeight: '900' },
  lessonStepText: { flex: 1, color: colors.text, fontSize: 14, lineHeight: 21 },
  coachingCheckIn: { borderRadius: 17, backgroundColor: '#141C24', borderWidth: 1, borderColor: '#2A3A48', padding: 14, gap: 5 },
  coachingCheckInTitle: { color: '#8FC0E0', fontSize: 10, lineHeight: 14, letterSpacing: 0.9, fontWeight: '900' },
  coachingCheckInText: { color: colors.text, fontSize: 14, lineHeight: 21 },
  coachingPreventionCard: { borderRadius: 17, backgroundColor: '#241E10', borderWidth: 1, borderColor: '#4A3D1C', padding: 14, gap: 10 },
  troubleshootingList: { gap: 9, marginTop: 8 },
  troubleshootingCard: { borderRadius: 15, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 13, gap: 5 },
  troubleshootingProblem: { color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: '900' },
  troubleshootingSolution: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  safetyTitle: { color: '#E39B95', fontSize: 16, lineHeight: 22, fontWeight: '900' },
  safetyText: { color: colors.text, fontSize: 13, lineHeight: 20 },
  completionCard: { borderRadius: 17, backgroundColor: '#1E1E1E', borderWidth: 1, borderColor: colors.gold, padding: 15, gap: 5 },
  completionTitle: { color: colors.text, fontSize: 16, lineHeight: 22, fontWeight: '900' },
  completionText: { color: colors.text, fontSize: 14, lineHeight: 21 },
  completionMeta: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  encouragementCard: { borderRadius: 17, backgroundColor: colors.forest, padding: 16, gap: 6 },
  encouragementTitle: { color: colors.gold, fontSize: 10, lineHeight: 14, letterSpacing: 1, fontWeight: '900' },
  encouragementText: { color: colors.white, fontSize: 14, lineHeight: 21, fontWeight: '700' },
  guidedCompleteCard: { borderRadius: 24, backgroundColor: colors.forest, padding: 22, gap: 8, alignItems: 'center' },
  guidedCompleteMark: { width: 54, height: 54, borderRadius: 27, backgroundColor: colors.gold, color: colors.forest, fontSize: 28, lineHeight: 54, fontWeight: '900', textAlign: 'center' },
  guidedCompleteKicker: { color: colors.gold, fontSize: 10, lineHeight: 14, letterSpacing: 1.2, fontWeight: '900' },
  guidedCompleteTitle: { color: colors.white, fontSize: 27, lineHeight: 33, fontWeight: '900', textAlign: 'center' },
  guidedCompleteBody: { color: 'rgba(255,255,255,0.78)', fontSize: 15, lineHeight: 22, textAlign: 'center' },
  sessionSnapshotCard: { borderRadius: 18, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 16, gap: 11 },
  sessionSnapshotTitle: { color: colors.text, fontSize: 17, lineHeight: 23, fontWeight: '900' },
  sessionSnapshotRow: { flexDirection: 'row', gap: 8 },
  sessionSnapshotMetric: { flex: 1, minWidth: 0, borderRadius: 13, backgroundColor: colors.mint, padding: 10, alignItems: 'center', gap: 3 },
  sessionSnapshotValue: { color: colors.green, fontSize: 21, lineHeight: 27, fontWeight: '900' },
  sessionSnapshotLabel: { color: colors.muted, fontSize: 10, lineHeight: 14, fontWeight: '800', textAlign: 'center' },
  sessionRatingStack: { gap: 9 },
  sessionRatingButton: { minHeight: 64, borderRadius: 16, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 13, justifyContent: 'center' },
  sessionRatingButtonSelected: { borderColor: colors.green, borderWidth: 2, backgroundColor: colors.mint },
  sessionRatingTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  sessionRatingValue: { width: 30, height: 30, borderRadius: 15, backgroundColor: colors.green, color: colors.white, fontSize: 14, lineHeight: 30, fontWeight: '900', textAlign: 'center' },
  sessionRatingCopy: { flex: 1, minWidth: 0, gap: 2 },
  sessionRatingTitle: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: '900' },
  sessionRatingDescription: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  sessionRatingSuggested: { flexShrink: 0, color: '#E4C27A', backgroundColor: '#2A2410', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 5, fontSize: 8, lineHeight: 11, letterSpacing: 0.6, fontWeight: '900' },
  sessionTimerCard: { borderRadius: 18, backgroundColor: colors.forest, padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 14 },
  sessionTimerLabel: { color: colors.gold, fontSize: 9, lineHeight: 13, letterSpacing: 1, fontWeight: '900' },
  sessionTimer: { color: colors.white, fontSize: 31, lineHeight: 37, fontWeight: '900', fontVariant: ['tabular-nums'] },
  timerButton: { minWidth: 86, minHeight: 48, borderRadius: 14, backgroundColor: colors.gold, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 },
  timerButtonText: { color: colors.forest, fontSize: 14, fontWeight: '900' },
  sessionStepCard: { borderRadius: 20, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 18, gap: 7 },
  sessionStepKicker: { color: colors.green, fontSize: 10, lineHeight: 14, letterSpacing: 1, fontWeight: '900' },
  sessionStepText: { color: colors.text, fontSize: 20, lineHeight: 28, fontWeight: '900' },
  sessionCoachCard: { borderRadius: 17, backgroundColor: colors.mint, borderWidth: 1, borderColor: '#2A2A2A', padding: 15, gap: 5 },
  sessionCoachLabel: { color: colors.green, fontSize: 9, lineHeight: 13, letterSpacing: 0.9, fontWeight: '900' },
  sessionCoachBody: { color: colors.text, fontSize: 14, lineHeight: 21 },
  sessionCheckInCard: { borderRadius: 18, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 16, gap: 10 },
  sessionCheckInLabel: { color: '#8FC0E0', fontSize: 9, lineHeight: 13, letterSpacing: 0.9, fontWeight: '900' },
  sessionCheckInHeading: { color: colors.text, fontSize: 18, lineHeight: 24, fontWeight: '900' },
  sessionCountRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  sessionCountText: { color: colors.green, backgroundColor: colors.mint, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, fontSize: 11, lineHeight: 15, fontWeight: '900' },
  sessionResetCard: { borderRadius: 15, backgroundColor: '#241E10', borderWidth: 1, borderColor: '#4A3D1C', padding: 13, gap: 8 },
  sessionResetTitle: { color: '#E4C27A', fontSize: 16, lineHeight: 21, fontWeight: '900' },
  sessionResetText: { color: colors.text, fontSize: 13, lineHeight: 19 },
  sessionActionRow: { flexDirection: 'row', gap: 9 },
  sessionWinButton: { flex: 1, minHeight: 50, borderRadius: 14, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  sessionWinButtonText: { color: colors.white, fontSize: 13, fontWeight: '900', textAlign: 'center' },
  sessionHelpButton: { flex: 1, minHeight: 50, borderRadius: 14, backgroundColor: '#241E10', borderWidth: 1, borderColor: '#4A3D1C', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  sessionHelpButtonText: { color: '#E4C27A', fontSize: 13, fontWeight: '900', textAlign: 'center' },
  sessionTroubleCard: { borderRadius: 17, backgroundColor: '#1E1E1E', borderWidth: 1, borderColor: colors.line, padding: 15, gap: 5 },
  sessionTroubleLabel: { color: '#E4C27A', fontSize: 9, lineHeight: 13, letterSpacing: 0.8, fontWeight: '900' },
  sessionOutlineButton: { flex: 1, minHeight: 48, borderRadius: 14, borderWidth: 1, borderColor: colors.green, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  sessionOutlineButtonText: { color: colors.green, fontSize: 14, fontWeight: '900' },
  sessionExitNote: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  sessionPromiseCard: { borderRadius: 17, backgroundColor: '#141C24', borderWidth: 1, borderColor: '#2A3A48', padding: 15, gap: 5 },
  sessionPromiseTitle: { color: '#8FC0E0', fontSize: 16, lineHeight: 21, fontWeight: '900' },
  sessionPromiseText: { color: colors.text, fontSize: 13, lineHeight: 20 },
  primaryButton: { minHeight: 52, borderRadius: 15, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
  primaryButtonText: { color: colors.white, fontSize: 16, fontWeight: '900' },
  pressed: { opacity: 0.82 },
  disabled: { opacity: 0.45 },
  fieldGroup: { gap: 7 },
  inputError: { borderColor: '#E39B95', borderWidth: 2 },
  validationText: { color: '#E39B95', fontSize: 13, lineHeight: 18, fontWeight: '700' },
  chipGroup: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  selectionChip: { minHeight: 48, justifyContent: 'center', borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.card, paddingHorizontal: 14, paddingVertical: 10 },
  selectionChipActive: { borderColor: colors.green, backgroundColor: colors.mint },
  selectionChipText: { color: colors.text, fontSize: 15, fontWeight: '700' },
  selectionChipTextActive: { color: colors.green, fontWeight: '900' },
  onboardingProgress: { gap: 8 },
  progressStep: { color: colors.muted, fontSize: 11, letterSpacing: 1.2, fontWeight: '900' },
  onboardingProgressTrack: { height: 7, borderRadius: 999, backgroundColor: colors.line, overflow: 'hidden' },
  onboardingProgressFill: { height: '100%', borderRadius: 999, backgroundColor: colors.gold },
  secondaryTextButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  secondaryText: { color: colors.green, fontSize: 15, fontWeight: '900' },
  centerState: { flex: 1, minHeight: 320, alignItems: 'center', justifyContent: 'center', gap: 16, padding: 24 },
  errorCard: { backgroundColor: '#241514', borderColor: '#5A3A38', borderWidth: 1, borderRadius: 18, padding: 18, gap: 12 },
  welcomeMark: { width: 64, height: 64, borderRadius: 22, backgroundColor: colors.gold, alignItems: 'center', justifyContent: 'center' },
  welcomeMarkText: { color: colors.forest, fontSize: 25, fontWeight: '900' },
  onboardingTitle: { color: colors.text, fontSize: 32, lineHeight: 38, letterSpacing: -0.7, fontWeight: '900' },
  onboardingBody: { color: colors.muted, fontSize: 16, lineHeight: 24 },
  photoPreview: { width: 96, height: 96, borderRadius: 48, backgroundColor: colors.mint },
  photoActionRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  dateSelection: { minHeight: 52, justifyContent: 'center', borderWidth: 1, borderColor: colors.line, borderRadius: 15, backgroundColor: '#161616', paddingHorizontal: 14, paddingVertical: 12 },
  dateSelectionText: { color: colors.text, fontSize: 16, fontWeight: '700' },
  dateSelectionPlaceholder: { color: '#8A8A8A', fontSize: 16 },
  developerToolsCard: { backgroundColor: '#241E10', borderRadius: 22, padding: 18, gap: 11, borderWidth: 1, borderColor: colors.gold },
  assessmentQuestion: { backgroundColor: colors.card, borderRadius: 22, padding: 18, gap: 12, borderWidth: 1, borderColor: colors.line },
  assessmentOptions: { gap: 8 },
  assessmentOption: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderColor: colors.line, borderRadius: 15, backgroundColor: '#161616', paddingHorizontal: 14, paddingVertical: 10 },
  assessmentOptionSelected: { borderColor: colors.green, backgroundColor: colors.mint, borderWidth: 2 },
  radioOuter: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: colors.muted, alignItems: 'center', justifyContent: 'center' },
  radioSelected: { borderColor: colors.green },
  radioInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.green },
  optionText: { flex: 1, color: colors.text, fontSize: 15, fontWeight: '700' },
  safetyCard: { backgroundColor: '#241514', borderColor: '#5A3A38', borderWidth: 1, borderRadius: 18, padding: 18, gap: 8 },
  scoreRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', minHeight: 48, borderBottomWidth: 1, borderBottomColor: colors.line },
  scoreValue: { color: colors.green, fontSize: 18, fontWeight: '900' },
  completedBadge: { minHeight: 48, borderRadius: 15, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center' },
  completedBadgeText: { color: colors.green, fontSize: 15, fontWeight: '900' },
  progressHero: { borderRadius: 28, backgroundColor: colors.forest, padding: 22, gap: 11 },
  progressValue: { color: colors.white, fontSize: 58, fontWeight: '900', letterSpacing: -1.5 },
  progressLabel: { color: 'rgba(255,255,255,0.73)', fontSize: 15, fontWeight: '700' },
  progressTrack: { height: 10, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.12)', overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 999, backgroundColor: colors.gold },
  progressHistoryCard: { borderRadius: 22, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 18, gap: 11 },
  progressRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: colors.line },
  completeText: { color: colors.green, fontWeight: '900' },
  notStartedText: { color: colors.muted, fontWeight: '700' },
  historyListContent: { flexGrow: 1, paddingHorizontal: 18, paddingTop: 18, paddingBottom: 110 },
  historyHeader: { gap: 10, marginBottom: 20 },
  historyDogContext: { color: colors.muted, fontSize: 15, lineHeight: 22 },
  historyStateScreen: { flex: 1, padding: 18, gap: 14 },
  historyCardSpacing: { marginBottom: 12 },
  historySessionCard: { minHeight: 48, borderRadius: 20, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 17, gap: 9 },
  historyCardTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  historySkillLabel: { flex: 1, color: colors.green, fontSize: 10, lineHeight: 15, letterSpacing: 0.8, textTransform: 'uppercase', fontWeight: '900' },
  historyOutcomeBadge: { flexShrink: 0, borderRadius: 999, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 6 },
  historyOutcomeSuccess: { backgroundColor: colors.mint, borderColor: colors.green },
  historyOutcomePartial: { backgroundColor: '#241E10', borderColor: colors.gold },
  historyOutcomeUnsuccessful: { backgroundColor: '#241514', borderColor: '#5A3A38' },
  historyOutcomeText: { color: colors.text, fontSize: 10, lineHeight: 14, fontWeight: '900' },
  historySessionTitle: { color: colors.text, fontSize: 20, lineHeight: 26, fontWeight: '900' },
  historyMetadataRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 7 },
  historyMetadataText: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  historyMetadataDot: { color: colors.gold, fontSize: 13, lineHeight: 17, fontWeight: '900' },
  historyNotesPreview: { color: colors.text, fontSize: 13, lineHeight: 19 },
  historyCardAction: { color: colors.green, fontSize: 13, lineHeight: 18, fontWeight: '900' },
  historyEmptyCard: { marginTop: 12, borderRadius: 20, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 20, gap: 8 },
  historyListFooter: { paddingTop: 8, paddingBottom: 8 },
  historyMissingLessonNotice: { borderRadius: 18, backgroundColor: '#241E10', borderWidth: 1, borderColor: colors.gold, padding: 16, gap: 5 },
  historyMissingLessonTitle: { color: '#E4C27A', fontSize: 16, lineHeight: 22, fontWeight: '900' },
  historyDetailCard: { borderRadius: 20, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, padding: 18, gap: 12 },
  historyDetailRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16, borderBottomWidth: 1, borderBottomColor: colors.line, paddingVertical: 9 },
  historyDetailLabel: { flex: 1, color: colors.muted, fontSize: 13, lineHeight: 19, fontWeight: '800' },
  historyDetailValue: { flex: 1, color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: '900', textAlign: 'right' },
  historyDetailSupportingText: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  membershipCard: { borderRadius: 27, backgroundColor: colors.forest, padding: 21, gap: 8 },
  membershipEyebrow: { color: colors.gold, fontSize: 10, letterSpacing: 1.5, fontWeight: '900' },
  membershipTitle: { color: colors.white, fontSize: 25, fontWeight: '900' },
  membershipBody: { color: 'rgba(255,255,255,0.7)', fontSize: 14, lineHeight: 21 },
  profileValue: { color: colors.text, fontSize: 18, fontWeight: '900' },
  tabBar: { height: 82, backgroundColor: '#000000', flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#141414', paddingHorizontal: 6, paddingTop: 8, paddingBottom: 8, gap: 6 },
  tabButton: { flex: 1, minHeight: 52, marginTop: 4, borderRadius: 14, alignItems: 'center', justifyContent: 'center', gap: 5, backgroundColor: '#1B1B1B', borderWidth: 1, borderColor: '#222222' },
  tabButtonActive: { backgroundColor: '#242424', borderColor: 'rgba(212,175,55,0.35)' },
  tabDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#8F7A3E' },
  tabDotActive: { backgroundColor: '#D4AF37' },
  tabText: { color: '#8F7A3E', fontSize: 11, fontWeight: '800' },
  tabTextActive: { color: '#D4AF37' },

  // ---- Home (Today) cinematic screen ----
  homeRoot: { flex: 1, backgroundColor: '#000000' },
  homeSafe: { flex: 1 },
  homeBody: { flex: 1, width: '100%', alignItems: 'center', paddingHorizontal: 24 },
  homeHeroBlock: { alignItems: 'center', gap: 2 },
  homePhotoRing: { borderRadius: 999, borderWidth: 3, borderColor: '#D4AF37', padding: 4, backgroundColor: 'rgba(0,0,0,0.25)' },
  homeButtons: { width: '100%', alignItems: 'center', gap: 12 },
  // Both Home buttons share one dark-charcoal + gold-border + gold-text treatment.
  homeButton: { width: '80%', minHeight: 58, borderRadius: 999, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20, borderWidth: 1.5, borderColor: '#D4AF37', backgroundColor: '#181818' },
  homeButtonText: { color: '#D4AF37', fontSize: 18, fontWeight: '900', letterSpacing: 0.2 },
  // The primary action is distinguished only by a subtle gold glow, not colour.
  homeButtonPrimaryGlow: { shadowColor: '#D4AF37', shadowOpacity: 0.35, shadowRadius: 12, shadowOffset: { width: 0, height: 0 }, elevation: 6 },
  homeButtonPressed: { opacity: 0.85, transform: [{ scale: 0.99 }] },
  homeWelcome: { width: '100%', alignItems: 'center', gap: 6, paddingHorizontal: 6 },
  homeWelcomeTitle: { color: '#F5ECD6', fontSize: 22, lineHeight: 28, fontWeight: '800', textAlign: 'center' },
  homeWelcomeLine: { color: 'rgba(255,255,255,0.82)', fontSize: 14, lineHeight: 20, textAlign: 'center' },
  homeWelcomeReport: { color: '#D4AF37', fontSize: 13, lineHeight: 19, fontWeight: '700', textAlign: 'center' },

  // ---- Get Ready (lesson summary) image ----
  getReadyImageCard: { alignSelf: 'center', width: '76%' },

  // ---- Before You Begin ----
  bybSection: { gap: 7 },
  bybEasierCard: { borderRadius: 17, backgroundColor: colors.mint, borderWidth: 1, borderColor: '#2A2A2A', padding: 14, gap: 10 },
  bybEasierIcon: { width: 20, color: colors.green, fontSize: 15, lineHeight: 21, fontWeight: '900', textAlign: 'center' },

  // ---- Active session (single-screen) ----
  activeColumn: { flex: 1, gap: 10 },
  activeTimerHeader: { maxHeight: 104, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: 16, backgroundColor: colors.forest, paddingHorizontal: 16, paddingVertical: 12, gap: 12 },
  activeTimerLabel: { color: colors.gold, fontSize: 9, lineHeight: 13, letterSpacing: 1, fontWeight: '900' },
  activeTimerValue: { color: colors.white, fontSize: 26, lineHeight: 30, fontWeight: '900', fontVariant: ['tabular-nums'] },
  activeTimerButton: { minWidth: 84, minHeight: 44, borderRadius: 12, backgroundColor: colors.gold, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  activeTimerButtonText: { color: colors.forest, fontSize: 14, fontWeight: '900' },
  activeSteps: { flex: 1, justifyContent: 'center' },
  activeStepRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, paddingVertical: 7, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line },
  activeStepRowLast: { borderBottomWidth: 0 },
  activeStepNumber: { width: 26, height: 26, borderRadius: 13, backgroundColor: colors.gold, alignItems: 'center', justifyContent: 'center', marginTop: 1 },
  activeStepNumberText: { color: '#3A2C12', fontSize: 13, lineHeight: 17, fontWeight: '900' },
  activeStepBody: { flex: 1, gap: 1 },
  activeStepHeading: { color: colors.text, fontSize: 17, lineHeight: 21, fontWeight: '900' },
  activeStepText: { color: colors.text, fontSize: 15, lineHeight: 20 },
  activeCounterRow: { flexDirection: 'row', gap: 10 },
  activeCounterSuccess: { flex: 1, minHeight: 56, borderRadius: 14, backgroundColor: colors.forest, alignItems: 'center', justifyContent: 'center', paddingVertical: 6, gap: 1 },
  activeCounterTryAgain: { flex: 1, minHeight: 56, borderRadius: 14, backgroundColor: 'transparent', borderWidth: 1.5, borderColor: colors.gold, alignItems: 'center', justifyContent: 'center', paddingVertical: 6, gap: 1 },
  activeCounterLabelOnDark: { color: colors.gold, fontSize: 11, lineHeight: 14, letterSpacing: 0.8, fontWeight: '900' },
  activeCounterLabelLight: { color: '#E4C27A', fontSize: 11, lineHeight: 14, letterSpacing: 0.8, fontWeight: '900' },
  activeCounterValueOnDark: { color: colors.white, fontSize: 24, lineHeight: 28, fontWeight: '900' },
  activeCounterValueLight: { color: colors.text, fontSize: 24, lineHeight: 28, fontWeight: '900' },
  activeUndo: { alignSelf: 'center', minHeight: 40, justifyContent: 'center', paddingHorizontal: 18 },
  activeUndoText: { color: colors.green, fontSize: 14, fontWeight: '800' },
  activeUndoTextDisabled: { color: colors.muted, opacity: 0.5 },
  activeResetHint: { flexDirection: 'row', alignItems: 'center', gap: 10, borderRadius: 12, backgroundColor: '#241E10', borderWidth: 1, borderColor: '#4A3D1C', paddingHorizontal: 12, paddingVertical: 8 },
  activeResetHintText: { flex: 1, color: '#E4C27A', fontSize: 13, lineHeight: 18, fontWeight: '700' },
  activeResetHintButton: { minHeight: 40, borderRadius: 10, backgroundColor: colors.gold, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  activeResetHintButtonText: { color: colors.forest, fontSize: 13, fontWeight: '900' },

  // ---- Lesson scaffold (stable content + pinned bottom actions) ----
  lessonScaffoldSafe: { flex: 1, backgroundColor: colors.background },
  lessonScaffoldScroll: { padding: 18, paddingBottom: 12, gap: 14 },
  lessonScaffoldFixed: { flex: 1, paddingHorizontal: 16, paddingTop: 10, paddingBottom: 6 },
  lessonScaffoldFooter: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: 6, borderTopWidth: 1, borderTopColor: colors.line, backgroundColor: colors.background },
  lessonActionRow: { flexDirection: 'row', gap: 12, alignItems: 'stretch' },
  lessonActionButton: { minHeight: 56, borderRadius: 999, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, borderWidth: 1.5, borderColor: '#D4AF37', backgroundColor: '#181818' },
  lessonActionBack: { flex: 1 },
  lessonActionForward: { flex: 2, backgroundColor: '#202020', shadowColor: '#D4AF37', shadowOpacity: 0.3, shadowRadius: 10, shadowOffset: { width: 0, height: 0 }, elevation: 5 },
  lessonActionText: { color: '#D4AF37', fontSize: 16, fontWeight: '900', letterSpacing: 0.2, textAlign: 'center' },
  lessonActionPressed: { opacity: 0.85, transform: [{ scale: 0.99 }] },
  lessonActionDisabled: { opacity: 0.5 },

  // ---- Journey roadmap ----
  journeyIntro: { color: colors.muted, fontSize: 15, lineHeight: 22 },
  journeyProgressText: { color: colors.text, fontSize: 15, lineHeight: 22, fontWeight: '900' },
  journeyGroup: { gap: 2, marginTop: 18 },
  journeyGroupTitle: { color: colors.green, fontSize: 12, lineHeight: 16, letterSpacing: 0.8, textTransform: 'uppercase', fontWeight: '900', marginBottom: 4 },
  journeyNode: { flexDirection: 'row', gap: 12 },
  journeyRail: { width: 30, alignItems: 'center' },
  journeyMarker: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', borderWidth: 2, backgroundColor: colors.card },
  journeyMarkerCompleted: { backgroundColor: colors.gold, borderColor: colors.gold },
  journeyMarkerCurrent: { backgroundColor: '#242424', borderColor: colors.gold },
  journeyMarkerUpcoming: { backgroundColor: colors.card, borderColor: colors.line },
  journeyMarkerText: { fontSize: 13, lineHeight: 17, fontWeight: '900' },
  journeyMarkerTextCompleted: { color: '#3A2C12' },
  journeyMarkerTextCurrent: { color: colors.white },
  journeyMarkerTextUpcoming: { color: colors.muted },
  journeyConnector: { flex: 1, width: 2, minHeight: 14, backgroundColor: colors.line, marginVertical: 2 },
  journeyCard: { flex: 1, borderRadius: 16, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.card, paddingHorizontal: 14, paddingVertical: 12, marginBottom: 12, gap: 3 },
  journeyCardCurrent: { borderColor: colors.gold, borderWidth: 2, backgroundColor: '#242424' },
  journeyCardUpcoming: { opacity: 0.7 },
  journeyCardTitle: { color: colors.text, fontSize: 16, lineHeight: 21, fontWeight: '900' },
  journeyCardMeta: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  journeyCardStateText: { fontSize: 11, lineHeight: 15, fontWeight: '900', letterSpacing: 0.4 },
});
