import type { TroubleshooterTopicId } from '../../domain/models';
import type { TroubleshooterProtocol } from './troubleshooterTypes';

const protocols: readonly TroubleshooterProtocol[] = [
  protocol({
    id: 'recall-reset', topicId: 'recall', likelyObstacle: 'The recall is being asked for at a difficulty where the cue has little chance of succeeding.',
    explanation: ['Dogs do not automatically understand that a cue learned in a room also applies in a yard, park, or near wildlife.', 'Every ignored repetition can make the cue less useful. Safe management and easier successful repetitions protect the response while it grows.'],
    why: ['The selected situation points to distance, distraction, or incomplete generalisation.', 'A short successful return is more useful than testing the cue at full difficulty.'],
    primaryAdjustment: 'Shorten the distance and lower the distraction until one cue produces an immediate turn.',
    exercise: exercise('Quiet recall reset', '3–5 minutes', ['A quiet room, doorway, or securely enclosed yard', 'Five high-value rewards', 'A harness and long line if outdoors'], ['Start one or two metres away while your dog is only mildly occupied.', 'Say the name, then the recall cue once.', 'Move backwards as your dog turns; mark the turn immediately.', 'Reward generously close to your body, then release back to sniffing or exploring.'], 'Complete three to five successful returns and finish.'),
    difficultySigns: ['Cannot turn away from the environment', 'Stops halfway', 'Needs repeated cues'],
    successCriteria: ['Turns after one cue', 'Returns directly from the chosen distance', 'Succeeds at least four times out of five'],
    stopConditions: ['The long line or environment is unsafe', 'Your dog cannot eat or disengage', 'Fear, panic, or escalating frustration appears'],
    fallbackLevel2: ['Move to a quiet doorway or yard.', 'Use a secure long line and a higher-value reward.', 'Reward orientation before asking for the full return.'],
    fallbackLevel3: ['Pause use of a repeatedly ignored cue.', 'Rebuild with a fresh cue in an easy setting.', 'Seek qualified reward-based help before off-lead practice.'],
    professionalEscalation: 'Get professional help if recall failure creates escape, traffic, livestock, or wildlife risk.',
    relatedLessonIds: ['recall-short-distance', 'recall-around-distractions'],
  }),
  protocol({
    id: 'name-orientation-reset', topicId: 'name-response', likelyObstacle: 'The name may have become background noise, a predictor of something unpleasant, or dependent on visible food.',
    explanation: ['A name response is simply an orientation skill: hear the name once, then turn towards the person.', 'It should be trained separately from recall so the dog is not always required to leave something interesting after hearing their name.'],
    why: ['The answers suggest the first name cue is unclear or tied to an easy context.', 'Rebuilding one clean cue-response-reward sequence restores useful meaning.'],
    primaryAdjustment: 'Say the name once and reward the first small head turn, with food hidden until after the turn.',
    exercise: exercise('Name means turn', '2–3 minutes', ['A quiet familiar room', 'Five tiny high-value rewards hidden in a pocket or behind your back'], ['Wait until your dog is looking slightly away but is not deeply distracted.', 'Say the name once in a warm, clear voice.', 'Mark the first eye or head movement towards you.', 'Bring out the reward only after the turn and deliver it beside you.'], 'Do five repetitions with several seconds between each.'),
    difficultySigns: ['Watches the reward hand', 'Responds only after repetition', 'Avoids or slows after hearing the name'],
    successCriteria: ['Turns after the first name cue', 'Food remains hidden until after the response', 'Four successes out of five in this room'],
    stopConditions: ['A sudden hearing or cognitive change is possible', 'The name causes avoidance', 'Your dog becomes worried or disengaged'],
    fallbackLevel2: ['Move closer and use a quieter room.', 'Make one neutral sound before the next trial, then say the name once.', 'Use a better reward after the turn.'],
    fallbackLevel3: ['Choose a fresh orientation cue if the name has a strong negative history.', 'Condition the new cue only in easy situations.', 'Ask a veterinarian about sudden hearing or cognitive changes.'],
    professionalEscalation: 'Seek veterinary advice for a sudden response change, hearing concerns, confusion, or cognitive signs.',
    relatedLessonIds: ['recall-name-response'],
  }),
  protocol({
    id: 'sit-without-visible-lure', topicId: 'sit', likelyObstacle: 'The visible food or hand movement may have become part of the cue rather than a temporary teaching aid.',
    explanation: ['Dogs learn the whole picture around a behaviour. If food is always shown first, “sit” can mean sit only when food is visible.', 'The solution is not to stop rewarding. It is to hide the reward until after the response and make the signal gradually smaller.'],
    why: ['The selected pattern is consistent with lure dependence, an unclear signal, or incomplete generalisation.', 'An empty cue hand followed by a reward from the other hand separates the cue from the payment.'],
    primaryAdjustment: 'Use an empty cue hand and deliver the reward from the opposite hand only after the sit.',
    exercise: exercise('Fade the visible food', '2–3 minutes', ['A comfortable non-slip surface', 'Five small rewards held in the hand behind your back'], ['Show the same familiar hand signal with an empty hand.', 'Wait two seconds without repeating or pushing your dog.', 'Mark as the bottom touches the floor.', 'Reward from the other hand, then release and move between repetitions.'], 'Do three to five repetitions, ending before responses slow.'),
    difficultySigns: ['Stares at the hidden reward hand', 'Backs away or appears uncomfortable', 'Needs the full lure movement'],
    successCriteria: ['Sits with an empty cue hand', 'Responds within two seconds', 'Succeeds four times out of five on comfortable footing'],
    stopConditions: ['Sitting appears painful or suddenly difficult', 'Your dog repeatedly avoids the position', 'The surface is slippery or uncomfortable'],
    fallbackLevel2: ['Make the empty hand signal slightly more familiar.', 'Alternate one visible-lure repetition with two empty-hand repetitions.', 'Reward every successful empty-hand response.'],
    fallbackLevel3: ['Capture naturally offered sits instead of luring.', 'Rebuild the verbal or hand cue after the position is comfortable.', 'Arrange veterinary assessment if sitting is slow, uneven, or newly reluctant.'],
    professionalEscalation: 'Seek veterinary advice for sudden reluctance, uneven movement, pain, or difficulty getting up and down.',
    relatedLessonIds: ['impulse-control-wait-for-reward'],
  }),
  protocol({
    id: 'stay-one-second', topicId: 'stay', likelyObstacle: 'Duration, handler movement, or distraction was added before the starting position and release were clear.',
    explanation: ['A stay contains several separate skills: hold the position, tolerate time, handle distance or movement, and wait for a release.', 'Adding more than one difficulty factor at once produces frequent breaks. Rewarding before movement makes the successful moment clear.'],
    why: ['The selected pattern indicates that the current duration or distraction is too difficult.', 'A one-second stationary repetition creates a clean starting point without repeated failure.'],
    primaryAdjustment: 'Return to one second, reward while your dog is still in position, then use an exact release cue.',
    exercise: exercise('One-second stay reset', '2–3 minutes', ['A quiet room', 'A non-slip surface or mat', 'Five small rewards'], ['Ask for an easy position and remain still.', 'Pause for one second.', 'Mark and reward while your dog is still in position.', 'Say the same release cue and invite movement before resetting.'], 'Practise five repetitions using a 1, 1, 2, 1, 2-second pattern.'),
    difficultySigns: ['Moves before the reward', 'Watches your feet anxiously', 'Does not understand the release'],
    successCriteria: ['Holds position for the planned second', 'Receives the reward before moving', 'Moves only after the clear release in four of five repetitions'],
    stopConditions: ['The position is uncomfortable', 'Frustration or worry increases', 'The floor or surroundings are unsafe'],
    fallbackLevel2: ['Reinforce the starting position before saying stay.', 'Practise the release cue separately.', 'Do not move your feet until stationary duration is easy.'],
    fallbackLevel3: ['Teach the position and release as separate skills.', 'Use a comfortable mat or standing wait instead of sit.', 'Ask a qualified trainer to check cue and reward timing.'],
    professionalEscalation: 'Seek veterinary advice if holding or entering the position seems physically uncomfortable.',
    relatedLessonIds: ['impulse-control-wait-for-reward', 'impulse-control-doorways'],
  }),
  protocol({
    id: 'loose-lead-reset', topicId: 'loose-lead-walking', likelyObstacle: 'The route, trigger distance, or starting arousal is beyond the current loose-lead skill.',
    explanation: ['Pulling can be reinforced because it moves the dog towards smells, people, or other dogs. Fear and frustration can also increase forward pressure.', 'Equipment protects comfort and safety, but the walking skill grows through well-timed reinforcement and achievable routes.'],
    why: ['The selected situation identifies where lead tension begins.', 'Starting farther away and rewarding one or two slack steps prevents another long pulling rehearsal.'],
    primaryAdjustment: 'Increase distance from the difficult trigger and reward the first safe check-in or slack step.',
    exercise: exercise('Slack lead and check-in', '3–5 minutes', ['A quiet route or open space with an exit', 'Secure comfortable harness and fixed-length lead', 'High-value food and permission to sniff'], ['Begin far enough away that your dog can eat and turn towards you.', 'Mark one voluntary check-in and feed beside your leg.', 'Take one or two steps; mark while the lead is slack.', 'Reward beside your leg, then release to sniff or turn away.'], 'Complete five short slack-lead sequences, not a full walk.'),
    difficultySigns: ['Hard staring or inability to turn', 'Lead remains continuously tight', 'Cannot take food normally'],
    successCriteria: ['Can check in at the chosen distance', 'Completes five slack steps in four of five attempts', 'Body remains loose enough to sniff and eat'],
    stopConditions: ['Lunging, growling, or snapping', 'Traffic, escape, or fall risk', 'You cannot maintain safe physical control'],
    fallbackLevel2: ['Use a visual barrier or larger distance.', 'Practise a U-turn or hand target away from dogs.', 'Choose shorter, quieter outings and reward orientation.'],
    fallbackLevel3: ['Avoid close dog encounters and use management routes.', 'Get reward-based professional help for lunging, growling, or loss of control.', 'Ask a veterinarian about sudden changes or possible pain.'],
    professionalEscalation: 'Professional help is needed when pulling includes lunging, aggression, traffic risk, pain, or inability to maintain control.',
    relatedLessonIds: ['loose-lead-reward-zone', 'loose-lead-direction-changes', 'loose-lead-real-world-distractions'],
  }),
  protocol({
    id: 'settle-capture-calm', topicId: 'settling', likelyObstacle: 'The settle request is currently too long, too exciting, or arriving before physical and emotional needs are met.',
    explanation: ['Calm is easier to teach by noticing small relaxed behaviours than by repeatedly asking an already aroused dog to settle.', 'A comfortable mat can become a predictable station, but duration and busy environments must be added gradually.'],
    why: ['The answers suggest arousal, frustration, or an over-large duration step.', 'Rewarding one calm moment creates an achievable first repetition.'],
    primaryAdjustment: 'Stop asking for a long settle and quietly reward one naturally calm moment on or near a comfortable mat.',
    exercise: exercise('One calm moment', '2–4 minutes', ['A quiet area and comfortable non-slip mat', 'Tiny rewards placed calmly between the paws', 'Toileting, water, movement, and rest needs already met'], ['Sit quietly without repeating a settle cue.', 'Mark a small calm action: looking away, sniffing the mat, softer posture, sitting, or lying down.', 'Place the reward calmly on the mat.', 'After several seconds, release and offer a sniff or movement break.'], 'Reward three to five calm moments and finish.'),
    difficultySigns: ['Whining, pawing, or rapid movement increases', 'Cannot remain near the mat', 'Food delivery creates more excitement'],
    successCriteria: ['Offers at least one calm behaviour', 'Can eat gently and remain in the area', 'Completes three relaxed repetitions'],
    stopConditions: ['Sudden pacing, panting, inability to lie down, or pain signs', 'Panic, aggression, or compulsive activity', 'Urgent toileting, water, movement, or distance needs'],
    fallbackLevel2: ['Move to a quieter area and shorten the session.', 'Use calm enrichment or sniffing before the mat.', 'Reward a single calm observation rather than a full lie-down.'],
    fallbackLevel3: ['Review sleep, exercise, enrichment, triggers, and physical comfort.', 'Use structured relaxation only with an individualised plan.', 'Seek professional or veterinary help for persistent distress or restlessness.'],
    professionalEscalation: 'Seek veterinary help for sudden restlessness, night pacing, pain, panting without cause, or inability to lie down.',
    relatedLessonIds: ['impulse-control-wait-for-reward', 'impulse-control-doorways'],
  }),
  protocol({
    id: 'jumping-four-paws', topicId: 'jumping', likelyObstacle: 'Greeting excitement is stronger than the dog’s current four-paws-down skill.',
    explanation: ['Jumping often gains attention or access, even when the person pushes the dog away or speaks firmly.', 'Management prevents repeated jumping while calm access to people becomes the reward for four paws on the floor.'],
    why: ['The chosen greeting context is currently too exciting or lasts too long.', 'A barrier and brief greeting allow reinforcement before jumping begins.'],
    primaryAdjustment: 'Use a gate or lead and let a brief greeting begin only while four paws remain down.',
    exercise: exercise('Calm greeting rehearsal', '3–5 minutes', ['One calm adult helper', 'A gate or secure lead', 'Small rewards or access to greeting'], ['Begin far enough from the helper for four paws to stay down.', 'Mark and reward one calm look or step.', 'Let the helper approach for one second while paws remain down.', 'If jumping begins, the helper calmly pauses and moves away; reset at an easier distance.'], 'Complete three short greetings and stop.'),
    difficultySigns: ['Cannot keep paws down at the starting distance', 'Grabbing clothes or mouthing', 'Excitement increases after each greeting'],
    successCriteria: ['Four paws stay down as the helper approaches', 'Greeting remains one to three seconds', 'Three calm repetitions'],
    stopConditions: ['Knockdown or bite risk', 'A child or vulnerable person is involved', 'Mouthing or frustration escalates'],
    fallbackLevel2: ['Increase distance and use the barrier.', 'Reward a mat or four-paws position before any approach.', 'Make the helper less animated and the greeting shorter.'],
    fallbackLevel3: ['Practise the position without visitors.', 'Use management for real arrivals while training separately.', 'Seek professional help for grabbing, biting, or dangerous knockdowns.'],
    professionalEscalation: 'Get qualified help when jumping includes biting, guarding, severe frustration, or risk to children or vulnerable people.',
    relatedLessonIds: ['jumping-four-paws-down', 'jumping-calm-greetings', 'jumping-visitors-and-excitement'],
  }),
  protocol({
    id: 'barking-function-first', topicId: 'barking', likelyObstacle: 'The trigger or purpose of the barking has not yet been separated from the sound itself.',
    explanation: ['Barking can be driven by alerting, fear, frustration, attention, separation distress, discomfort, or normal needs.', 'A useful plan changes the trigger setup and teaches an alternative instead of punishing communication.'],
    why: ['The chosen pattern gives a starting hypothesis, not a diagnosis.', 'Recording what happens before and after barking helps choose management and reinforcement.'],
    primaryAdjustment: 'Prevent one predictable trigger and reward a calm alternative before prolonged barking starts.',
    exercise: exercise('Trigger and recovery plan', '3–5 minutes', ['A known mild trigger that occurs naturally', 'A curtain, gate, distance, or sound masking', 'Food, mat, or sniff activity'], ['Do not provoke barking; wait for the normal mild trigger.', 'At the first orientation, add distance or block the view.', 'Mark a brief quiet pause, head turn, or check-in.', 'Reward calmly, then guide to the prepared mat or sniff activity.'], 'Use the plan for one to three naturally occurring events.'),
    difficultySigns: ['No pause is available', 'Races back to the trigger', 'Cannot engage with food or enrichment'],
    successCriteria: ['Can disengage from the trigger', 'Offers a brief quiet or calm alternative', 'Recovery becomes faster across similar events'],
    stopConditions: ['Panic, aggression, or redirected behaviour', 'Sudden night barking or other health change', 'Separation-related destruction or escape attempts'],
    fallbackLevel2: ['Increase distance or improve the visual barrier.', 'Reward farther from the trigger.', 'Keep a short diary of trigger, distance, body language, and recovery.'],
    fallbackLevel3: ['Use a cause-specific plan with a qualified consultant.', 'Arrange veterinary assessment for sudden or unexplained changes.', 'Do not use anti-bark devices or punish growling and warning behaviour.'],
    professionalEscalation: 'Seek help for panic, aggression, separation distress, sudden changes, night barking, or inability to recover.',
    relatedLessonIds: ['barking-identify-triggers', 'barking-quiet-reinforcement', 'barking-real-world-management'],
  }),
  protocol({
    id: 'focus-check-in', topicId: 'focus', likelyObstacle: 'The session or environment is asking for more attention than the dog can currently offer.',
    explanation: ['Focus changes with sleep, development, stress, reward value, clarity, and the environment.', 'Voluntary check-ins are a practical foundation because the dog learns that choosing the handler is worthwhile.'],
    why: ['The selected pattern points to distraction, session length, or food positioning.', 'A micro-session captures engagement before it disappears.'],
    primaryAdjustment: 'Lower the distraction and reward the first voluntary glance rather than repeatedly asking for attention.',
    exercise: exercise('Three check-ins', '1–3 minutes', ['A quiet area', 'Three to five valued rewards', 'Optional permission to sniff as a reward'], ['Stand quietly and allow your dog to look around.', 'Mark the first voluntary glance towards you.', 'Deliver the reward near you, then release to look or sniff again.', 'Pause and wait for the next offered check-in.'], 'Finish after three to five check-ins.'),
    difficultySigns: ['Cannot eat ordinary rewards', 'Scans continuously', 'Turns away more after each repetition'],
    successCriteria: ['Offers three voluntary check-ins', 'Can reorient after looking around', 'Body remains loose and engaged'],
    stopConditions: ['Sudden inability to focus or extreme restlessness', 'Fear, freezing, or frantic behaviour', 'Possible pain or medical change'],
    fallbackLevel2: ['Move indoors or farther from activity.', 'Use a higher-value or functional reward such as sniffing.', 'Reduce to one successful check-in.'],
    fallbackLevel3: ['Review sleep, exercise, stress, and physical comfort.', 'Teach a hand target as an easy alternative.', 'Seek veterinary or behaviour help for sudden or severe changes.'],
    professionalEscalation: 'Seek veterinary advice for sudden cognitive, sensory, pain, or extreme restlessness changes.',
    relatedLessonIds: ['focus-check-in', 'focus-hold-attention', 'focus-around-distractions'],
  }),
  protocol({
    id: 'chewing-safe-choice', topicId: 'chewing', likelyObstacle: 'The available legal chew, management, or trade routine does not yet match what the dog gains from the household item.',
    explanation: ['Chewing can be normal exploration, teething, enrichment, stress relief, or part of separation distress.', 'Prevention and suitable choices are essential because repeatedly taking objects by force can create chasing, swallowing, or guarding.'],
    why: ['The selected pattern identifies reward value, alone-time distress, or removal conflict as the likely obstacle.', 'A calm trade and better management protect safety while the alternative is reinforced.'],
    primaryAdjustment: 'Remove access to unsafe items and offer one supervised chew matched to the dog’s size and chewing style.',
    exercise: exercise('Choose and trade safely', '3–5 minutes', ['A quiet supervised area', 'One veterinarian-appropriate chew', 'Higher-value food for a trade'], ['Place the safe chew down and allow voluntary investigation.', 'Mark calm interaction and add a small reward beside it.', 'After a short period, toss the trade reward a little away.', 'Pick up and inspect the chew only while your dog is away eating.'], 'Complete one calm chew-and-trade sequence.'),
    difficultySigns: ['Attempts to swallow pieces', 'Runs away or stiffens over the item', 'Abandons the chew to follow the person'],
    successCriteria: ['Chooses the legal chew', 'Engages calmly for several minutes', 'Moves away willingly for the trade'],
    stopConditions: ['Suspected swallowing, choking, or toxic/sharp item', 'Growling, guarding, or bite risk', 'Escape destruction or panic when alone'],
    fallbackLevel2: ['Try another safe texture or food toy.', 'Improve gates, storage, and supervision.', 'Practise trades only with low-risk items.'],
    fallbackLevel3: ['Ask a veterinarian about safe chew options or possible pica.', 'Use a qualified consultant for guarding or separation distress.', 'Do not chase or pry objects from the mouth.'],
    professionalEscalation: 'Urgent veterinary help is needed after suspected ingestion, choking, toxic exposure, or intestinal obstruction signs.',
    relatedLessonIds: ['chewing-appropriate-items', 'chewing-redirection-routine', 'chewing-independence-and-prevention'],
  }),
  protocol({
    id: 'reactivity-safe-distance', topicId: 'reactivity', likelyObstacle: 'The trigger is inside the dog’s current safe working distance or the encounter is too unpredictable.',
    explanation: ['Lunging and intense reactions can involve fear, frustration, predation, territorial behaviour, pain, or learning history.', 'Training begins where the dog can notice the trigger and still eat, respond, and recover. Distance is treatment, not failure.'],
    why: ['The selected trigger pattern indicates threshold and recovery are central.', 'A planned exit and calm check-in are safer than waiting for a reaction.'],
    primaryAdjustment: 'Increase distance immediately and work only where the dog can safely notice, eat, and disengage.',
    exercise: exercise('Notice and leave safely', '2–5 minutes', ['Secure harness and fixed lead', 'High-value food', 'A spacious location, visual barrier, and exit route'], ['Start farther away than you expect to need.', 'When the trigger appears, check that your dog can eat and has a relatively soft body.', 'Mark one calm notice or tiny head turn away.', 'Feed while moving farther away, then leave after up to three successful sightings.'], 'One to three sightings with full recovery between them.'),
    difficultySigns: ['Hard stare or stiff body', 'Takes food roughly or refuses it', 'Recovery becomes slower'],
    successCriteria: ['Can eat and respond at the recorded distance', 'Disengages within five seconds', 'Recovers within thirty seconds after each sighting'],
    stopConditions: ['Lunging, snapping, redirected behaviour, or bite risk', 'You cannot control the dog safely', 'A child, vulnerable person, traffic, livestock, or serious fighting risk is present'],
    fallbackLevel2: ['Use a barrier, quieter time, and greater distance.', 'Practise a U-turn, hand target, or find-it away from triggers.', 'Never force a greeting.'],
    fallbackLevel3: ['Stop planned exposure and use avoidance management.', 'Work with a qualified reward-based behaviour consultant.', 'Arrange veterinary assessment for sudden change, pain, severe anxiety, or aggression.'],
    professionalEscalation: 'Moderate or severe reactivity, aggression, bite history, or unpredictable reactions require individual professional and veterinary support.',
    relatedLessonIds: ['reactivity-safe-distance', 'reactivity-look-and-disengage'],
  }),
  protocol({
    id: 'house-training-routine', topicId: 'house-training', likelyObstacle: 'The current toileting schedule, supervision, or freedom does not match the dog’s physical need and learning history.',
    explanation: ['Reliable toileting develops through frequent opportunities, immediate reinforcement in the correct place, and careful supervision.', 'Regression in a previously reliable dog can have urinary, digestive, pain, stress, or age-related causes and should not be treated as disobedience.'],
    why: ['The selected pattern points to timing, increased freedom, or sudden regression.', 'An earlier outing and immediate outdoor reward give the clearest learning information.'],
    primaryAdjustment: 'Schedule the next supervised toileting trip before the usual accident time and reward immediately after toileting outside.',
    exercise: exercise('Earlier toileting success', '2–5 minutes', ['Lead if the area is not enclosed', 'Food rewards ready outdoors', 'A simple time and result log', 'Enzymatic cleaner for accidents'], ['Go to the same quiet toileting area before the predicted time.', 'Stand calmly and allow sniffing without starting play.', 'Mark as toileting finishes and reward within one or two seconds in that location.', 'Offer a brief sniff afterwards and record the time and result.'], 'Repeat at the next two likely toileting times.'),
    difficultySigns: ['Plays but does not toilet', 'Accidents follow new room access', 'Frequency or urgency changes'],
    successCriteria: ['Toilets in the chosen area', 'Reward arrives immediately outdoors', 'Four of five scheduled opportunities succeed'],
    stopConditions: ['Straining, blood, pain, vomiting, increased thirst, or unusual frequency', 'A previously reliable dog changes suddenly', 'The dog cannot physically wait for the schedule'],
    fallbackLevel2: ['Return indoors under close supervision and retry in ten minutes.', 'Temporarily reduce freedom after unsuccessful trips.', 'Move the next outing fifteen minutes earlier.'],
    fallbackLevel3: ['Arrange veterinary assessment for regression or physical signs.', 'Rebuild the schedule as if starting fresh.', 'Use a qualified trainer for routine mechanics after medical causes are addressed.'],
    professionalEscalation: 'Veterinary assessment comes first for sudden regression, straining, blood, pain, increased thirst, or marked frequency changes.',
    relatedLessonIds: ['house-training-routine', 'house-training-signal-and-reward', 'house-training-reliability'],
  }),
  protocol({
    id: 'confidence-choice', topicId: 'confidence', likelyObstacle: 'The new thing is too intense, too close, or difficult to escape.',
    explanation: ['Fear learning improves through choice and below-threshold exposure, not forced contact.', 'The dog should be free to retreat. Pairing a mild version of the trigger with something valued can gradually change the emotional response.'],
    why: ['The selected situation identifies novelty or intensity as the likely obstacle.', 'Increasing distance and rewarding voluntary investigation protects choice.'],
    primaryAdjustment: 'Increase distance and reward calm observation without luring the dog closer than they choose.',
    exercise: exercise('Look, choose, retreat', '2–4 minutes', ['A harmless mild version of the new thing', 'An open quiet area with a clear retreat path', 'High-value food'], ['Place the new thing far enough away for your dog to notice without freezing.', 'Mark a glance, sniff, or relaxed body shift.', 'Deliver or toss the reward away from the object so retreat remains easy.', 'Let your dog decide whether to look again; change only one feature next time.'], 'Complete three calm observations, not close approaches.'),
    difficultySigns: ['Freezing, hiding, or refusing food', 'Stretching forward while keeping the body back', 'Repeated startles or slow recovery'],
    successCriteria: ['Can observe and eat at the chosen distance', 'Retreats and re-engages voluntarily', 'Body remains relaxed across three observations'],
    stopConditions: ['Panic, frantic escape, self-injury, or snapping', 'The dog cannot eat or recover', 'Fear began suddenly or pain may contribute'],
    fallbackLevel2: ['Make the object quieter, smaller, farther away, or still.', 'Work from a doorway or behind a barrier.', 'Reward calm observation only; no approach is required.'],
    fallbackLevel3: ['Stop exposure and manage the environment.', 'Use an individual desensitisation and counterconditioning plan.', 'Seek veterinary or certified behaviour help for intense, broad, or worsening fear.'],
    professionalEscalation: 'Professional help is needed for panic, self-injury, aggression, inability to eat, severe generalised fear, or sudden change.',
    relatedLessonIds: ['confidence-choice-and-exploration', 'confidence-new-surfaces-and-sounds', 'confidence-new-environments'],
  }),
];

export function protocolForTopic(topicId: TroubleshooterTopicId): TroubleshooterProtocol {
  const result = protocols.find((candidate) => candidate.topicId === topicId);
  if (!result) throw new Error(`Missing troubleshooter protocol for ${topicId}`);
  return result;
}

export const troubleshooterProtocols: readonly TroubleshooterProtocol[] = Object.freeze(protocols);

function protocol(value: Omit<TroubleshooterProtocol, 'protocolVersion' | 'reviewStatus'>): TroubleshooterProtocol {
  return Object.freeze({ ...value, protocolVersion: 1, reviewStatus: 'professional-review-required' });
}

function exercise(
  title: string,
  minutes: string,
  setup: readonly string[],
  steps: readonly string[],
  repetitions: string,
): TroubleshooterProtocol['exercise'] {
  return Object.freeze({ title, minutes, setup: Object.freeze(setup), steps: Object.freeze(steps), repetitions });
}
