import { authorLesson } from '../authorLesson';

export const barkingLessons = [
  authorLesson({
    id: 'barking-identify-triggers', title: 'Identify Barking Triggers', shortDescription: 'Observe when barking happens so you can respond to its cause rather than punish the sound.', skill: 'barking', difficultyLevel: 1, estimatedMinutes: 6,
    goal: 'You can identify common triggers, distance, duration, and what helps your dog recover.', equipment: ['A simple notes app or paper log', 'Food for calm reinforcement', 'A quiet observation point'], prerequisites: [],
    steps: ['1. Choose one normal part of the day to observe without deliberately creating barking.', '2. Record what happened immediately before the barking, including sound, sight, location, and distance.', '3. Note the dog’s body language and how long barking continued.', '4. Record what naturally helped, such as added distance, closing a curtain, or moving rooms.', '5. Review three observations and choose one trigger that can be managed safely.'],
    tips: ['Describe what you see rather than guessing motives.', 'Include normal needs such as toileting or rest.', 'Look for patterns across several days.'],
    commonMistakes: ['Treating all barking as bad or identical.', 'Deliberately provoking barking to collect data.', 'Ignoring signs of fear, pain, or unmet needs.'],
    troubleshooting: [{ problem: 'Triggers seem random.', solution: 'Add time, location, activity, and recent rest to the log for a clearer pattern.' }, { problem: 'Barking is too intense to observe closely.', solution: 'Use immediate management and record details only after everyone is safe.' }, { problem: 'Barking has changed suddenly.', solution: 'Arrange veterinary advice, especially if other behaviour or health changes are present.' }],
    safetyNotes: ['Do not provoke barking; sudden or unexplained changes warrant veterinary support, and urgent safety concerns need qualified help.'], completionDescription: 'The owner records at least three naturally occurring barking events with a specific trigger, context, duration, and recovery strategy for each.', tags: ['foundation', 'barking', 'home'],
  }),
  authorLesson({
    id: 'barking-quiet-reinforcement', title: 'Reinforce Quiet Moments', shortDescription: 'Teach a calm alternative by rewarding brief quiet pauses around a manageable trigger.', skill: 'barking', difficultyLevel: 2, estimatedMinutes: 8,
    goal: 'Your dog can notice a mild trigger and receive reinforcement during a short quiet pause.', equipment: ['High-value food rewards', 'A manageable known trigger', 'A visual barrier if needed'], prerequisites: [{ lessonId: 'barking-identify-triggers', minimumSuccessfulCompletions: 1 }],
    steps: ['1. Set up far enough from the trigger that barking is unlikely or brief.', '2. Let your dog notice it and wait for one natural pause without repeating a “quiet” cue.', '3. Mark the pause and deliver several small rewards calmly.', '4. Move away or block the trigger before barking builds again.', '5. Repeat three to five times, gradually rewarding slightly longer quiet periods.'],
    tips: ['Begin with a one-second pause.', 'Management can prevent rehearsal between sessions.', 'Reward calm breathing and turning away as well as silence.'],
    commonMistakes: ['Shouting “quiet”, which may add more noise.', 'Waiting for a long silence before rewarding.', 'Working too close to the trigger.'],
    troubleshooting: [{ problem: 'There is no pause to reward.', solution: 'Increase distance or use a barrier until your dog can briefly disengage.' }, { problem: 'Barking resumes as food stops.', solution: 'Use several rewards, then move away before the trigger becomes difficult again.' }, { problem: 'The dog becomes excited by rapid treats.', solution: 'Scatter food for sniffing or use slower delivery in a quieter location.' }],
    safetyNotes: ['Do not suppress warning barking around genuine danger; address the cause and use distance or barriers when your dog is distressed.'], completionDescription: 'Around a mild known trigger, the dog offers a quiet pause of at least three seconds in four of five managed repetitions.', tags: ['barking', 'home', 'focus'],
  }),
  authorLesson({
    id: 'barking-real-world-management', title: 'Real-World Barking Management', shortDescription: 'Combine prevention, calm alternatives, and reinforcement in an everyday routine.', skill: 'barking', difficultyLevel: 3, estimatedMinutes: 12,
    goal: 'Your dog can move from a known trigger to a practised calm activity with less repeated barking.', equipment: ['Food rewards', 'A mat or safe resting area', 'Curtains, gate, or sound masking as appropriate', 'A safe enrichment item'], prerequisites: [{ lessonId: 'barking-quiet-reinforcement', minimumSuccessfulCompletions: 1 }],
    steps: ['1. Choose one predictable trigger and prepare barriers, rewards, and a calm activity before it occurs.', '2. At the first sign of attention to the trigger, guide your dog away rather than waiting for prolonged barking.', '3. Reward a quiet check-in, then offer the mat, sniff scatter, or safe enrichment.', '4. Keep the trigger reduced while your dog settles and avoid repeatedly exposing them.', '5. Track recovery time over several real events and adjust management when needed.'],
    tips: ['Preventing rehearsal is useful training.', 'Match the alternative activity to your dog’s needs.', 'Aim for faster recovery, not complete silence in every situation.'],
    commonMistakes: ['Removing management too quickly.', 'Using the plan only after barking is intense.', 'Expecting barking to disappear regardless of cause.'],
    troubleshooting: [{ problem: 'The dog races back to the trigger.', solution: 'Improve the barrier and deliver the calm activity farther from the trigger.' }, { problem: 'The dog will not engage with enrichment.', solution: 'Increase distance and choose an easier, familiar activity.' }, { problem: 'Barking is worsening or unpredictable.', solution: 'Seek a qualified force-free trainer and veterinary guidance to assess contributing factors.' }],
    safetyNotes: ['Respect barking as communication; use secure management and seek professional or veterinary help if reactions are intense, sudden, or create injury risk.'], completionDescription: 'For three predictable trigger events, the dog transitions to the planned calm activity within one minute and avoids prolonged repeated barking in at least two events.', tags: ['barking', 'home', 'safety'],
  }),
] as const;
