import { authorLesson } from '../authorLesson';

export const chewingLessons = [
  authorLesson({
    id: 'chewing-appropriate-items', title: 'Choose Appropriate Chews', shortDescription: 'Make safe, suitable chewing options easy and rewarding to choose.', skill: 'chewing', difficultyLevel: 1, estimatedMinutes: 6,
    goal: 'Your dog willingly chooses an appropriate chew when it is offered in a calm setting.', equipment: ['Two veterinarian-appropriate chew options', 'Food rewards', 'A supervised quiet area'], prerequisites: [],
    steps: ['1. Select chews that suit your dog’s size, chewing style, and health needs.', '2. Remove unsafe household items from the immediate area before practice.', '3. Present one chew on the floor and let your dog investigate without pushing it towards them.', '4. Mark and reward calm interaction with the chew, then allow continued access while supervised.', '5. After a short period, trade the chew for food and inspect it for damage.'],
    tips: ['Rotate a small number of safe options.', 'Supervise until you know how your dog chews each item.', 'Use a calm location where competition is unlikely.'],
    commonMistakes: ['Offering an item that can splinter or be swallowed.', 'Forcing the chew into the dog’s mouth.', 'Chasing the dog to take an item away.'],
    troubleshooting: [{ problem: 'The dog ignores the chew.', solution: 'Try a different safe texture or add a small amount of suitable food to it.' }, { problem: 'The dog tries to swallow pieces.', solution: 'Remove the item by trading and ask a veterinarian about safer alternatives.' }, { problem: 'The dog guards the chew.', solution: 'Stop direct removal, create distance, and seek qualified force-free support for a safe plan.' }],
    safetyNotes: ['Discard damaged items and seek urgent veterinary advice after suspected swallowing, choking, or ingestion of a toxic or sharp object.'], completionDescription: 'The dog chooses and calmly uses a suitable chew for three supervised minutes on three separate occasions.', tags: ['foundation', 'chewing', 'home'],
  }),
  authorLesson({
    id: 'chewing-redirection-routine', title: 'A Calm Redirection Routine', shortDescription: 'Guide your dog from an unsuitable object to a safe alternative without conflict.', skill: 'chewing', difficultyLevel: 2, estimatedMinutes: 8,
    goal: 'Your dog can leave a low-risk household object and engage with an appropriate chew after a calm trade.', equipment: ['A safe chew', 'High-value food rewards', 'One clean low-risk practice object'], prerequisites: [{ lessonId: 'chewing-appropriate-items', minimumSuccessfulCompletions: 1 }],
    steps: ['1. Place a low-value, non-hazardous practice object within view while keeping the safe chew ready.', '2. If your dog approaches the object, call them away once and scatter two rewards nearby.', '3. Quietly remove the practice object while the dog eats.', '4. Offer the safe chew and reward when your dog engages with it.', '5. Repeat only a few times, then secure tempting household items out of reach.'],
    tips: ['Practise with safe low-value objects, never real hazards.', 'Keep your response calm and predictable.', 'Reward moving away before the dog picks the object up when possible.'],
    commonMistakes: ['Prying an object from the dog’s mouth.', 'Using a dangerous item for a realistic test.', 'Redirecting repeatedly without improving household management.'],
    troubleshooting: [{ problem: 'The dog runs away with the object.', solution: 'Do not chase; toss food away from the object and improve barriers before practising again.' }, { problem: 'The dog returns to the same object.', solution: 'Remove access completely and provide a longer-lasting safe activity.' }, { problem: 'The dog will not trade.', solution: 'Use a higher-value reward and seek professional guidance if guarding or swallowing is a concern.' }],
    safetyNotes: ['Never practise with medicines, batteries, string, cooked bones, sharp items, or anything the dog might swallow.'], completionDescription: 'The dog moves from a safe practice object to an appropriate chew after one calm redirection in four of five attempts.', tags: ['chewing', 'home', 'safety'],
  }),
  authorLesson({
    id: 'chewing-independence-and-prevention', title: 'Independence and Prevention', shortDescription: 'Build a practical routine that meets chewing needs while preventing unsafe choices.', skill: 'chewing', difficultyLevel: 3, estimatedMinutes: 11,
    goal: 'Your dog settles with a safe chewing activity while normal household movement occurs nearby.', equipment: ['A dog-safe rest area', 'A suitable long-lasting chew or food toy', 'Gates or storage for household items', 'A timer'], prerequisites: [{ lessonId: 'chewing-redirection-routine', minimumSuccessfulCompletions: 1 }],
    steps: ['1. Dog-proof the area and prepare a safe chew matched to your dog’s habits.', '2. Invite your dog into the rest area and provide the chew without closing them in immediately.', '3. Move around normally for thirty seconds while staying close enough to supervise.', '4. Return calmly, add a small reward beside the chew, and increase duration in one-minute steps.', '5. Finish before the dog abandons the chew, then store both safe and unsafe items securely.'],
    tips: ['Schedule chewing after exercise and toileting needs are met.', 'Increase time gradually rather than leaving suddenly.', 'Continue supervision for any item that could break apart.'],
    commonMistakes: ['Assuming a “durable” toy is indestructible.', 'Using confinement without teaching the dog to relax there.', 'Leaving tempting hazards available to test reliability.'],
    troubleshooting: [{ problem: 'The dog leaves the chew to follow you.', solution: 'Reduce movement and duration, then reward a few seconds of independent engagement.' }, { problem: 'Destructive chewing happens when alone.', solution: 'Shorten absences, improve management, and seek force-free support for possible separation distress.' }, { problem: 'Chewing suddenly becomes intense or compulsive.', solution: 'Arrange veterinary assessment to check for pain, gastrointestinal issues, or other health changes.' }],
    safetyNotes: ['Supervise chew safety and contact a veterinarian after suspected ingestion or any sudden, compulsive change in chewing.'], completionDescription: 'The dog remains calmly engaged with a safe chew for five supervised minutes while the owner moves normally nearby on three occasions.', tags: ['chewing', 'home', 'confidence'],
  }),
] as const;
