import { authorLesson } from '../authorLesson';

export const confidenceLessons = [
  authorLesson({
    id: 'confidence-choice-and-exploration', title: 'Choice and Exploration', shortDescription: 'Build confidence by rewarding voluntary investigation and respecting retreat.', skill: 'confidence', difficultyLevel: 1, estimatedMinutes: 6,
    goal: 'Your dog chooses to investigate one harmless unfamiliar object while remaining free to move away.', equipment: ['Food rewards', 'One harmless unfamiliar object', 'A quiet open area'], prerequisites: [],
    steps: ['1. Place the harmless object on the floor well away from your dog’s resting space.', '2. Let your dog enter the area voluntarily with a clear route to retreat.', '3. Mark and reward looking towards, sniffing near, or calmly moving around the object.', '4. Toss rewards away from the object occasionally so moving away is part of the exercise.', '5. Stop after several relaxed choices and remove the object when your dog is elsewhere.'],
    tips: ['Reward curiosity at any distance.', 'Keep the object still at first.', 'Let retreat reset the exercise rather than ending in failure.'],
    commonMistakes: ['Holding the dog close to the object.', 'Luring so near that the dog feels trapped.', 'Assuming refusal is stubbornness.'],
    troubleshooting: [{ problem: 'The dog will not enter the room.', solution: 'Move the object farther away or out of sight and reward calm behaviour at the doorway.' }, { problem: 'The dog grabs or knocks the object.', solution: 'Use a less exciting object and reward slower investigation from a distance.' }, { problem: 'The dog shows tense body language.', solution: 'Remove pressure, increase distance, and finish with an easy familiar activity.' }],
    safetyNotes: ['Never force interaction; use stable, non-toxic objects and always allow your dog to retreat.'], completionDescription: 'The dog voluntarily approaches within one metre of a harmless unfamiliar object with relaxed body language on three separate repetitions.', tags: ['foundation', 'confidence', 'home'],
  }),
  authorLesson({
    id: 'confidence-new-surfaces-and-sounds', title: 'New Surfaces and Sounds', shortDescription: 'Introduce gentle sensory changes through choice and gradual exposure.', skill: 'confidence', difficultyLevel: 2, estimatedMinutes: 9,
    goal: 'Your dog can voluntarily investigate a mild new surface or sound and recover calmly.', equipment: ['Food rewards', 'One stable textured surface', 'One low-volume everyday sound', 'A non-slip floor'], prerequisites: [{ lessonId: 'confidence-choice-and-exploration', minimumSuccessfulCompletions: 1 }],
    steps: ['1. Place a stable textured mat beside familiar flooring so your dog can choose either surface.', '2. Reward looking at or stepping towards the mat without pulling the dog onto it.', '3. Scatter one or two rewards near the edge, then toss one away to invite retreat.', '4. In a separate set, play one everyday sound at barely noticeable volume and reward relaxed behaviour.', '5. Increase only texture contact or sound volume slightly after repeated calm responses.'],
    tips: ['Work on surface and sound exercises separately.', 'Use non-slip materials that cannot shift.', 'Watch recovery speed, not just approach distance.'],
    commonMistakes: ['Forcing all four paws onto a surface.', 'Increasing sound volume because the dog did not visibly react.', 'Blocking the dog’s path away.'],
    troubleshooting: [{ problem: 'The dog stretches without stepping on.', solution: 'Reward that choice and make the surface smaller or more familiar.' }, { problem: 'The sound causes a startle.', solution: 'Stop the sound, allow recovery, and restart another day at a much lower volume.' }, { problem: 'Progress changes between days.', solution: 'Begin each session at an easy level and follow the dog’s response that day.' }],
    safetyNotes: ['Never force a frightened dog towards a sound or surface; stop if the dog cannot recover, eat, or choose to re-engage.'], completionDescription: 'The dog voluntarily places at least two paws on a stable new surface and remains relaxed through three presentations of a low-volume everyday sound.', tags: ['confidence', 'home', 'safety'],
  }),
  authorLesson({
    id: 'confidence-new-environments', title: 'Explore New Environments', shortDescription: 'Transfer choice-based confidence skills to a quiet unfamiliar location.', skill: 'confidence', difficultyLevel: 3, estimatedMinutes: 12,
    goal: 'Your dog can explore a quiet new environment, check in, and recover from mild novelty.', equipment: ['A secure well-fitted harness and lead', 'High-value rewards', 'Water', 'A quiet planned location'], prerequisites: [{ lessonId: 'confidence-new-surfaces-and-sounds', minimumSuccessfulCompletions: 1 }],
    steps: ['1. Choose a quiet location with space to leave and visit at a low-traffic time.', '2. Begin at the edge and allow your dog to watch or sniff without moving forward.', '3. Reward check-ins, relaxed sniffing, and voluntary steps while keeping the lead loose.', '4. After a mild new sight or sound, pause and give your dog time to recover or retreat.', '5. Leave after five to ten calm minutes, before tiredness or worry accumulates.'],
    tips: ['A short visit beside the car can be enough.', 'Revisit the same place before choosing somewhere harder.', 'Let your dog set the exploration pace.'],
    commonMistakes: ['Choosing a crowded location for the first visit.', 'Pulling the dog towards something they avoid.', 'Staying until the dog is exhausted.'],
    troubleshooting: [{ problem: 'The dog will not leave the starting point.', solution: 'Stay there, reward calm observation, and leave without forcing progress.' }, { problem: 'The dog startles repeatedly.', solution: 'Move to a quieter area or end the visit and choose an easier location next time.' }, { problem: 'The dog refuses food.', solution: 'Increase distance from activity and prioritise leaving safely over completing the exercise.' }],
    safetyNotes: ['Allow retreat at all times, use secure equipment, and seek qualified force-free or veterinary support if fear is intense, worsening, or sudden.'], completionDescription: 'During three visits to the same quiet new location, the dog explores voluntarily for five minutes and recovers from mild novelty within thirty seconds.', tags: ['confidence', 'outdoors', 'safety'],
  }),
] as const;
