import { authorLesson } from '../authorLesson';

export const houseTrainingLessons = [
  authorLesson({
    id: 'house-training-routine', title: 'Build a Toileting Routine', shortDescription: 'Use timing, supervision, and immediate rewards to make the right location easy to choose.', skill: 'house-training', difficultyLevel: 1, estimatedMinutes: 6,
    goal: 'Your dog follows a predictable routine and toilets in the chosen area with prompt reinforcement.', equipment: ['Lead if the toileting area is not enclosed', 'Food rewards', 'A simple toileting log', 'Enzymatic cleaner'], prerequisites: [],
    steps: ['1. Take your dog to the chosen area after waking, eating, play, and other likely toileting times.', '2. Stand quietly and allow enough lead for sniffing without starting a game.', '3. Mark calmly as toileting finishes, then reward immediately in that location.', '4. Offer a brief sniff or play afterwards so toileting does not always end outdoor time.', '5. Log the time and result to plan the next supervised trip.'],
    tips: ['Reward within a second or two of finishing.', 'Use the same easy-to-reach area initially.', 'Supervise closely between scheduled trips.'],
    commonMistakes: ['Punishing accidents or showing the dog the mess.', 'Waiting too long between opportunities.', 'Rewarding only after returning indoors.'],
    troubleshooting: [{ problem: 'The dog plays but does not toilet.', solution: 'Return indoors under close supervision and try again after ten minutes.' }, { problem: 'Accidents occur at similar times.', solution: 'Schedule the next outing fifteen minutes before the usual time.' }, { problem: 'The dog toilets very frequently or has a sudden change.', solution: 'Contact a veterinarian to rule out urinary, digestive, or pain-related causes.' }],
    safetyNotes: ['Never punish accidents; clean calmly and seek veterinary support for sudden changes, straining, pain, or unusual frequency.'], completionDescription: 'The dog toilets in the chosen area and receives an immediate reward on at least four of five scheduled opportunities across two days.', tags: ['foundation', 'house-training', 'home'],
  }),
  authorLesson({
    id: 'house-training-signal-and-reward', title: 'Signal and Reward', shortDescription: 'Pair the established routine with a clear way for your dog to request access.', skill: 'house-training', difficultyLevel: 2, estimatedMinutes: 8,
    goal: 'Your dog uses a consistent, low-key signal before being taken to the toileting area.', equipment: ['Food rewards', 'A consistent door or exit point', 'An optional accessible bell or mat', 'A toileting log'], prerequisites: [{ lessonId: 'house-training-routine', minimumSuccessfulCompletions: 1 }],
    steps: ['1. Choose a simple signal such as standing on a mat or touching an accessible bell.', '2. Prompt the signal immediately before every scheduled toileting trip.', '3. Open the door as soon as the signal occurs and go directly to the toileting area.', '4. Reward after toileting, not merely for repeatedly sounding the signal.', '5. Gradually pause for one second to let your dog offer the signal before prompting.'],
    tips: ['Keep the signal easy for your dog’s body and size.', 'Respond consistently while the skill is new.', 'Continue scheduled trips rather than relying on the signal alone.'],
    commonMistakes: ['Choosing a signal the dog cannot perform comfortably.', 'Ignoring genuine requests because the timing seems inconvenient.', 'Turning the bell into an unrestricted request for outdoor entertainment.'],
    troubleshooting: [{ problem: 'The dog uses the signal but does not toilet.', solution: 'Offer a brief quiet toileting trip, then return indoors without play.' }, { problem: 'The dog never signals independently.', solution: 'Prompt immediately before the door opens and reward successful toileting consistently.' }, { problem: 'The dog signals too late.', solution: 'Increase scheduled opportunities while the signal continues developing.' }],
    safetyNotes: ['Do not withhold toileting access to test the signal, and never punish a missed or late request.'], completionDescription: 'Before four of five scheduled toileting trips, the dog offers or follows one prompt for the chosen signal and then toilets in the correct area.', tags: ['house-training', 'home', 'focus'],
  }),
  authorLesson({
    id: 'house-training-reliability', title: 'Build House-Training Reliability', shortDescription: 'Gradually extend freedom and routine changes while protecting successful habits.', skill: 'house-training', difficultyLevel: 3, estimatedMinutes: 12,
    goal: 'Your dog remains reliable with modest changes in room access, timing, or location.', equipment: ['Food rewards', 'Gates or a safe rest area', 'A toileting log', 'Enzymatic cleaner'], prerequisites: [{ lessonId: 'house-training-signal-and-reward', minimumSuccessfulCompletions: 1 }],
    steps: ['1. Review the log and identify a reliable interval that has produced no recent accidents.', '2. Add access to one small new area for ten supervised minutes after successful toileting.', '3. Keep scheduled outings and reward in the correct location as usual.', '4. Change only one factor at a time, such as room, interval, weather, or exit door.', '5. If an accident occurs, reduce freedom temporarily and resume the last successful schedule.'],
    tips: ['Progress by successful days, not by a fixed calendar.', 'Maintain more frequent trips during travel or routine changes.', 'Treat setbacks as useful scheduling information.'],
    commonMistakes: ['Giving full household access too quickly.', 'Changing several routine factors at once.', 'Stopping rewards immediately after a few successful days.'],
    troubleshooting: [{ problem: 'Accidents return in a new room.', solution: 'Supervise there for shorter periods immediately after toileting.' }, { problem: 'Bad weather disrupts the routine.', solution: 'Use shelter, high-value rewards, and shorter more frequent opportunities.' }, { problem: 'A previously reliable dog changes suddenly.', solution: 'Arrange veterinary assessment before assuming the dog has forgotten training.' }],
    safetyNotes: ['Never punish accidents; sudden regression, pain, increased thirst, or altered toileting needs should be discussed with a veterinarian.'], completionDescription: 'The dog completes seven consecutive days without an accident while one planned increase in supervised freedom is introduced.', tags: ['house-training', 'home', 'confidence'],
  }),
] as const;
