import { authorLesson } from '../authorLesson';

export const reactivityLessons = [
  authorLesson({
    id: 'reactivity-safe-distance', title: 'Find a Safe Working Distance', shortDescription: 'Observe triggers from far enough away that your dog can remain safe, eat, and recover.', skill: 'reactivity', difficultyLevel: 1, estimatedMinutes: 7,
    goal: 'You can identify and maintain a distance where your dog notices a trigger without reacting intensely.', equipment: ['A secure well-fitted harness', 'A sturdy standard lead', 'High-value food rewards', 'A spacious location with an easy exit'], prerequisites: [],
    steps: ['1. Choose a spacious location where triggers are predictable and can be observed from far away.', '2. Check that the harness and lead are secure, then position yourself near a clear exit route.', '3. When a trigger appears, watch whether your dog can eat, respond to their name, and keep a relatively soft body.', '4. Mark and reward calm noticing without moving closer to the trigger.', '5. Increase distance immediately if your dog stiffens, cannot eat, cannot disengage, or struggles to recover.'],
    tips: ['Begin farther away than you think you need.', 'Use parked cars or vegetation as visual barriers.', 'Keep sessions brief and include decompression afterwards.'],
    commonMistakes: ['Moving closer to test the dog’s limit.', 'Allowing forced greetings.', 'Holding the lead tight while remaining near the trigger.'],
    troubleshooting: [{ problem: 'The dog reacts as soon as the trigger appears.', solution: 'Choose a quieter location, add a visual barrier, or work at a much greater distance.' }, { problem: 'The dog cannot take food.', solution: 'Leave the area calmly; inability to eat is a clear sign the setup is too difficult.' }, { problem: 'Reactions are intense, unpredictable, or worsening.', solution: 'Pause app exercises and contact a qualified force-free trainer or veterinary behaviour professional.' }],
    safetyNotes: ['Never deliberately provoke a reaction or risk a greeting. Three app lessons cannot resolve every serious reactivity or aggression case; seek professional help when there is injury risk, and veterinary support for sudden changes that may involve pain or illness.'], completionDescription: 'Across three trigger sightings, the dog remains able to eat, respond, and recover within thirty seconds at the recorded safe distance.', tags: ['foundation', 'reactivity', 'safety'],
  }),
  authorLesson({
    id: 'reactivity-look-and-disengage', title: 'Look and Disengage', shortDescription: 'Reinforce the choice to look away from a trigger while staying below reaction threshold.', skill: 'reactivity', difficultyLevel: 2, estimatedMinutes: 10,
    goal: 'Your dog can notice a trigger and voluntarily turn away at a safe distance.', equipment: ['A secure well-fitted harness', 'A sturdy standard lead', 'High-value food rewards', 'A location with generous distance and exits'], prerequisites: [{ lessonId: 'reactivity-safe-distance', minimumSuccessfulCompletions: 1 }],
    steps: ['1. Start beyond the safe distance recorded in the foundation lesson.', '2. Let your dog notice the trigger briefly without asking them to approach.', '3. Mark the first head turn, eye movement, sniff, or body shift away from the trigger.', '4. Deliver several rewards while moving another step away.', '5. End after three successful disengagements and leave before the trigger becomes harder.'],
    tips: ['Reward tiny disengagements at first.', 'Movement away can be part of the reward.', 'Use only predictable triggers with ample space.'],
    commonMistakes: ['Waiting for full eye contact before rewarding.', 'Reducing distance after every success.', 'Continuing when the dog cannot recover between sightings.'],
    troubleshooting: [{ problem: 'The dog stares without disengaging.', solution: 'Increase distance or move behind a visual barrier rather than repeating cues.' }, { problem: 'The dog takes food roughly.', solution: 'Treat that as rising arousal, move farther away, and end the set early.' }, { problem: 'The dog redirects towards the lead or owner.', solution: 'Prioritise immediate distance and obtain qualified professional support before further setups.' }],
    safetyNotes: ['Keep the dog below threshold, avoid forced greetings, and never place any person or animal at risk. Serious cases need individual force-free and veterinary support beyond these three app lessons.'], completionDescription: 'At a safe distance, the dog voluntarily disengages from a visible trigger within five seconds in four of five opportunities.', tags: ['reactivity', 'focus', 'safety'],
  }),
  authorLesson({
    id: 'reactivity-controlled-exposure', title: 'Carefully Controlled Exposure', shortDescription: 'Practise predictable, below-threshold trigger sightings with a safety-first plan.', skill: 'reactivity', difficultyLevel: 3, estimatedMinutes: 14,
    goal: 'Your dog can complete a short controlled session with repeated recovery and no forced interaction.', equipment: ['A secure well-fitted harness', 'A sturdy standard lead', 'High-value food rewards', 'A skilled adult helper if appropriate', 'Barriers and an exit plan'], prerequisites: [{ lessonId: 'reactivity-look-and-disengage', minimumSuccessfulCompletions: 1 }],
    steps: ['1. Plan the trigger type, starting distance, barriers, helper movement, and exit before bringing your dog into view.', '2. Begin beyond the dog’s established working distance and confirm they can eat and respond.', '3. Present one brief, predictable trigger movement while reinforcing looking and disengaging.', '4. Move away for at least thirty seconds of recovery before another presentation.', '5. Complete no more than three successful presentations and finish while the dog remains settled.'],
    tips: ['Use a qualified force-free professional to plan setups when risk is uncertain.', 'Change only distance, duration, or movement in one session.', 'A calm retreat is a successful training choice.'],
    commonMistakes: ['Using uncontrolled public encounters as practice.', 'Asking the helper to approach for a greeting.', 'Continuing because the dog managed one difficult repetition.'],
    troubleshooting: [{ problem: 'Recovery takes longer after each presentation.', solution: 'End the session and make the next setup shorter and farther away.' }, { problem: 'The dog cannot eat, respond, or disengage.', solution: 'Increase distance immediately and leave using the planned exit.' }, { problem: 'Behaviour presents an injury risk.', solution: 'Do not continue independently; work with a qualified force-free trainer or veterinary behaviour professional.' }],
    safetyNotes: ['No app setup should risk injury or use flooding. Three lessons cannot resolve every serious reactivity or aggression case; seek veterinary support for sudden changes and professional help for intense, worsening, or unpredictable reactions.'], completionDescription: 'In a planned below-threshold setup, the dog completes three brief trigger presentations while eating, disengaging, and recovering within thirty seconds each time.', tags: ['reactivity', 'outdoors', 'safety'],
  }),
] as const;
