export const storageKeys = {
  appState: '@good-dog-academy/app-state',
  schemaVersion: '@good-dog-academy/schema-version',
  owners: '@good-dog-academy/domain/owners',
  dogs: '@good-dog-academy/domain/dogs',
  behaviourProfiles: '@good-dog-academy/domain/behaviour-profiles',
  behaviourAssessments: '@good-dog-academy/domain/behaviour-assessments',
  lessonProgress: '@good-dog-academy/domain/lesson-progress',
  dailyPlans: '@good-dog-academy/domain/daily-plans',
  trainingSessions: '@good-dog-academy/domain/training-sessions',
  adaptiveTrainingMemory: '@good-dog-academy/adaptive/training-memory-v1',
  adaptiveSessionHistory: '@good-dog-academy/adaptive/session-history-v1',
  poseShadowValidation: '@good-dog-academy/vision/pose-shadow-validation-v1',
  achievements: '@good-dog-academy/domain/achievements',
  progress: '@good-dog-academy/domain/progress',
  notificationSettings: '@good-dog-academy/domain/notification-settings',
  troubleshooterAttempts: '@good-dog-academy/domain/troubleshooter-attempts',
  developmentSeedVersion: '@good-dog-academy/development/seed-version',
} as const;
